### ISSUE TITLE
Content change for Travel page

### ISSUE THREAD

**Issue by mtemplet** [18F/nsf-sbir#1014]
https://seedfund.nsf.gov/resources/review/travel/

Need to replace, "The National Science Foundation is at the Ballston-MU station on the Orange Line in Virginia" replaced with “at the Eisenhower Avenue station on the Yellow Line in Virginia.”  This statement is found in two places on the page Making Air and Hotel sections.  

Search for “Ballston” across our pages and ensure it is updated everywhere.

**Comment by seakhtar** [comment]
Hi @mtemplet -

Sorry, I was out last week- this looks finished up but let me know if there's anything left to do for this issue.

**Comment by mtemplet** [comment]
No problem, @seakhtar ! This is all done :)
