### ISSUE TITLE
Updates tied to the June 2018 Phase I Solicitation

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1038]
The new solicitation will go live around March 14. Here are the changes that need to be made...

Topics
- [x] Adding new topic areas - medical devices, etc. 
- [x] Removing Smart Health
- [ ] Adding updated PDF of all topic areas

Program Directors
- [x] Add Nancy and Linda
- [x] Remove Jesus

- [x] Add webinar dates

- [ ] Add new link to FAQs

SAM Registration

- [x] Link to the SAM Quick Start Page - https://www.sam.gov/sam/transcript/Quick_Guide_for_Grants_Registrations.pdf
- [x] Add a step to the timeline 
- [x] active
 - [X] inactive

Company Lists
- [ ] Fix the lists to make sure they are pulling the right companies for each topic area

- [ ] Change the site to ACTIVE

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Here are the updated Portfolio and Contacts pages showing the new PDs and their headshots, as well as the new topics categories. 
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/awardUpdates/portfolio/
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/awardUpdates/contact/

If it looks okay, I'll start getting it pushed to the live server. 

Just wanted to give a note to @CecileGonzalez - this update will roll back the fix to the Awards phase I and phase II page that I worked on with you. At the time, I didn't realize that the topic names weren't permanent, so filtering the awards by topic doesn't really work any better than filtering them by PD. Rolling back will allow the new topics to display properly, but means that CT will disappear from the page again. I'm going to keep working to get this straightened out. Thanks for your patience on this!

**Comment by CecileGonzalez** [comment]
Thanks for the update and heads up about the current award lists, Sarah!


  *   The portfolio page looks good to me.
  *   On the Contacts page (https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/awardUpdates/contact/), Anna appears twice, and Ben Schrag doesn’t appear at all.
  *   On the Bios page (https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/awardUpdates/contact/bios/), the same thing happens, and the bios are not in alphabetical order (maybe they are in a different order?).

Can you please take a look at these things?

Cecile

Cecile J. Gonzalez
NSF Directorate for Engineering
(703) 292-8538

**Comment by seakhtar** [comment]
Thanks for catching that @CecileGonzalez ! I've made an update that should fix the problem- Ben has been added back in and the extra Anna has been removed. 

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/awardUpdates/contact/
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/awardUpdates/contact/bios/

For the contacts page, I believe they are ordered by topic- so it matches what is displayed on the Portfolio page.

**Comment by kmonterr** [comment]
Thanks, @seakhtar ! It looks good! I think it's odd that the overall bios page isn't alphabetized. I don't want it to hold us up, so let's publish if it's not an easy fix.

Also, I've been trying to update Rajesh's bio to say something about his new topic, but it's not working. I updated the yml file. Maybe it was happening at the same time as other updates? It's **Update program-directors.yml #1049** It built in Federalist and everything! Here's what I wanted to change it to...

 the National Science Foundation covering Educational Technologies and Applications. 
+    Until early 2018, his focus area was Advanced Manufacturing and Nanotechnology.

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I think all program director bios are updated through the tech-topics data file (took me a while to learn that!). Just wanted to make sure I was looking in the right place- I couldn't find the "... Educational Technologies and Applications" line? Is there a different bio page?

![capture](https://user-images.githubusercontent.com/28659251/36996210-31657312-2084-11e8-84da-5a141ae771ca.JPG)

**Comment by kmonterr** [comment]
Oh my! That's probably why. I was updating the "program-directors.yml" file.  I just committed the changes to the Tech Topics data file in DEV. Feel free to merge!

**Comment by seakhtar** [comment]
Okay, I just merged the updates to the master branch- let me know if anything looks off.

I did notice that it seems like the Rajesh bio update seemed to disappear? I'm not quite sure why, I could see that it had been merged with dev. I think if you or I add it back in one more time, it should stick. It must have gotten lost somehow with all of the tech-topic updates in my branch.

**Comment by kmonterr** [comment]
Oh no! @seakhtar things somehow got royally messy. Linda disappeared from the Contact page and somehow has Rajesh's photo associated with her on the Topics page...Eek!

**Comment by seakhtar** [comment]
@kmonterr - I'm going to reverse the merge for now until I figure out what's going on! I'll keep you updated.

**Comment by kmonterr** [comment]
ok! Thanks!

**Comment by seakhtar** [comment]
Okay, think I figured it out. There was some extra code that I didn't see under Linda's bio that was throwing things off. [Here ](https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/staging/contact/)is the staging link, if you can take a look real quick. I'd like to get another pair of eyes on it before I push to prod- want to make sure there isn't anything else I missed!

**Comment by seakhtar** [comment]
Okay, the bios have been updated and everything is ready for review again in [staging](https://github.com/18F/nsf-sbir/edit/staging/_data/tech-topics.yml)!

**Comment by kmonterr** [comment]
yes!! Approved! Thank you for your help with this one! Looks good :)

**Comment by seakhtar** [comment]
Okay, took a couple of tries (I think the system is acting up a bit, maybe with all the updates going on), but I think everything is showing up correctly on production now. As usual, let me know if you see anything else that needs updating!

**Comment by kmonterr** [comment]
I wonder what was up with it yesterday? It wasn't happy with all of the updates we were pushing! 👎

**Comment by kmonterr** [comment]
HI @seakhtar ! I just found out that the solicitations will be posted in the next 24 hours. stay tuned with the links to push to the site! We'll also need to turn it to "active" at that point!

**Comment by seakhtar** [comment]
Sure @kmonterr , I'll keep an eye out!

**Comment by kmonterr** [comment]
Hi Sarah! The solicitations have posted! Can you please update the site and switch it to the ACTIVE stage this morning? Thank you!!
SBIR - https://www.nsf.gov/pubs/2018/nsf18550/nsf18550.htm
STTR - https://www.nsf.gov/pubs/2018/nsf18551/nsf18551.htm
