### ISSUE TITLE
Add a SAM Step to the Apply Timeline - Inactive & Active 

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1042]
- [x] Please add separate SAM step to our timeline for “any time before deadline” right after the "Get Pre-Submission Feedback.

Register with SAM.gov (required)

Before you begin your proposal, you MUST register to do business with the U.S. government through System for Award Management (SAM) https://www.sam.gov/portal/SAM/##11#1#1
Processing time: Up to three weeks
Any company that does business with the government needs a SAM account. When you register, you’ll have to share bank account information. Registration expires after one year.

- [X] Then can you please reorder the Register step to make SAM first…so it’s there twice.
- [x] Add the same new step and change the order to the ACTIVE timelines

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I've added the SAM step into the timeline, but I was a bit unsure about the checkbox that says to 
"reorder the Register step to make SAM first…so it’s there twice." Did you mean the register step would show up twice, or the SAM one? If you can let me know which numbers you'd like each step to be, I'll make sure to get them to match up correctly:

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/SAM-step/apply/

**Comment by kmonterr** [comment]
Hi Sarah!

This is almost perfect! Can you just adjust the language in Step 6, registrations, to move the SAM information first? Then make these slight edits to the text in Step 4 for SAM?

Processing time: Up to three weeks 
You must register to do business with the U.S. government through System for Award Management (SAM). When you register, you’ll have to share bank account information. This registration process is free and takes only 10-15 minutes to initiate, but can take up to three weeks to complete. You MUST have an active SAM.gov registration to create a FastLane account and submit a proposal to NSF. Registration expires after one year.

**Comment by kmonterr** [comment]
I just made the changes! I'll commit them ...

**Comment by kmonterr** [comment]
Do you mind making sure that the same information is in the ACTIVE timeline??

**Comment by seakhtar** [comment]
Hey @kmonterr -

I was just updating, so hopefully I didn't rewrite anything! Let me just double check that it will look the same ACTIVE

**Comment by seakhtar** [comment]
I think we should be okay- there is special code included in the steps that have different ACTIVE/INACTIVE states that Step 4 and 6 don't have. So I think they should look the same no matter what state the site is in. 
If everything looks good, let me know and I'll create the pull request and get everything to the live server-
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/SAM-step/apply/
