### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1069]
On this page - https://seedfund.nsf.gov/apply/

the link the Digital Health and Medical Devices (buried in “See What We Fund”) is broken.  Can you take a look?

**Comment by seakhtar** [comment]
Hmm, that's odd. It was working on my original branch when I added the new topics in; not sure how it got lost when we merged to production. I've noticed that's happened with other pull requests too- might need to keep an eye on that.

I'll work on getting the pages back- the I, S, PH topic is missing as well!

**Comment by kmonterr** [comment]
Super weird! It is also happening with IOT on the apply page. Can you fix it please?
If you go to https://seedfund.nsf.gov/portfolio/#internet-of-things-i-semiconductors-s-and-photonic-devices-and-materials-ph
And click on the topic link “Internet of Things (I), Semiconductors (S), and Photonic Devices and Materials (PH):” you get an error.

**Comment by seakhtar** [comment]
Looks like this is all set now-
