### ISSUE TITLE
Update the FastLane Guide

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1078]
Hi Sarah,
We went through our FastLane Guide online and the PDF. It looks like we'll need a few changes. See the comments in the attached PDF for all of the changes. Can you please update online version and create a 508 compliant PDF with all of the changes? I'm still waiting for one updated screenshot, but i'll add it to this issue when I get it! 

[Phase_I_Proposal_Preparation_Booklet (AM markups 03 13 2018).pdf](https://github.com/18F/nsf-sbir/files/1816978/Phase_I_Proposal_Preparation_Booklet.AM.markups.03.13.2018.pdf)

**Comment by kmonterr** [comment]
Hi @seakhtar - https://seedfund.nsf.gov/fastlane/form-prep/ 
can you please replace the screen shot and language on "“Funding Mechanism:" to "Type of Proposal"
Here are the two new related screenshots for the guide - 
![type of proposal 2](https://user-images.githubusercontent.com/26437393/37620717-6dd4570e-2b93-11e8-8d32-22a56972fba2.jpg)

**Comment by kmonterr** [comment]
@seakhtar - how's this update coming? Let me know if you need help or clarification! This is the last screenshot that was missing from this whole list of updates.

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Thanks for the screenshot-  I hope to have it posted once I get that implemented and the compliance finished up. For some reason a lot of the links were throwing red flags so I've been trying to get that straightened out! I'll give you a head's up once it's all set.

**Comment by kmonterr** [comment]
Thanks, @seakhtar !

**Comment by kmonterr** [comment]
Hi Sarah!

Thanks so much!

Page 1 - yes! We can make the changes. can you change the last step to 
**NSF Research.gov - register company and Principal Investigator (PI)**

The exact steps are on pages 11 and 12 in this PDF. Can you just copy their text and screenshots here and delete the FastLane Registration step?

We might have to get rid of the PI part too on this page - https://seedfund.nsf.gov/fastlane/ - and replace it with what they suggested in this PDF, that'd be perfect.

[Single ID Job Aids - 03-14-18.pdf](https://github.com/18F/nsf-sbir/files/1843304/Single.ID.Job.Aids.-.03-14-18.pdf)


**Page 15 - They did include this in the solicitation. (Here's what will go with G.6 Other)**

Firstly, the applicant may budget up to $10,000 as a direct charge on line G.6 to this Phase I award for the following specific purposes related to financials and accounting:

- Hiring a certified public accountant (CPA) to prepare audited, compiled, or reviewed financial statements
- Hiring a CPA to perform an initial financial viability assessment based on standard financial ratios so the awardee organization would have time to improve their financial position prior to submitting the Phase II proposal
- Hiring a CPA to review the adequacy of the awardee's project cost accounting system
- Purchasing a project cost accounting system

If the applicant elects to budget funds for one of the above purposes, the budget justification should include a brief description of the desired use of funds, and the use of funds must be approved by the cognizant Program Director, prior to award.

Second, the applicant may budget up to $20,000 to cover costs related to NSF's "Beat-The-Odds Boot Camp" which is offered to all Phase I awardees. 
This program is based on the NSF's Innovation Corps program, and more information can be found here. All Phase I awardees are strongly encouraged to participate in this activity. Costs that are allowable are limited to travel costs related to customer discovery (this could include costs associated with registration/attendance at events for the purpose of customer discovery) and salary/wages for team members who participated in the Boot Camp. All costs related to the Boot Camp must be in line with approved salary rates and other relevant Federal guidelines. International travel cannot be reimbursed, nor can any salary/wages for work done while outside of the United States. NSF recommends that, for the purposes of the proposal budget, applicants that plan to participate in this activity budget $10,000 and simply list this as "Boot Camp" costs in the budget justification.

**Page 31 - don't worry about the updated screenshot.**

Once you have all of this mocked up, please send me the dev link and I'll make sure it's all good!!

**Comment by kmonterr** [comment]
Awesome!

If you can pull the steps and screenshots out of the job aids and add them, that would be preferred. I want to make sure we have the same look as our guide. Does that work? if you need me to ask for the screenshots again, please let me know!

**Comment by kmonterr** [comment]
Hi @seakhtar - what do you think of linking to the resources for creating a new organization? https://www.research.gov/research-portal/appmanager/base/desktop?_nfpb=true&_pageLabel=research_node_display&_nodePath=/researchGov/Service/Desktop/InstitutionAndUserManagement.html

that way, if they update something we don't have to update it too....

**Comment by seakhtar** [comment]
Hi @kmonterr -

I actually just finished adding those steps in, so we can go either way! 
Here is how it currently looks, but if you prefer, I can take that stuff back out and just stick in the link:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/fastlaneUpdate/assets/files/applicants/Phase_I_Proposal_Preparation_Booklet.pdf

**Comment by kmonterr** [comment]
Hi @seakhtar It looks good! How does it look on the site? Do you mind sending the dev/branch preview link?

Thank you!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

As far as I know the fastland guide only shows up on the site as a link that you can click that opens the PDF in browser- I think the link is on this page: https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/fastlaneUpdate/resources/applicants/

Unless I've forgotten another location?

**Comment by kmonterr** [comment]
hi @seakhtar - Yes! There's the whole dynamic version of the same content - https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/fastlaneUpdate/fastlane/

**Comment by seakhtar** [comment]
Hey @kmonterr -

Gah- sorry, completely missed that! I'll get it updated asap. Luckily, it should go quicker than the pdf. 
I'll let you know once it's all set for review!

**Comment by seakhtar** [comment]
hi @kmonterr -

Okay, the pages have been updated. I think I got all the edits but if anything looks off to you just let me know:

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/fastlaneUpdate/fastlane/

**Comment by kmonterr** [comment]
Hi @seakhtar ! It's almost there! Do you mind replicating the language that you updated in the PDF on the site? Let me know when you're done and I'll take another look! THANK YOU!

**Comment by seakhtar** [comment]
Hi @kmonterr -

I thought I managed to get all those edits included- is there a specific step you can point me to that I might have missed?

Thanks for you patience with this!

**Comment by kmonterr** [comment]
I'll go through it now! I noticed some changes were missing at the beginning. Do you mind starting on the topics? thank you, @seakhtar again!

**Comment by kmonterr** [comment]
I think I caught everything! I'll push it live! 
Do you mind updating the PDF with my changes? They were edits to the beginning...
Thanks again, @seakhtar !!

**Comment by seakhtar** [comment]
Hi @kmonterr -

Sure- was it just that first "Required Registrations" step that changed, or were there edits anywhere else?Once I've got everything I'll re-upload the PDF and get started on the topics updates!

**Comment by kmonterr** [comment]
That's it! Thanks, Sarah! I pushed the changes to Dev, but haven't moved them to staging or master yet. do you mind doing that once you update the PDF?

thanks again!

**Comment by seakhtar** [comment]
Yes, that sounds good. I'll let you know when it's complete!

**Comment by seakhtar** [comment]
Hi @kmonterr -

I think this is all complete now. It seems to be appearing okay on the live site!

**Comment by kmonterr** [comment]
Yes! Thank you! How's the tech topics change going? I'm starting to get a lot of questions about it...
