### ISSUE TITLE
Removing a PDF and finding a link

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1089]
We should remove this PDF - https://seedfund.nsf.gov/assets/files/awardees/NSF-SBIR-STTR-PhaseIRespOpp.pdf

I'm not sure where it is linked from. is that easily found?

**Comment by seakhtar** [comment]
A search of the repository (using the search bar at the top of the page when you are in Git) with the link itself seems to turn up instances of where it appears in pages. It looks like this link was used here: https://seedfund.nsf.gov/resources/awardees/phase-1/

I'll remove the PDF and the link both!

**Comment by seakhtar** [comment]
This has been merged to master and should be fixed there as soon as the build completes!

**Comment by kmonterr** [comment]
Thank you!!
