### ISSUE TITLE
Update funding levels for NSF and SBIR

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1093]
SBIR should say $200 M

The National Science Foundation (NSF) is an independent federal agency that supports fundamental research and education across all fields of science and engineering. In fiscal year (FY) 2018, its budget is **$7.8 billion.** NSF funds reach all 50 states through grants to nearly 2,000 colleges, universities and other institutions. Each year, NSF receives more than 50,000 competitive proposals for funding and makes about 12,000 new funding awards.

**Comment by seakhtar** [comment]
Hi @kmonterr -

I found references to the funding number on these pages:
about.md
press.md
awardees.md (phase I)
awardees.md (phase II)
ambassador.md (phase I)
ambassador.md (phase II)

All the updates are currently on this branch:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/fundingUpdate/about/

Let me know if you'd like me to push these live!

**Comment by kmonterr** [comment]
Thank you, @seakhtar !! Do you mind removing the "nearly" in front of each reference? Sorry if I wasn't clear! Then we're good to push it live! Thank you!

**Comment by seakhtar** [comment]
No problem- the changes are now live!
