### ISSUE TITLE
QA the FastLane Guide

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1106]
Hi Sarah - 

I noticed that the Research.gov link is broken on the site and in the FastLane Guide PDF. I'm fixing it on the site, but can you please fix it in the PDF and replace the PDF?
https://seedfund.nsf.gov/assets/files/applicants/Phase_I_Proposal_Preparation_Booklet.pdf

![broken research gov link](https://user-images.githubusercontent.com/26437393/38428113-fce55468-3988-11e8-9f96-d9838f3fd8f9.JPG)
Here's the correct link - https://www.research.gov/research-portal/appmanager/base/desktop?_nfpb=true&_pageLabel=research_home_page

Can you please check the rest of the links on the site and in the PDF too? I hope there aren't more broken links!

Kelly

**Comment by seakhtar** [comment]
That's weird- I thought I specifically checked it! Though I just sent it to www.research.gov, since that was what was in Amanda's comment. 

I'll definitely go through the guide again and double-check, and upload any other changes!

**Comment by seakhtar** [comment]
Hi @kmonterr -

Sorry meant to ask if you'd made your change in dev or in a new branch? Just don't want to overwrite your edits. Thanks!

**Comment by seakhtar** [comment]
Actually looks like you've got some stuff sitting in staging so I'll hold of on pushing to prod for now.

**Comment by kmonterr** [comment]
Feel free to push it live! Thanks, Sarah!!

I really appreciate you checking the links!

**Comment by seakhtar** [comment]
Sure- it's been pushed!
