### ISSUE TITLE
Check to see if our site needs to be updated per DAP4.0

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1111]
Today, we're announcing the release of DAP v4.0, which replaces the code version previously in place for over a year, v3.1. You can view the new code file and documentation in our Github repo.

How does this affect me?

There are two ways this can affect you. The first is that if your site calls our file locally, you need to update the file in your servers, and the second is that there are a few new features to this code version you can choose to take advantage of in reporting.

1. Host location

We successfully pushed DAP v4.0 to our central host location at https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js yesterday. That means that if your site calls the DAP file from that location in your HTML, no further action is needed. 

If you host the file locally, you need to swap the current file with the new version in your servers OR switch to calling the file from our central host location above in order to take advantage of the most recent version. We ask that you complete this action by June 30. We'll be working with agency POCs to identify outdated code and ensure updates in the coming months.

For more information:
•	Github README detailing implementation
•	Implementation Guide
•	Code Capabilities Summary
If you don't know how your site calls the DAP code, we ask that you contact your developers to find out, or email us at dap@support.digitalgov.gov so that we can help.

2. Summary of changes

The DAP code will now offer:
•	
•	URL Protocol Tracking: The protocol of the current page is now stored as a custom dimension called URL Protocol. Example value: https
•	Event Interaction Type Tracking: For events such as outbound links, email links, and document download links, in addition to tracking these interactions automatically, the DAP code now also passes a value into an Interaction Type custom dimension indicating either “Mouse Click” or “Enter Key Keystroke”. Previously, using the Enter key to open a link was not tracked at all.
•	Source Mapping: Source mapping capabilities have been added to the DAP code, a feature which developers can use to better inspect DAP in various developer tools. Note: this feature is only available when the filename matches "Universal-Federated-Analytics-Min.js".
•	Script Source URL (DAP Code Location) Tracking: The location of the DAP code itself is now stored as a custom dimension called Script Source URL. Example value: https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js
For a full description of changes, see the changelog.

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I did a search for this link, and it looks like it is already referenced in our base.html code. I think that means we are already up to date- I don't see why we'd need to reference it twice.

**Comment by kmonterr** [comment]
awesome! Thank you, @seakhtar !
