### ISSUE TITLE
Remove Debasis from Our Site - 4/27

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1120]
Hi @seakhtar - 

Can you please help me remove Debasis Majumdar from our site next Friday (April 27)? He got a new job and is leaving our office!
His portfolio (Materials and Nano) will transfer to Ben Schrag.
All of his companies need should be transferred to Ben Schrag.
We'll also need to remove his bio and photo.

Let me know if you have questions!
Kelly

**Comment by seakhtar** [comment]
Sure! I'll start working on this in a new branch and let you know when it's ready to review.

**Comment by seakhtar** [comment]
Okay, he's been removed in this branch: 
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/pd-update/portfolio/

It looks like he's been removed from the Portfolio and the list of Bios. I could keep the branch separate until the 27th?

**Comment by kmonterr** [comment]
@seakhtar Looks good! Yes, let's wait until next Friday to push the changes live.

Do the Phase I and Phase II lists look good? I noticed there are quite a few companies in the "Other Topics" category. @benschrag does it look right to you?

**Comment by seakhtar** [comment]
Hey @kmonterr ,

No, unfortunately the Phase I and Phase II lists are going to continue to be incorrect until we figure out our changing PD problem. Since those pages use the PDs to display the awards, when the PD changes, the awards can disappear or end up in the wrong categories. Unfortunately, there doesn't seem to be an easy fix for this, but I'm hoping Dakota's developer can take a look at the code and propose an alternative.

**Comment by seakhtar** [comment]
Hi @kmonterr -

This update has been pushed to the live server. Sorry if it was late- I might have gotten confused about which updates we were holding back on! 

As for the Phase I/Phase II issue, I've explained the problem to our developer and we'll be discussing it tonight to try to find a solution. Depending on how much those pages might need to be overhauled we'd probably want to test things thoroughly before pushing anything live, but we'll try to get a solution up and working as quickly as possible. I'll keep you informed as we go!

**Comment by kmonterr** [comment]
Thanks, @seakhtar ! Keep me posted on the Phase I/Phase II problem.
