### ISSUE TITLE
Showcase Page Updates

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1152]
Hi Sarah -

We'd love to rework the Showcase page to swap out the older videos with the new ones. Here's what I'd like to do:

- [ ] Remove the old videos
- [ ] Add the new videos (linked below)
- [ ] Use the Title & description from YouTube to populate the text field for the page. E.g. Elidah, a small business funded by the National Science Foundation, created a medical device to help women with stress urinary incontinence - the inability to control the urge to urinate - a condition which impacts about one in three women.
- [ ]  Remove the company name from the title, but make sure to put a link to the company's site. It will be in the YouTube description.
- [ ] Keep the two testimonials from Robert and Jose - put them between a few videos.
- [ ] Add our twitter feed, if possible?

Let me know if you have any questions!
Kelly 

- Malaria test – Fyodor Biotechnologies https://www.youtube.com/watch?v=XzgzRg9PwRc&index=71&t=0s&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb
•	Elidah - https://www.youtube.com/watch?v=ksxUK6OWpOA&index=5&t=0s&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb
•	Branch Technology - https://www.youtube.com/watch?v=OsLDAevskrA&index=4&t=1s&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb
•	Arable - https://www.youtube.com/watch?v=BC7LQRir7L8&t=73s
•	TAO Connect - https://www.youtube.com/watch?v=Z4mwbSNvlp8&index=1&t=4s&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb
•	Bay Labs - https://www.youtube.com/watch?v=QdCIZE-eKB4&index=3&t=3s&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb
•	Spheryx - https://www.youtube.com/watch?v=OyR_i_nPkhA&index=72&t=0s&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb
•	Keystone Tower Systems - https://www.youtube.com/watch?v=Q10zFGxpNoo&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=62
•	Omnity - https://www.youtube.com/watch?v=r5EULFTdI0I&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=65

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I will add this to the queue!

**Comment by seakhtar** [comment]
Hi @kmonterr -

Quick question- when copying over the descriptions, did you want me to just use the first paragraph, or the whole thing?

**Comment by kmonterr** [comment]
Just the first paragraph!

**Comment by seakhtar** [comment]
Okay, how does this look?

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/showcaseUpdates/showcase/

**Comment by kmonterr** [comment]
Hi Sarah!
Looks good! a few changes: 

- [ ] Do you mind removing "a small business funded by the National Science Foundation" in the text for each video? I think it's implied!
- [ ] Also, can you stagger the videos - i.e. make one on the left and the on the right? It might be more visually appealing. 
- [ ] Can you make Jose Mejia and Rob Nordsell's photos smaller? When I look on mobile they are huge!
- [ ] can you put Omnity and Keystone tower at the end? and move the last three up higher (TAO, Bay Labs and Sphyerx).

**Comment by seakhtar** [comment]
Hi @kmonterr 
Here is the updated page- let me know if there are any further edits you'd like me to make!

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/showcaseUpdates/showcase/

**Comment by kmonterr** [comment]
Looks good! Feel free to push it live!
