### ISSUE TITLE
Reorganizing the Portfolio Page & tiny fix

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1153]
I'd like to swap the locations of the "we fund varied tech sectors" and the list of technology topic areas with the Featured Alumni and Exits. 
Please keep the "View our current awardees" in the same place. 
I tried unsuccessfully to do it on a new branch (topicsup). Feel free to delete that branch!

Move this up:
![image](https://user-images.githubusercontent.com/26437393/40188492-0e7168ca-59c8-11e8-9bd2-2e41fbea126c.png)

Move this down:
![image](https://user-images.githubusercontent.com/26437393/40188470-034464a2-59c8-11e8-8e52-8c320e7fbc25.png)

There's also a weird little graphic showing up on the page (in Chrome). I highlighted it here:
![image](https://user-images.githubusercontent.com/26437393/40188588-44544b1a-59c8-11e8-9a2b-780da64b3bde.png)

**Comment by seakhtar** [comment]
Hi @kmonterr - 

I'll look into it and let you know if I have any questions.

**Comment by seakhtar** [comment]
Hi @kmonterr -

Is this the correct order?

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/topicLoc/portfolio/

Let me know if I need to rearrange anything!

**Comment by kmonterr** [comment]
Looks perfect @seakhtar !!

**Comment by seakhtar** [comment]
Great- I'll go ahead and push to the live site!
