### ISSUE TITLE
Swap the headshot on the site

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1169]
We just took new professional photos! We'd love to swap the current ones out with the new ones!

![anna](https://user-images.githubusercontent.com/26437393/40677364-77584674-634b-11e8-94ef-571f137d50f0.jpg)
![ben](https://user-images.githubusercontent.com/26437393/40677367-778296c2-634b-11e8-862c-a5f2c4befc17.jpg)
![henry](https://user-images.githubusercontent.com/26437393/40677369-779f3c6e-634b-11e8-9ab8-ac7c9efd45a2.jpg)
![linda](https://user-images.githubusercontent.com/26437393/40677370-77b323aa-634b-11e8-88b4-558bfda40088.jpg)
![murali](https://user-images.githubusercontent.com/26437393/40677371-77c6e5de-634b-11e8-85fa-b2f2dd2960d1.jpg)
![nancy](https://user-images.githubusercontent.com/26437393/40677372-77d74a50-634b-11e8-9355-582c487a0be8.jpg)
![peter](https://user-images.githubusercontent.com/26437393/40677373-77ec7b96-634b-11e8-9bbb-b998011ed98c.jpg)
![rajesh](https://user-images.githubusercontent.com/26437393/40677374-78030aa0-634b-11e8-96e1-807ceff41a43.jpg)
![rick](https://user-images.githubusercontent.com/26437393/40677375-7819d348-634b-11e8-9075-32231af58086.jpg)
![ruth1](https://user-images.githubusercontent.com/26437393/40677376-7831e4f6-634b-11e8-90e9-ec326da52e73.jpg)

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Here is the branch with the swapped photos:

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/pdImages/contact/bios/

Let me know if that all looks okay!

**Comment by kmonterr** [comment]
Hi @seakhtar - 
Three small things:

Can you zoom out of Nancy's photo so it looks a little more like the rest? She wasn't here the day we took photos.

Then, I forgot to send you Barry's and Gracie's new photos! Can you add them to the page too?
![barry](https://user-images.githubusercontent.com/26437393/40783111-73845f46-64af-11e8-92ba-93128dc7667c.jpg)
! 
![gracie](https://user-images.githubusercontent.com/26437393/40783090-639dbf96-64af-11e8-887d-b9f037d19d86.jpg)

**Comment by seakhtar** [comment]
Hi @kmonterr -

Sorry for the delay on this- the new headshots are in place and ready for review:

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/pdImages/contact/bios/

**Comment by kmonterr** [comment]
Looks great, @seakhtar ! Feel free to push it live

**Comment by seakhtar** [comment]
Okay, it's been published!
