### ISSUE TITLE
Photonic misspelled

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1200]
the webpage for my portfolio is mis-spelled in the URL (‘photoic’)
https://seedfund.nsf.gov/topics/internet-of-things-semiconductors-and-**photoic**-devices/

is it an easy fix??? the program director wants it fixed before an event next week...

https://seedfund.nsf.gov/topics/internet-of-things-semiconductors-and-photoic-devices/

**Comment by seakhtar** [comment]
Hi @kmonterr 

This has been fixed and pushed to dev, but I saw there were some updates that you had made that hadn't been pushed to staging yet. Did you want me to go ahead and push everything in dev to prod, or were you still working in dev?

**Comment by kmonterr** [comment]
Yes, please!! THanks, Sarah!

**Comment by seakhtar** [comment]
Okay, everything has been pushed to production and should be live as soon as the build finishes!
