### ISSUE TITLE
Ruby version manager upgrade required

### ISSUE THREAD

**Issue by seakhtar** [18F/nsf-sbir#1213]
@line47, @femmebot, @kmonterr  -

Builds aren't completing due to error- can you resolve? We need to commit changes first thing Wednesday, 7/11. These appear to be server related and not something I can fix on the front end.

>> STDOUT:
[BUILD] 2018-07-10 23:57:26 INFO: Using ruby version in .ruby-version
Warning, new version of rvm available '1.29.4', you are using older version '1.29.3'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
[BUILD] 2018-07-10 23:57:26 INFO: Ruby version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by kmonterr** [comment]
@seakhtar - I just sent an email to Will Slack at Federalist. He would be the point person on this. @wslack

**Comment by seakhtar** [comment]
Thanks @kmonterr - I'll keep watch so we can get the switch-over made as soon as possible.
