### ISSUE TITLE
Typos and swamp contact info - 

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1228]
We just realized that this webpage needs an update at the bottom:  https://seedfund.nsf.gov/resources/review/travel/

Please remove Amanda and Doretha and replace with Stacey Stoby (sstoby@associates.nsf.gov, 703-292-8825) – please ensure her email is a hyperlink?

Unrelated, there are some minor typos on this page that have long needed cleaning up, at the top – these random / marks:

•	$280 for each travel day (based on geographic point of origin and confirmed travel dates)/*
/* To
And finally, under Hotel Information, can you make the email address a hyperlink?  NSF contractor Accommodations Unlimited is available to assist you with securing a hotel room. Please contact Wendi Picker at 800-201-4005 or nsf@wedothelegwork.com. 

Thank you!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

These changes have been made- let me know if you need me to make any further updates!

-Sarah
