### ISSUE TITLE
Clarifying Supplement Guidance - RAHSS/REU/RET/VRS/CAP Budget Step

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1233]
@seakhtar - could help us update the website to make this more explicit (add a sentence in italics):  https://seedfund.nsf.gov/resources/awardees/phase-2/instructions/

3. RAHSS/REU/RET/VRS/CAP Budget Info: All student/teacher costs are entered under line F as participant support costs.  **Please enter the number of students/teachers in the “Number of Participants” field in section F of the budget.**

**Comment by seakhtar** [comment]
Hi @kmonterr 

This one seemed pretty straightforward so I pushed it ahead- let me know if you'd like me to make any adjustments!

https://seedfund.nsf.gov/resources/awardees/phase-2/instructions/
