### ISSUE TITLE
Adding another quote and headshot to the Showcase page.

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1239]
I have one more photo for this one coming too...

Maybe put it after Elidah? 

“The grants we received from NSF were instrumental in bootstrapping ThousandEyes and allowing us to focus on building the first version of our product and acquiring customers. By the time we raised our series A from Sequoia capital, we had a handful of well-known brands as customers with annual bookings of more than $250k, i.e. real revenue. Thanks to NSF, we were on our way to commercializing our technology.” - Mohit Lad, CEO & Co-Founder of ThousandEyes, a network intelligence platform for businesses, was founded by Lad and Ricardo Oliviera in 2010. In 2018, they have 220 employees and have raised nearly $61 million.

ThousandEyes delivers Network Intelligence—performance visibility and actionable insights on digital experience for every user and application over any network. It arms network engineers, operations teams, support/service desk staff, developers, and even business users with an accurate, up-to-the-moment understanding of the link between application delivery and underlying network dependencies and behaviors– both inside and outside the organization. 

![thousandeyes-mohit-lad-ceo-co-founder](https://user-images.githubusercontent.com/26437393/44548207-6feb0a00-a6eb-11e8-8f62-5aa6215073a0.jpg)

**Comment by kmonterr** [comment]
Caption: ThousandEyes' patented Path Visualization provides detailed hop-by-hop visibility and performance metrics from any network, even if it's outside your enterprise boundaries. A global inference engine correlates multiple streams of data and visually pinpoints the location of outages (shown as red circles), and provides additional contextual information about the specific location.
![thousandeyes-path-visualization](https://user-images.githubusercontent.com/26437393/44548824-31564f00-a6ed-11e8-8199-de18ec67fbda.jpg)

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just wanted to ask if you wanted a title for this section? And any caption for the headshot?

**Comment by kmonterr** [comment]
Hi @seakhtar - Sorry!

Monitoring internal and external network performance - ThousandEyes 

Caption for headshot:
Mohit Lad, CEO & Co-Founder of ThousandEyes

**Comment by seakhtar** [comment]
Hi @kmonterr 

Just wanted to send you a quick mock-up of this section- were you looking for something like this? Let me know if you had anything else in mind:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/showcaseUpda/showcase/

**Comment by kmonterr** [comment]
Hi @seakhtar ! It looks good! Can you make the tech photo a little smaller? It seems too big!

Thank you!!

**Comment by seakhtar** [comment]
Hi @kmonterr -

This might be too small now, but let me know :)
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/showcaseUpda/showcase/

**Comment by kmonterr** [comment]
Thanks, @seakhtar - can you make it more like Shasqi? Just a little smaller or left/right justified? Thanks!

**Comment by kmonterr** [comment]
Hi @seakhtar - Do you mind pushing this live once you make this last change? for some reason, I thought it was up already!

**Comment by seakhtar** [comment]
Hi @kmonterr -

So sorry- don't know how I missed this one! I've updated/pushed it to prod. Not sure if I quite got what you were looking for, so if you'd like me to make any adjustments, let me know!

**Comment by kmonterr** [comment]
Do you mind changing $61M to $110M? in this sentence - 
they have 220 employees and have raised nearly $61 million.

**Comment by seakhtar** [comment]
Hi @kmonterr -
The number has been adjusted
