### ISSUE TITLE
Portfolio page: Updating the Internet of Things (I), Semiconductors (S), and Photonic (PH) Devices and Materials

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1240]
Can you please swap out "Sensorhound" and replace it with "SweetSense Inc"? 1738321 

Thank you!
Kelly

**Comment by seakhtar** [comment]
Okay, this has been switched out on this branch:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/MIUpdate/portfolio/

**Comment by kmonterr** [comment]
Oddly, it's not showing up...even when I refresh?

**Comment by seakhtar** [comment]
@kmonterr -

This should be switched out now!
