### ISSUE TITLE
Portfolio Page: Advanced Manufacturing and Nanotechnology (MN)

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1241]
Please keep Branch Technology, but replace the other 8 companies in this portfolio area with 

- Elementum 3D, Inc. (https://www.elementum3d.com/
- Vaxess, Inc. (http://vaxess.com/)
- 3DEO, Inc. (http://www.3deo.co/)
- XPEED Turbine Technologies, Inc. ,  https://www.xpeedturbinetechnology.com/
- Astrileux, Inc. , http://astrileux.com/  
- Hummingbird Nano, LLC , http://www.hummingbirdnano.com/ 
- Big Blue Technologies, Inc. , http://www.bigbluetec.com/ 
- Briteseed, LLC , http://briteseed.com/ 

please link them to their award search result, not their websites. We will want to link to company sites and include logos/ one sentence about each company, but that's a whole new project! Coming soon...

**Comment by seakhtar** [comment]
These have been switched out, currently on this branch:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/MIUpdate/portfolio/
I'll keep my eye of for that new logo project :)

**Comment by kmonterr** [comment]
Hi @seakhtar - oddly, only Branch is showing up. The other 8 are missing...

**Comment by seakhtar** [comment]
Hi @kmonterr -

Yes- something weird happened and now the page isn't working correctly. I'm still troubleshooting what's going on- I have no clue what's causing the problem. I'll let you know once it's working again.

**Comment by seakhtar** [comment]
Yes- I'm not sure if the system is just having some sort of hiccup at the moment. This morning it was working okay, but now- even with a brand new branch- it displays any new companies as a blank space. The change is very simple so I don't think I'm entering anything wrong. I'll give it some time and try again-- if it still doesn't work by Monday, we might have to contact Federalist's support email. 
I'll keep you posted-

**Comment by kmonterr** [comment]
Hi @seakhtar !

Let me know how it's working. I don't think it's a hosting issue (Federalist). It would probably be an API issue. You might want to talk to the Dakota developer? Let me know how I can help.
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -
Yeah- I might have to talk to our Devs- nothing I'm trying seems to be working!

I think you might be right and that it's tied to the API- though when I tried rolling back the API update it didn't make a difference. I've checked and those companies do appear in the API data file, so I'm not sure why the system isn't creating the link properly. 

I'll discuss it with the rest of the team and get back to you!

**Comment by seakhtar** [comment]
Hi @kmonterr 
I think we've finally gotten this straightened out! All of the correct companies should be showing up now. The only one I couldn't get to work was Elementum 3D, Inc. When I checked the awards data file, that company wasn't listed anywhere. I did find "elementum3d" in an email address listed under the award "Sinter Print Inc". Is that an alternate name, maybe? 

Here is the branch for you to check over: https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/portfolioFix/portfolio/

**Comment by kmonterr** [comment]
Hi @seakhtar !

Looks great! Thank you! What was the hiccup, if you don't mind me asking??

Elementum 3D was formerly Sinter Print!

This was just for the Advanced Manufacturing companies, right? I didn't see changes to the featured companies and exits or the other portfolios.

Thank you!
Kelly

**Comment by seakhtar** [comment]
So the issue was that you have to run another API update after you add any new companies to the portfolio page- otherwise the system won't link them to their awards pages properly and they'll show as missing. 
It also turns out that the spelling needs to identically match the spelling in the API or they system won't recognize the award... took me a few tries to figure that one out. 

Did you want me to leave Elementum 3D off for now? Maybe they'll update it's name in the API later on? Or I can go ahead and just add Sinter Print instead.

This branch should be showing changes for all 3 topics - you might have to refresh the page a few times to see them all, as they rotate out:

MN:
Vaxess, Inc. 
3DEO, Inc. 
XPEED Turbine Technologies, Inc.
Astrileux, Inc. 
Hummingbird Nano, LLC 
Big Blue Technologies, Inc
Briteseed, LLC

CT: 
CycloPure
ESal
Azimuth1
Saratoga Energy Research Partners

SP:
SweetSense

**Comment by kmonterr** [comment]
Yes! The changes to these three topic areas look good. I was looking at #1237, which i don't think you've updated yet.
Just add Sinter. I don't think they update the name in the award search :(
Thank you!

**Comment by seakhtar** [comment]
@kmonterr -

Sinter has been added and the changes pushed to the production server
