### ISSUE TITLE
Portfolio Update: Chemical and Environmental Technologies

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1242]
**Please delete these companies from the list:**
- Cambrian Innovation Inc
•	Flodesign Sonics Inc.
•	Ubiquitous Energy, Inc
•	Cycladex

**Keep these:** 
•	Vaporsens Inc.
•	Precision Polyolefins, LLC
•	Modular Genetics, Inc.
•	Renuvix
•	ZYMtronix Catalytic Systems Inc.

**Add these:**
- Cyclopure, 
- ESal, 
- Azimuth1
- Saratoga Energy.

**Comment by seakhtar** [comment]
Hi @kmonterr ,

These have been added/switched out. Just as a reminder- the page only shows only nine at a time so you might have to refresh a couple of times to see them all.
I'm putting all the portfolio updates in one branch so when I get your okay for all those issues I'll go ahead and publish:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/MIUpdate/portfolio/

**Comment by kmonterr** [comment]
Hi @seakhtar - same thing is happening here. Only a few are showing up...

**Comment by seakhtar** [comment]
@kmonterr -

This has been fixed and should now be showing up!
