### ISSUE TITLE
December Deadline - New SBIR and STTR Solicitations

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1248]
new SBIR and STTR solicitations will be cleared next week. 

Can you please update the links and push the site to “active” mode when they are available? 

The new deadline will be December 4, 2018. 

Besides the links to the new solicitations and the deadline date, everything else should remain the same. We are still working to finalize our topics and FAQs.

**Comment by kmonterr** [comment]
Thanks, Sarah!

On the apply page. The timeline is missing a space after the period. (bolded below). 

Applications due by 5:00 p.m. in your local time zone.
Note: Applications due by 5:00 p.m. in your local time **zone.Your** time zone is based on your company's address as you listed it in your application.

Otherwise, it looks good! Gracie/Cecile will send you the links to the solicitations!

Have a great weekend!

**Comment by seakhtar** [comment]
Sure- it's been adjusted!

**Comment by kmonterr** [comment]
Thanks, @seakhtar ! Looks like we're set as soon as NSF sends the links! 👍
