### ISSUE TITLE
New Topics PDF

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1265]
[SBIR Topic updates combined_final_10.2018.pdf](https://github.com/18F/nsf-sbir/files/2434948/SBIR.Topic.updates.combined_final_10.2018.pdf)

Hi @seakhtar - 

We finished the topics! Can you please update the PDF on the site? I believe it is in two or three places.

We'll also have to rethink how we organize the content of the portfolio pages and topics there. I'm including the word doc here to help with that. We'll have to change the subtopics on the portfolio page and make sure they are tagged to the right PD. I'm adding @benschrag to this too
[SBIR Topic updates combined_final_10.2018_PD assignments.docx](https://github.com/18F/nsf-sbir/files/2435112/SBIR.Topic.updates.combined_final_10.2018_PD.assignments.docx)
 since he knows the best which PD goes with which topic.

Thanks, Sarah! This is the priority this week! I'll respond about FastLane too!

Kelly

**Comment by kmonterr** [comment]
thanks, @seakhtar ! It looks good! please push it live!

**Comment by seakhtar** [comment]
Okay, @kmonterr , it's been posted!

**Comment by kmonterr** [comment]
How is it going updating the portfolio page with the new topics and subtopics, and the related subpages?

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I had a discussion with our developer about some of the roadblocks we might run into with the topics updates-- we'll try to come up with a solution to get it displaying correctly.

In the meantime I had a quick question-- I noticed some of the topics had the same 2-letter code. Are those topics grouped together in some way?

**Comment by kmonterr** [comment]
Hi @seakhtar -
Thank you! Sorry for the delay. Since the solicitation is already out, we couldn't change the two letter codes. They are tied to the solicitation. What you could do to make this easy is put each of these topics on a page for each program director. I specified who had what topic in the document. Then, do a link that would bring the user directly to that topic on the page from the portfolio page.  (Much like how the PD bios are organized, but one page per PD with each of their topics listed.) I'm not sure that I'm explaining it well. Let me know if you want to chat about it! I'm around until about noon today then in a training.

Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Thanks for the explanation. 18F developed a specific way to get the topics pages to display (ie, centered around the topic, with the PD just as a sidebar). We could create new pages for the site, but it would sort of mean shedding those templates and we would probably want to test everything thoroughly to make sure doing so didn't break anything.

I'd actually started inputting them if you want to take a look at how it would look currently (I was still working on troubleshooting the links though, so it's not quite finished yet)-- 
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/topicsUpdate/portfolio/

. Would you prefer the PD-centric way, or should I continue as is?

Thanks!

**Comment by seakhtar** [comment]
I was wondering about the featured companies as well! 
But that sounds good- I'll wait to hear back from you after our nice holiday weekend :)

**Comment by kmonterr** [comment]
You too!!  I'll keep you posted :)

**Comment by seakhtar** [comment]
Hi @kmonterr 

I will work on getting these implemented-- do you know if these are all active companies? 
I know we've been running into trouble with the "recent date" field, where it manually needs to be set back a few years to capture older companies, so just wanted to check!

**Comment by kmonterr** [comment]
Thanks, @seakhtar  - I believe that they are all current companies, but to be safe, I would set the date back a few years just in case! Thank you!

**Comment by seakhtar** [comment]
Hi @kmonterr 
Okay, I think I've got the companies placed into the system. I'm still trying to check to see if there are any that aren't showing up, and if there are, why- but I wanted you to be able to start taking a look. Let me know if there are any immediate changes you see. 

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/topicsUpdate/portfolio/

**Comment by kmonterr** [comment]
Hi @seakhtar -
There is a space missing behind Advanced Manufacturing and the parenthesis, and Advanced Materials and the parenthesis.

**Comment by seakhtar** [comment]
Got it- should show up changed in a minute.

Just as an FYI- I'm still troubleshooting Distributed Ledger- for some reason the page wouldn't come up properly so if it looks weird when you open it, that's just me

**Comment by kmonterr** [comment]
Hi @seakhtar -

It looks awesome! Here are a couple of additional changes. once you make them, please push it live!

Featured Alumni and Exits -

- Missing Novan - https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/topicsUpdate/portfolio/details/?company=novan-inc
- Missing Ekso Bionics, Inc. - https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/topicsUpdate/portfolio/details/?company=ekso-bionics-inc
- missing Jana (formerly Txteagle, Inc.) - https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/topicsUpdate/portfolio/details/?company=txteagle-inc

Advanced Manufacturing -
- Missing  a "Y" on technology in "Sustainable Manufacturing Technolog (M9) "

Chemical and Advanced Energy Technologies 
- Novel  Catalysts and Processes (CT3) should be: Power Generation and Advanced Infrastructure (CT3)

Distributed Ledger - 
- the subtopics are messed up. Should be:
DL1: Advanced Protocols:  Blockchain, DAGs, and Next Gen Protocols
DL2: Cryptography and Security, Identity and Anonymity Solutions, Trusted Devices  
DL3: Smart Contracts, Next-Generation Financial Technologies
DL4: Scalability Solutions, Enhanced Consensus Methods, Organizational Structures
DL5: Human to Technology Interface Innovations, Disruptive Business Model Innovations for Distributed Ledger Technologies
DL6: Distributed Ledger Convergence with Sensing, Big Data, AI, and IoT
DL7: Autonomous Systems and Economies
DL8: Other Technologies and Approaches Potentially Relevant to Distributed Ledger

Educational technology-
- Missing a space between - Learning Assessment**s(E**A8) 

Environmental Technologies
- Remove extra subtopic code at the beginning - Environmental Technologies (CT): **CT7.** 

IT-
Remove  Quantum Information Technologies (IT3) as a subtopic in IT. It is pulled out later.

**Comment by kmonterr** [comment]
Hi @seakhtar - I'm still double checking everything! It looks like the link is messed up to 
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/topicsUpdate/portfolio/details/?company=applied-lifesciences-systems-poultry-inc 
It's under Biological technologies

**Comment by kmonterr** [comment]
something is weird with Nancy's bio on this test branch too. It is pulling Linda's bio. I'm not sure if it will ruin her correct bio when we merge it, but just to flag this issue for you - https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/topicsUpdate/contact/bios/#Nancy%20Kamei

**Comment by seakhtar** [comment]
Hi @kmonterr -

Here are some updates:

1. Featured Alumni and Exits - Seems like the only way to see them all is to do a hard refresh (CTRL+Shift+R). Even then it can take a couple of times to get through the whole list, but I have seen all three companies show up at one point or another. I think it's because the number is capped at 9, and just doing a normal refresh doesn't change which ones appear. Whenever someone navigates to the page though it should show a new set.

2. Advanced Manufacturing & Chemical and Advanced Energy Technologies- these have been updated!

3. Distributed ledger- Running into a problem with the phrase "Advanced Protocols: Blockchain". Markdown registers colons as signals for new topics. I've been trying to find a way to override this with no luck so far. Is there any other character we could use, such as "Advanced Protocols - Blockchain"? If not, I'll keep working on this!

All the other changes should be showing up correctly now-

**Comment by seakhtar** [comment]
Forgot to add! 

Nancy's bio should be showing up correctly now- that one was my mistake, forgot to update it.

Having more trouble with the Biological technologies link. The company literally shows up in the NSF awards db as "APPLIED LIFESCIENCES & SYSTEMS POULTRY, INC.", so not sure why it's having trouble? Might be a question for Kanak, since it looks like the system is having trouble parsing the API to make the page.

**Comment by benschrag** [comment]
Hello – Re: #3 below, I am fine with substituting a dash for a colon if that helps!

Thanks for all the work!

Cheers,
Ben

**Comment by kmonterr** [comment]
Thank you, @seakhtar !!! Feel free to use a dash and push the whole thing live. We really, really appreciate it!!!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

No problem - just finished merging to master. Once the build finishes, it should be all set!

**Comment by kmonterr** [comment]
Hi @seakhtar -
We got good feedback about the new layout! People will be sending more companies to add to the featured company spots for several of the topic areas. Here's the first such update:

Educational Technology needs to be updated to include these companies -
Edify: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1660072
Killer Snails: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1660065
Cue Think; https://www.nsf.gov/awardsearch/showAward?AWD_ID=1660216&HistoricalAwards=false
AlChemie: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1659983
Couragion: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1660021&HistoricalAwards=false
Speak Agent: https://nsf.gov/awardsearch/showAward?AWD_ID=1632488&HistoricalAwards=false
Zyrobotics: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1555852
ThoughtStem: https://nsf.gov/awardsearch/showAward?AWD_ID=1632539&HistoricalAwards=false
Looking Glass Ventures: https://nsf.gov/awardsearch/showAward?AWD_ID=1758301&HistoricalAwards=false
