### ISSUE TITLE
Check the Phase I average.

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1269]
Hi - Do you mind checking the API here? The average amount of funding awarded to each of Phase I company is $257,915, which exceeds the maximum award for a Phase I company.  
https://seedfund.nsf.gov/awardees/phase-1/

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Did the maximum amount of funding change at some point? As far as I can tell, it's just averaging the listed "amount awarded" of all the awards retrieved from the API. It looks like some of the awards listed have quite high amounts and that might be throwing off the average (ie, [this one](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1620855&HistoricalAwards=false) ).

This is sort of related to the issue I brought up with the featured companies error-- we could set the "recent date" so that only companies with the new funding cap are shown. This would remove the older awards from both the PhaseI/II pages, but it might fix the error. As the "recent date" is also tied to which companies are featured on the portfolio page, it might also affect those as well.

Let me know if I need to explain that better--

**Comment by kmonterr** [comment]
Hi @seakhtar -
Hmm that could be it. The funding cap is the same ($225K). the current phase I companies should only be pulling the active awards. The one you noted expired already. Maybe that's the problem? I had thought that that API only went back a year, but I could be wrong. Is it written in the WIKI?

I'd recommend tying the API to award expiration date - if that's possible in the NSF database. I'd like only current companies (Phase I and Phase II) to be shown and averaged on these pages.

As for the featured companies, let me look at what you wrote on that issue! 
Kelly

**Comment by seakhtar** [comment]
Sure- do you know the specific cut-off date for active awards? Or is it just a year back from now?

**Comment by kmonterr** [comment]
There isn't a specific date. There is a tag in the NSF award search for active and expired. That's how i would work it!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

So it looks like the API itself didn't have a flag for "active/inactive" but I figured anything that had an expired date as of today could be considered inactive-- that did seem to [fix the companies](https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/averageAward/awardees/phase-1/) listed in the accordions (they all look capped at the right number now), but it didn't fix the average award number at the top. I'm not sure if it's a bug- the wiki doesn't really mention any other steps other than updating the recent date field. 

It looks like it's getting it's figures from [here](https://github.com/18F/nsf-sbir/blob/dev/_data/awards_summary.yml), but I'm not sure how that file is being populated or why that data is different from what's showing up in the accordions. So unfortunately this one is going to take a little more digging as well-- sorry about that! I'll try to figure out what's going on with our developer and get back to you asap.

**Comment by kmonterr** [comment]
Let me know what you have found! @seakhtar. Adding @benschrag here for awareness.

**Comment by seakhtar** [comment]
Hi @kmonterr ,
We've investigated this issue and I think we've figured out the problem. 
It looks like the system is pulling in three types of Phase I awards: SBIR, STTR, and something called CCI.
The SBIR and STTR awards are all at or below $225,000, but the CCI awards are all $1,800,000. This appears to be what is throwing off the average.
I'd never heard of the CCI awards (ex: CCI Phase I: NSF Center for Chemo-Mechanical Assembly) before and wanted to check with you that they should be added in. The system is set up to automatically pull them from the API, but if that needs to change, we can look into a fix!

Spreadsheets with 3 types of recent Phase I awards attached:
[SBIR Phase I Awards.xlsx](https://github.com/18F/nsf-sbir/files/2622427/SBIR.Phase.I.Awards.xlsx)
[STTR Phase I.xlsx](https://github.com/18F/nsf-sbir/files/2622428/STTR.Phase.I.xlsx)
[CCI Phase I.xlsx](https://github.com/18F/nsf-sbir/files/2622431/CCI.Phase.I.xlsx)

@deladie @gaanley @kbasnyat

**Comment by kmonterr** [comment]
Yay @seakhtar ! I'm so thankful you've gotten to the bottom of this!

Please remove all CCI Phase I awards. I have no idea what they are!!! They should not be a part of our API.

Thank you!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

We've removed the CCI awards and reset the API. The awards average does seem to be showing the correct figure in this branch:

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/apiResetTest/awardees/phase-1/

Just as a note, the NSF awards database data changed in a way that has caused some of the awards to filter into new topics (let me know if you'd like a deeper explanation of this). I'm hoping this new distribution is more accurate than the old one, but I wanted to warn you in case you were wondering why the topics numbers were different.  

If it all looks okay, let me know and I'll get it published!

**Comment by kmonterr** [comment]
Hi @seakhtar !!

The stats look great!!! Thank you so much. 

@benschrag said this. Maybe we should discuss? "it looks like a lot of the companies are being sorted into multiple topics?  And some into the wrong topics (e.g. the Advanced Materials companies are the same ones as those listed for Semiconductor)… I guess this is because they are only associated with PD.  Not sure there’s a fix, but maybe we can discuss?"

**Comment by seakhtar** [comment]
Hi @kmonterr -

It's been published! 

It was a little strange-- it took some troubleshooting, but some of the reference names for the PDs changed in the API. For example, Linda Molnar is now referenced as lmolnar, Anna Brady-Estevez as Anna Brady, Rick Schwerdtfeger as Carl Schwerdtfeger, and Ben is listed as Benaiah Schrag. 

Once I updated our data file to reflect the new reference names, all of the awards got shuffled again. I've discussed this with our developers and we think we might be able to come up with a fix that-- while requiring some manual work each time new awards are added to the database or the topic names changed-- might give us a little more control over how the awards are sorted. This would probably require lists of awards that belong to topics with the same PD, so we knew which belonged to which.

**Comment by benschrag** [comment]
Thanks!

I agree we might shift to a manual approach – we should just have PDs tag them when awards are made.  Happy to coordinate that, just send me a first list of companies to classify and guidance on how you want things formatted or delivered to you.

Cheers,
Ben
