### ISSUE TITLE
Portfolio Update - Biological Technologies

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1270]
1456071 – Lygos

1456372 - ARZEDA

1758659 – ALS-SP

1758591 – Synvitrobio

1758587 – Living Ink (which would also be nice on my Topics page)

1758698 – Enable Biosciences

1738463 – Manus Bio

1759075 – Navan Technologies

1758423 – Antheia

**Comment by seakhtar** [comment]
Hi @kmonterr -

In the topics PDF I've been using for the other featured companies, it listed these companies for Biomedical Technologies:

    - name: Protein Dynamic Solutions, LLC
    - name: Camras Vision, Inc.
    - name: Arytha Biosciences, LLC
    - name: CytoVale, Inc
    - name: OneBreath, Inc.
    - name: Rochal Industries LLP
    - name: Elidah, Inc.
    - name: Vaxess Technologies, Inc.
    - name: LambdaVision, Inc.
    - name: BriteSeed, LLC

Should I use these, or stick with the ones you've listed instead?
Just let me know!

**Comment by kmonterr** [comment]
Thanks, Sarah! Please use the ones I listed instead! :)
We are reviewing the draft today!
