### ISSUE TITLE
Quantum Information Technologies - portfolio page featured company

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1293]
You can move QC Ware to be the featured company in the Quantum Information Technologies topic.

https://seedfund.nsf.gov/portfolio/details/?company=qc-ware-corp

(It is currently in IT)

Thanks!

**Comment by seakhtar** [comment]
This has been added- it's on this branch for now:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/topicsUpdate2/portfolio/

**Comment by kmonterr** [comment]
Looks good! Thanks, @seakhtar !
