### ISSUE TITLE
Adding quantum presentation PDF to the Quantum page...

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1304]
Hi Sarah --

We'd like to add the PDF of Peter's recent Quantum presentation to the Quantum page.
https://seedfund.nsf.gov/topics/quantum-information/

Can you add a sentence after the paragraph about the topic and before the subtopic "IT3. Quantum Information Technologies." and link "reading a presentation to the PDF?
[NSF Funding Opportunities for Quantum Technologies - 10-25-2018 - Final.pdf](https://github.com/18F/nsf-sbir/files/2520544/NSF.Funding.Opportunities.for.Quantum.Technologies.-.10-25-2018.-.Final.pdf)

Learn more about NSF funding for quantum technologies by _reading a presentation_ given by program director Peter Atherton on October 25, 2018.

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just wanted to do a quick check- does this look about right?
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/quantumPDF/topics/quantum-information/

If so I'll go ahead and publish!

**Comment by kmonterr** [comment]
Yes! Thanks, @seakhtar !

**Comment by seakhtar** [comment]
Okay, this has been pushed to production and is now live!
