### ISSUE TITLE
Problem with 4 D Technology Corporation API Pull - not showing Phase II award too

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1305]
I'm not sure why, but the API isn't pulling 4 D Technology Corporation's Phase II award. Just its Phase I awards. I would like all of these on the portfolio page to show the Phase II award at the top, and the PHase I award at the bottom. 18F had worked on it so that's how they would show. Can you please fix this one and the others? Thanks,
- https://www.nsf.gov/awardsearch/showAward?AWD_ID=1556049

**Comment by seakhtar** [comment]
Hi @kmonterr 

Sorry for the delay on this! I've implemented the fix Lynette found and it should be showing up correctly when you click the 4D link (you might need to do a hard refresh if it doesn't appear right away):

https://seedfund.nsf.gov/portfolio/#instrumentation-and-hardware-systems-mi

Let me know if you notice any other issues--
Sarah
