### ISSUE TITLE
SAM Link Fix - 11/6

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1311]
Hi @seakhtar - Can you please check this out first thing tomorrow morning? I got alerted to this change to SAM and want to make sure our site's links are updated! Thank you!

Change of SAM URL - Need to Update Bookmark
Users who have bookmarked the SAM homepage will need to update their bookmark after 11/05/18. The following message is currently posted on SAM and has been shared with the Federal Service Desk (FSD): ALERT - Users who previously bookmarked this site will need to update their bookmark on 11/05/18. Users may continue to navigate directly to sam.gov, only the bookmarked url will be affected.

**Comment by kmonterr** [comment]
The link did change! 
Can you please update it first thing this morning everywhere on the Active and Inactive site???
Thank you!
https://www.sam.gov/SAM/

**Comment by seakhtar** [comment]
Hi @kmonterr -

This has been updated. With the site search I found it in three places (2x apply page and fastlane guide), but if you ever stumble across it somewhere else, just let me know!

**Comment by kmonterr** [comment]
Thank you, @seakhtar !! I think that's it!
