### ISSUE TITLE
Companies to Portfolio page - 

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1317]
advanced Manufacturing

- Please add unspun - https://www.nsf.gov/awardsearch/showAward?AWD_ID=1831088&HistoricalAwards=false
- PLease say: Elementum 3D (formerly Sinter Print Inc)

Medical devices
Please remove Aperiomics

Nanotechnology
Please add Astrileux https://www.nsf.gov/awardsearch/showAward?AWD_ID=1457418&HistoricalAwards=false

**Comment by seakhtar** [comment]
Hi @kmonterr 

Here is a branch with the updated companies-- if it looks okay, I'll go ahead and publish to the live branch!
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/adManCompanies/portfolio/
-Sarah

**Comment by kmonterr** [comment]
Hi @seakhtar - 
Two more little things then please push it live!

1. Somehow unspun is in the Featured Alumni and exits. Can you remove them from that?
2. I didn't see - Elementum 3D (formerly Sinter Print Inc) in Advanced Manufacturing...

**Comment by kmonterr** [comment]
Hi @seakhtar - Do you mind working on this today? I've been asked about it again today. Thanks!

**Comment by seakhtar** [comment]
Yes- it's been pushed to the live server. Sorry about that- was having some merging issues, but they're all straightened out now!

**Comment by kmonterr** [comment]
THank you!!!
