### ISSUE TITLE
Changing the site "inactive" mode after the deadline

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1323]
Can you please switch the code to "inactive" on Dec. 5? The home page should just say,  "Learn More"

We might be making some changes to the dates, but I'll keep you posted! It'll probably be in January/February.

Next deadline will be in June - deadline: June 2019
past_deadline: December 2018
solicitation_released: March 2019

**Comment by seakhtar** [comment]
Thanks Kelly, I'll make a test branch shortly before and push it live on the date!

**Comment by kmonterr** [comment]
Thank you, Sarah!

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just wanted to get the test branch created-- it's located here if you want to check it over. Let me know if there are any other adjustments you'd like me to make!

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/dec2018Switch/

**Comment by kmonterr** [comment]
It looks good!! Thanks, Sarah! I'll probably have some more changes coming in January to our apply pages. I'll keep you posted!
