### ISSUE TITLE
Remove Barry's Bio

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1372]
Hi Sarah - 

Can you please remove Barry Johnson and his bio from the IIP site? His time at NSF ended (sadly!)

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,

To remove Barry from the IIP page requires removing him from the NSF directory. I've gone ahead and made the request to do so, so his name should be removed within the next day or so!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I just checked and it looks like this has been completed!

**Comment by kmonterr** [comment]
Thanks, @seakhtar !
