### ISSUE TITLE
Updating the About Page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1375]
Hi Sarah - Are you all able to do an update for me on the Seed Fund – About page. The budget needs to be changed to $8.1 billion and the fiscal year is FY 2019. They would like this completed by COB today! Thank you!! Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr --

I've updated the about page with the new number, but I didn't see any reference to the fiscal year? 
Let me know if I missed it somewhere and I'll get it fixed!
https://seedfund.nsf.gov/about/

**Comment by kmonterr** [comment]
Sorry! I forgot to respond. It looks good!

**Comment by kmonterr** [comment]
Hi @seakhtar  - This is really concerning...the new budget number is not on the site anymore. Can you please fix it again and look into this to see what happened??

**Comment by seakhtar** [comment]
Hi @kmonterr ,

The number should be $8.1 billion, listed on the about page, right? I see it listed that way in the second to last paragraph (in the About NSF section), but is there another paragraph where it's wrong?

Just let me know and I'll get it fixed up.

**Comment by kmonterr** [comment]
It's still wrong on the press page...

**Comment by seakhtar** [comment]
Hi @kmonterr -

Okay, I've got it updated there too now. I did a site-search and it looks like there are a lot of pages we missed! So I will get them all fixed and get back to you

**Comment by seakhtar** [comment]
Hi @kmonterr -

Okay, so the budget was also showing up on the Phase I and Phase II Awards and Ambassadors pages. Along with the Press page, they've all been updated and should be on the site now. 

The old budget isn't showing up in the site search anymore, so I think we're good, but if you remember it in any other location just let me know!
