### ISSUE TITLE
NEW Phase I Process - March 4 Launch

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1378]
Hi @seakhtar - 

We'll be changing the Phase I application process to include a mandatory Project Pitch. I'll send revised language and links for the timeline and applicant pages. We will also be getting rid of "deadlines" and now having submission windows. We also want to make a banner for the site (like when we extended our deadline). 

Here's the to-do list. I'll hopefully send all of this to you by Friday. That way you'll have all next week to get it implemented on a test branch to push live on March 4 (Monday).

- [x] - Recreate the step-by-step on the website (Apply Page)
- [x] - Create a banner for seedfund.nsf.gov
- [x] -Update the call to action on the home page
- [x] - Schedule series of webinars
- [x] - Update the window end (deadline) everywhere
- [ ] - Make site active (March 4)
- [x] - create a new page devoted to the project pitch
- [x] - create new page about research and development
- [x] - New Topics pages on the site
- [x] - New PDF added to the site

--

**Comment by kmonterr** [comment]
Hi @seakhtar -

Here are four things to start - 

[RandD.docx](https://github.com/18F/nsf-sbir/files/2902540/RandD.docx)
[Project Pitch for website_KPM_GLN.docx](https://github.com/18F/nsf-sbir/files/2902544/Project.Pitch.for.website_KPM_GLN.docx)
[Apply page timeline.docx](https://github.com/18F/nsf-sbir/files/2902551/Apply.page.timeline.docx)

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Here are the R&D and Project Pitch pages. Just as a note, the Seedfund standard style for basic pages makes the text kind of squish to the side, and bolds the first paragraph. Let me know if you'd like me to counteract either of those things.

Otherwise, here are the pages:
 https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/updatesMarch2019/research-and-development/
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/updatesMarch2019/project-pitch/

I'm working on the alternate apply timeline-- it's giving me a little trouble due to the scripting of the active/inactive states and the accordions, but I'll keep you posted!

**Comment by kmonterr** [comment]
Hi @seakhtar  -
Thank you! Looking at the text can you make these changes - 

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/updatesMarch2019/research-and-development/
Change the title to - "What is R&D?"

Then spell out "research and development " in the first paragraph - 
America’s Seed Fund powered by the NSF requires that small businesses use the funding they receive in Phase I and Phase II for R&D. The goal of the small business’s project should be to determine the scientific and technical feasibility of a new concept or innovation that could be developed into new products, processes, or services. **Research and development** supported by the NSF’s program can be:
For the

**Comment by kmonterr** [comment]
@seakhtar - how's the apply timeline coming? Can we see a draft tomorrow morning? 

If it's not ready, we won't be able to go live with this change. 

Keep me posted!

**Comment by seakhtar** [comment]
Hi Kelly--
I'm still having a lot of trouble getting the entries to show up correctly. I've been trying to troubleshoot the issue but still haven't located the problem. Are we still on for the Monday deadline? 

Just a quick question-- the current timeline has different states depending on whether the site is in active mode or not. Will this new timeline have that as well? I'm wondering if that might have something to do with it. This has got all my focus though, so I'm hopeful I'll get it figured out soon! 

Regarding the other to-dos-- is there a specific way you'd like me to recreate the banner? Ie, will there be a new photo, or just a text change? And do we have the new webinar information to list on the events page? I'm thinking it might be good to create a branch with all the other updates in place so that I can focus on the timeline.

**Comment by kmonterr** [comment]
Hi @seakhtar -

We are still on for a Monday deadline, unless this isn't figured out!

This new process will only have the "Active" state. I wouldn't worry about the "inactive" state for the time being. 

The new banner should look like the banner that you added when we extended the application deadline in June. It'll just be text.

I like the idea of one branch for the timeline!

I'm waiting for the webinar info...Adding @benschrag here since he's assured me that it's coming!

THANK YOU!!
Kelly

**Comment by seakhtar** [comment]
Great- thanks! I'll get everything set up on a separate branch and add in the timeline once it's fixed up!

**Comment by kmonterr** [comment]
Thanks, Sarah!

**Comment by seakhtar** [comment]
Hi Kelly,

When you get the chance, can you let me know which dates you'd like for these fields?
deadline: 
past_deadline: 
solicitation_released:

I was also checking where else the deadline is mentioned besides the front page, but I think since we're removing it from the Apply timeline page, it doesn't seem to show up anywhere else? I'll double-check once I get the timeline straightened out but I wanted to ask in case you've seen it somewhere else that I'm missing.

Thanks!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

So it took some time but I did manage to figure out what was going on! It turns out the titles and descriptions of the timeline steps have trouble with special characters (such as colons, asterisks, and line breaks). For the descriptions I managed to use ASCII characters and html, but they don't work for the titles. That means it will not let me put asterisks around the "NEW"  on Step 4. If you would really like this in place, I can ask our developers to help me look for a solution. Otherwise, I think I got everything else. I'll add note in the wiki about this for future reference!

There was also an issue where any step that was not expired was automatically given an accordion arrow that opened needless white space. I did create a fix for this that basically tricks the system into thinking the step is inactive, but if we ever do want to bring inactive states back to the timeline this might cause problems. I think I can make a cleaner solution, but for the sake of time, I thought it best to leave it this way for now. 

Just a note-- the Project Pitch link won't work on this branch, but it will once I merge it to the main one. Let me know if I got anything wrong! 

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/timelineTest/apply/

**Comment by kmonterr** [comment]
Thanks, Sarah for working this out! I'm sorry it was more complicated than originally thought! I think it's fine to leave out the asterisks. 
Once you make these edits, please let me know and I'll send it around for feedback again today. 

Here are my initial edits:

Step 1- please update the list of topics, links and PDF in this accordion. 
Step 3 - I now know I need to shorten the text. "Preview the Project Pitch (optional)"
Delete the text after the title and make it only appear upon clicking on the arrow. please change it to: "Preview the information we look for in a Project Pitch[insert the link here]. 
Startups or entrepreneurs who submit a three-page Project Pitch will know within three weeks if they meet the program’s objectives to support innovative technologies that show promise of commercial and/or societal impact and involve a level of technical risk. 
Step 4 - Change the italicized text to - 
*Each small business can only submit one Project Pitch at a time and up to two Project Pitches per submission window. Any small business with a pending Project Pitch must wait for a response before submitting another Project Pitch. Any small business that has received an invitation to submit a full proposal, or which has a full proposal under review, must wait for a resolution of the full proposal before submitting a new or revised Project Pitch.
Step 5 - Please make sure that the Registration information is added back in. It is unchanged from what is currently on the apply page step 6 https://seedfund.nsf.gov/apply/
Step 6 - Delete this text - "Review the solicitation." and add links to the solicitations when they come ou. 
We only accept proposals from companies that have been officially invited to submit (via the Project Pitch process). You can check out our current SBIR solicitation or STTR solicitation to get a sense of NSF’s objectives.
Step 7- Make sure to link to the FastLane guide.

On the left side of the page - the timeline- 
Please add - "submission window will close on June 13" in red and keep the text about another submission window.

**Comment by kmonterr** [comment]
Comments on the other questions! I can't remember what past deadline is...Do you know? 

I need to ask our team what they want to put in the deadline fields...can you add this for the time being??

deadline: June 13 (submission window closes)
past_deadline: 
solicitation_released: March 2019

Do you mind adding the banner to this branch to replace the deadline extension banner from July? 
**Edit** Forgot to add that the main branch for all these updates (save the timeline) is located here:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/updatesMarch2019/

**Comment by seakhtar** [comment]
Hi @kmonterr -

Can you explain the banner a little more? I'd copied the code over from the deadline extension banner (the grey-blue box that's now on the test branch), but I didn't have text for it yet, so I just left the placeholder.  Is that the banner you wanted, or a different one? And do we have the text for it?

Also another quick question about the timeline-- did you want the note about June 13th to be it's own dot, or to appear on the same dot as the June 14th one? Here is the updated timeline page, to show what I mean:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/timelineTest/apply/

**Comment by kmonterr** [comment]
Hi @seakhtar -

Sorry if i wasn't clear! It's the text in Landing page & Applicants page2.docx

**Comment by kmonterr** [comment]
Two separate dots for now! We'll see if my bosses agree! :)

**Comment by seakhtar** [comment]
Got it!  Let me know if you'd like me to change the style/color of the banner in any way.
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/updatesMarch2019/

I forgot to ask- I think there's a Salesforce link needed for Step 4 of the timeline. Do we have that one?

**Comment by kmonterr** [comment]
Yes! I've asked for the link and will share it with you today/tomorrow at the latest.
Here are the links to the solicitations -
STTR Solicitation link - https://www.nsf.gov/publications/pub_summ.jsp?ods_key=nsf19554
SBIR Solicitation link - https://www.nsf.gov/publications/pub_summ.jsp?ods_key=nsf19555

**Comment by seakhtar** [comment]
Perfect--those are in place! I've gone ahead and merged the timeline to the main (test)branch, so everything is all in one place now. 
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/updatesMarch2019/

Just wanted to check- is there a link to the R&D page anywhere, or will it be linked to externally? I can't remember adding one in...

**Comment by kmonterr** [comment]
Thank you!! Somehow I missed this email!! I'm sending it around now for feedback. 

The R&D page should be linked from the Project Pitch Page. Just hyperlink the first use of the words research and development in the first bulleted item. I think it would also be good to hyperlink it from the About page too. The first bulleted item also mentions research and development.

I saw a few extra ">" on the project pitch page too. It wasn't linked in this version either.

Also, can you update the PDF of the topics here? There were changes. Maybe it's on another branch? 
[SBIR.Topic.updates.combined_2.25.2019final.pdf](https://github.com/18F/nsf-sbir/files/2916657/SBIR.Topic.updates.combined_2.25.2019final.pdf)

**Comment by seakhtar** [comment]
Okay, I think those last things should be all set now. Let me know if you notice anything else!

For the PDF, it should be showing the right one. If it's still not after doing a hard refresh, can you let me know which link is wrong?

**Comment by kmonterr** [comment]
The PDF is the right one! Thank you!

I didn't see other changes. I sent it to a lot of people, so I'll let you know if they catch anything else.

THANK YOU SO MUCH!

**Comment by kmonterr** [comment]
Hi @seakhtar 
Can you please add the following sentence in bold to this paragraph in Step 4?

*Each small business can only submit one Project Pitch at a time and up to two Project Pitches per submission window. **(The submission windows for 2019 are March 4-June 13 and June 14-December 12).** Any small business with a pending Project Pitch must wait for a response before submitting another Project Pitch. Any small business that has received an invitation to submit a full proposal, or which has a full proposal under review, must wait for a resolution of the full proposal before submitting a new or revised Project Pitch.

**Comment by kmonterr** [comment]
In Step 5- In the paragraph about SAM registration, can you please add the following bolded words? (They are bolded below but do not need to be bolded on the site).

You MUST register to do business with the U.S. government through System for Award Management (SAM). When you register, you’ll have to share bank account information **of the account where the NSF funds would be deposited.** This registration process is free and takes only 10-15 minutes to initiate, but can take up to three weeks to complete. An active SAM.gov registration is needed to create a FastLane account and submit a proposal to NSF. Registration expires after one year.

**Comment by kmonterr** [comment]
Here's the link to the Project Pitch!! 
https://nsfgov.secure.force.com/sbir/ 

It should be added to:
Step 4 - 
Please link online form and bold it in this sentence - Submit your Project Pitch using our **online form.** 

Project Pitch Page - 
Visit the **online form** to submit your Project Pitch or to preview the required fields.

**Comment by seakhtar** [comment]
Okay, I think I've got everything in place. The changes you mentioned above have been implemented, the two companies are now showing up on the project page, and the events are posted as well.

Let me know if there's anything that looks off, or if there are any further adjustments you'd like to make!

**Comment by kmonterr** [comment]
Thanks, Sarah! It looks amazing!!!

Do you mind removing GrokStyle and BayLabs from the IT featured companies? (I didn't catch that they were both there too!)

I'll let you know if we find anything else! Otherwise, please publish on Monday morning! (Anytime after you wake up/get to work).

**Comment by kmonterr** [comment]
Just FYI - I'm still waiting for the new link to the FAQs for the For Applicants page...hopefully coming today or Monday!

**Comment by seakhtar** [comment]
Sure- once the build completes, they should be gone from the IT section. 

Just to check-- the solicitations should be published by then? I think besides the timeline, the links show up on the about page as well, so I just wanted to sure that having the new ones already in place is okay. 

And I'll keep an eye out for the FAQ link!

**Comment by kmonterr** [comment]
Yes! The links should be live on Monday! 

Thank you!!

**Comment by kmonterr** [comment]
Hi @seakhtar !

The SBIR Solicitation has posted - https://www.nsf.gov/publications/pub_summ.jsp?ods_key=nsf19554

I noticed that we were wrong when we told you which was which. Can you please change the Apply page to link the SBIR solicitation to this link? (right now it's STTR). Step 6 and probably elsewhere.

Thank you! I'll let you know when STTR is live and we can push everything.

**Comment by seakhtar** [comment]
Okay, I've switched the links out! I'll wait for the STTR one--

**Comment by kmonterr** [comment]
Hi @seakhtar - 
Cecile was just able to review the draft pages. She had some additional changes that we should make before we push it.

In Step 1, See what we fund, let’s remove the word “Criteria”? Will they be confused with Merit Review criteria? It’s a little confusing having Merit Review, program objectives and then these criteria. They are really a summary of the program description. Instead, say: “What we look for”/”Here’s what we look for when determining which companies to fund:”? 

After Step 7, it says “Applications undergo panel and merit reviews.” Let’s delete “panel and”? The panels are performing merit review, and the PIs don’t need to worry about whether it occurs in a panel or ad hoc or combination manner.

I might have one more change coming too...

**Comment by kmonterr** [comment]
Another change for the R&D page - 
What is R&D? page
Please link the last sentence “Read our Apply page for more information.” to the Apply page.

**Comment by seakhtar** [comment]
Sure-- these changes have been made!

**Comment by kmonterr** [comment]
For the timeline (left side) - 

Please replace - at least 45 days
(six weeks) prior
to the end of the
submission window

With:

"prior to the end of the submission window"

Thank you!! That should be the last change (hopefully!!!)

**Comment by seakhtar** [comment]
Done- always good to get that fine-tuning in :)

**Comment by kmonterr** [comment]
Sorry @seakhtar - 

One more change!! Instead of "Start your application" on the home page, can we say, "Get started" 

There's been a lot of chatter about the word application v. proposal and I want to avoid any issues!

Still waiting for the STTR link and the FAQ link...

**Comment by seakhtar** [comment]
No problem-- it's been changed!

**Comment by kmonterr** [comment]
@seakhtar - 
let's push it live at 4:30 - with or without the STTR link!!

**Comment by seakhtar** [comment]
Sounds good!

**Comment by kmonterr** [comment]
STTR is live! Ha! Right on time!! Push away!
https://www.nsf.gov/pubs/2019/nsf19555/nsf19555.htm

Let me know when the site loads!

**Comment by seakhtar** [comment]
Haha-- just under the wire! The master branch has just finished building so it's up now. 

Let me know if you find anything that you would like to change!

**Comment by kmonterr** [comment]
THANK YOU, @seakhtar !!!!!!!!

**Comment by kmonterr** [comment]
Hi @seakhtar - Two last updates (I hope!)

The FAQs have been posted! Can you please update the link on the site?
https://www.nsf.gov/publications/pub_summ.jsp?ods_key=nsf19047

Can you please update the May 8 webinar language?
From: Program director Anna Brady-Estevez will explain the Project Pitch and answer questions about the program.
To: Program director Rick Schwerdtfeger will explain the Project Pitch and answer questions about the program.

**Comment by seakhtar** [comment]
Hi @kmonterr -

These updates have been made!
