### ISSUE TITLE
Adding 'How to Apply' webinars to the Events page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1427]
I'll send the links via email.

May 1 – Rajesh  - Registration Link

May 15 – Henry  - Registration Link

May 29 – Linda  - Registration Link

June 5 – Ben  - Registration Link

**Comment by kmonterr** [comment]
Can you please add these to the events page in chronological order? 

Sending the links via email now!

**Comment by seakhtar** [comment]
Hi @kmonterr--

Just wanted to check that this looks good before publishing:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/webinars0419/events/

Let me know and I'll push it live!

**Comment by kmonterr** [comment]
Hi @seakhtar -

Looks great! Thank you! Please publish it! :)

**Comment by seakhtar** [comment]
Okay, they've been published!

**Comment by kmonterr** [comment]
thank you, Sarah!
