### ISSUE TITLE
Adding a company to the Showcase page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1431]
Hi Sarah,

Can you please add these two photos and quote to the Showcase page? Where do you think it'll look the best?

“Without NSF funding, my company wouldn’t have been able to get off the ground. Early on, when we were too young and too risky for venture funding, NSF filled the gap with an SBIR Phase I grant. Now, after our Phase II is completed, we are a viable growth stage company that employs over 30 people and serves clients globally. The best part— our product is having a positive impact on society, giving people access to an ancient art form that was previously too costly and complex to create and install." - Ted Acworth, Founder and CEO of Artaic, a small business funded by NSF, that designs and fabricates custom mosaic tile installations using robots.
![Artaic_Custom_Mosaic-2405](https://user-images.githubusercontent.com/26437393/56160352-fe6f0d00-5f94-11e9-83de-dea44712c9c7.jpg)
![IMG_5922 (1)](https://user-images.githubusercontent.com/26437393/56160370-07f87500-5f95-11e9-96fa-25778b1176a4.JPG)

.

**Comment by seakhtar** [comment]
Hi Kelly,

This might not be possible, but do you by chance have a photo of the guy giving the quote? We have another quote on the page, but it's set up so that there's an image of the person right next to the block ([Improving LED brightness](https://seedfund.nsf.gov/showcase/#improving-led-brightness-and-reducing-power-consumption)). Since this is a quote as well, it would be look great for consistency, if possible!

If not, that's no problem- I'll maybe set it up like Shasqi's layout? There are a couple of options there!

**Comment by kmonterr** [comment]
![Ted Acworth - Artaic](https://user-images.githubusercontent.com/26437393/56313382-7d448100-6120-11e9-810f-d3f7aad36d49.jpg)
Here's his headshot

**Comment by seakhtar** [comment]
Awesome- thank you for finding one

**Comment by seakhtar** [comment]
Hi @kmonterr -

I've been trying to find the best way to lay out the photos, and I'm not sure I've succeeded so I figured I'd let you take a look in case you had any preferences! I've also just used the word Artaic as the header, but if you'd like me to replace it with anything else just let me know.

I have two versions-- one using the block-quote set up, and one without as an alternative. You can view them here:

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/showcaseArtaic/showcase/#artaic
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/showcaseArtaic/showcase/#artaic2

**Comment by kmonterr** [comment]
Hi @seakhtar - 

I like this version!
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/showcaseArtaic/showcase/#artaic

Can you remove the name Artaic in the header? please replace it with: 

Robots that create custom mosaics - Artaic.

Can you also link the name Artaic in the company description?

FYI - Oddly, both of the block-quotes show up in the previews.  #2 uses ThousandEyes' quote. Just a heads up to delete it before pushing the other live!

THank you!!
https://artaic.com/

**Comment by seakhtar** [comment]
This has been published! And thanks for the heads-up about the quote-- it's been deleted, but a second glance is always appreciated :)
