### ISSUE TITLE
Add a page and updating the Supplemental Funding Opportunities - Phase II 

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1432]
https://seedfund.nsf.gov/resources/awardees/phase-2/

Hi @seakhtar - 

Can you please add a page under the Supplemental Funding opportunities? 
Please call the page: **Additional Opportunities**

Here's the information to the page

NSF SBIR Innovative Postdoctoral Entrepreneurial Research Fellowship (I-PERF)
 
•      With funding support from NSF, the American Society for Engineering Education (ASEE) recruits, trains, mentors, places, and funds, early career STEM Ph.D. recipients from underrepresented groups to participate in entrepreneurial activities and perform innovative research at NSF Phase II SBIR/STTR awardee companies.
 
•     Postdoctoral  Fellowships are open to all fields in science and engineering funded by NSF within the current portfolio of active Phase II SBIR/STTR awardee companies.
 
•     Appointments are for one year.
 
•     The base stipend is $78,000 per year, plus optional individual health and life insurance, relocation and conference travel support, and professional development training in entrepreneurship. 
 
•   Number of Fellowships available: 31 
 
•   Deadline: Bi-monthly starting May 8, 2019, until filled.
 
•   More Information (https://iperf.asee.org)
 

2. Then can you remove the word "Partnerships" from each of the other pages and call them opportunities? They aren't really partnerships. 

Supplemental funding opportunities
**Commercial partnerships
Institutional partnerships
Educational partnerships**
Supplement submission instructions

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just wanted to acknowledge that I've seen this and will get back to you once it's all set!

**Comment by seakhtar** [comment]
Okay, does this look about right for the Additional Opportunities page? 

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/opportunities0419/resources/awardees/supplement/additional/

I've also updated the others to switch out the word partnership but let me know if there are any additional updates or changes.

**Comment by kmonterr** [comment]
Thanks, Sarah!

Can you make it look like the styles of the other pages? with bold?

Thanks for swapping out the word partnerships! Can you alphabetize the  supplemental 
<img width="284" alt="funding" src="https://user-images.githubusercontent.com/26437393/56432259-ad179400-629a-11e9-87a3-1e8f7c27f4fc.PNG">
opportunities in the sidebar?

**Comment by seakhtar** [comment]
Sure! Just to clarify, you'd like the bullet point text to be in bold?

**Comment by kmonterr** [comment]
If you look at the other pages, things like "max funding" "requirements" etc are in bold. Can you do that for this new page?
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/opportunities0419/resources/awardees/supplement/commercial/

**Comment by seakhtar** [comment]
Got it-- the ones that have colons? Let me know if I missed any--
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/opportunities0419/resources/awardees/supplement/additional/

**Comment by kmonterr** [comment]
Looks good! Thanks, SArah!

**Comment by seakhtar** [comment]
This has been published as well!

**Comment by kmonterr** [comment]
Thank you!
