### ISSUE TITLE
Small Business Week graphics

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1446]
Hi Sarah! We'd like to do something fun on our Showcase page for Small Business Week (Next week). Here are the graphics we made. Do you have ideas on how we can make them look good on the page? It could be a mosaic of sorts at the top?

Let me know if you have thoughts or want to share a mockup.
![Bay Labs Quote Image](https://user-images.githubusercontent.com/26437393/57042714-86127800-6c33-11e9-9831-3039687fec3c.png)
![Branch Technology Quote Image](https://user-images.githubusercontent.com/26437393/57042715-86127800-6c33-11e9-9903-4e98f4bfcd5e.png)
![Elidah Quote Image](https://user-images.githubusercontent.com/26437393/57042716-86127800-6c33-11e9-9002-cdd67fa47521.png)
![Keystone Tower Systems Quote](https://user-images.githubusercontent.com/26437393/57042717-86127800-6c33-11e9-8f5c-0ed740c8ca2d.png)
![Killer Snails Quote Image](https://user-images.githubusercontent.com/26437393/57042718-86127800-6c33-11e9-8b87-0ddba2e54afa.png)
![Omnity Quote Image](https://user-images.githubusercontent.com/26437393/57042720-86127800-6c33-11e9-88b9-c43ef774001e.png)
![posed2 Quote Image](https://user-images.githubusercontent.com/26437393/57042721-86127800-6c33-11e9-80a6-93f72e5342f9.png)
![Spheryx Quote](https://user-images.githubusercontent.com/26437393/57042722-86127800-6c33-11e9-8a6b-a87bc00b91f5.png)
![TAO Connect Quote Image](https://user-images.githubusercontent.com/26437393/57042723-86127800-6c33-11e9-9b00-60fae3861ba9.png)
![ThousandEyes Quote Image](https://user-images.githubusercontent.com/26437393/57042724-86ab0e80-6c33-11e9-8bb3-7d54711f9ec4.png)
![Tinkercast Quote Image](https://user-images.githubusercontent.com/26437393/57042725-86ab0e80-6c33-11e9-96ba-8fd2d4a6c8e5.png)
![Artaic Quote Image](https://user-images.githubusercontent.com/26437393/57042726-86ab0e80-6c33-11e9-9f2d-b66bf9e405f1.png)

Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Sure- I'll work on getting a branch in place so we can play around with how we want them to look!

**Comment by kmonterr** [comment]
Any luck, Sarah?

**Comment by seakhtar** [comment]
Hi @kmonterr -

I've been playing around with different layouts! At first I had them in a 3x4 grid at the top, but they were a bit small, and when I changed the grid to 2x6, I was worried it might be too long. So now I've got them spread out through the page, but wasn't sure if I liked that either. I've been trying to come up with another option :) Here is what it looks like though:

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/sbShowcase/showcase/

If you'd like to keep them all together though, I can give you an example of the grid version-- or let me know if there's something in particular that you'd like to see

**Comment by kmonterr** [comment]
Hi @seakhtar - 

It looks great! 

A few small changes and then please push it live either today or Monday morning!

Can you please move Elidah's graphic to the top - Swap Artaic and Elidah (Ted and Gloria)?

We also found a typo in the Omnity graphic. Here's the updated one!
![Omnity Quote Image](https://user-images.githubusercontent.com/26437393/57166115-2947c680-6dc7-11e9-96e4-9a4eb754092b.png)

Thank you for your help with this!!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -
Glad it looks okay-- the changes have been made and everything has been pushed to production!
