### ISSUE TITLE
Adding our new Division Director to the Bios page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1463]
Hi Sarah -

CAn you please add our new Division Director Andrea Belz to the Executives part of the bios page? (right above Gracie where Barry's photo and bio was). 

I also just edited Gracie's bio on dev. 

Once it's done, feel free to push it live!
Kelly 

Andrea Belz joined NSF in May 2019 as the Division Director of Industrial Innovation and Partnerships (IIP), which manages America’s Seed Fund powered by the NSF. Previously, Andrea served as Vice Dean for Technology Innovation and Entrepreneurship in the University of Southern California (USC) Viterbi School of Engineering, as well as Entrepreneur-in-Residence (Technology) of Industrial and Systems Engineering. She was previously a Visiting Professor of Engineering and Applied Sciences at the California Institute of Technology.  From 2014 to 2019, Andrea was the Founding Director of Innovation Node-Los Angeles, a regional hub for the NSF Innovation Corps (I-Corps™) program. She has worked with many university startups and investors, most recently representing a major angel investing group on the board of a Caltech spinoff laser manufacturer until its acquisition in 2018.  For nearly 20 years, Andrea has advised universities, corporations and other organizations on commercialization opportunities as managing member of the Belz Consulting Group. Her recent research has focused on technology ventures, from startups through publicly funded launch programs to private funding. Andrea has authored or co-authored dozens of refereed articles, peer-reviewed conference presentations and proceedings on technical topics and innovation, and she authored a book on product development. Belz earned her bachelor’s degree at the University of Maryland at College Park and doctoral degree at the California Institute of Technology, both in physics; she earned her master’s degree in finance at Pepperdine University Graziadio School of Business. 
![Belz 2015 head shot mid res](https://user-images.githubusercontent.com/26437393/57727572-d9d38700-765f-11e9-821c-3569e70af6e7.jpg)

**Comment by kmonterr** [comment]
Hi @seakhtar - Thanks for fixing the other issue!!

Do you mind adding Andrea to the page above Gracie please? 

Thank you!

**Comment by seakhtar** [comment]
Sure-- how does this look?
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/divDir/contact/bios/#executive-staff

**Comment by kmonterr** [comment]
Thank you! CAn you please remove the double mention of her name at the start?
Andrea Belz Andrea Belz ?

Otherwise, it looks good! Push publish. Thank you!
Kelly

**Comment by seakhtar** [comment]
Okay, it's been updated and is on the live site!
