### ISSUE TITLE
Update to the Form Prep in the FastLane Guide

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1477]
Hi Sarah!

Can you please add the new section to the very bottom of the last Form Preparation screen below the section on Supplementary Documents:  https://seedfund.nsf.gov/fastlane/form-prep-3/

The text and new screenshot is in this document [FastLane Guide update - Single Copy Docs 5.2019 project pitch.docx](https://github.com/18F/nsf-sbir/files/3229654/FastLane.Guide.update.-.Single.Copy.Docs.5.2019.project.pitch.docx)

Thank you!

**Comment by seakhtar** [comment]
Just wanted to follow up that these were bundled with the other updates and are live now as well.

**Comment by kmonterr** [comment]
Great!! Thanks so much, @seakhtar !!
