### ISSUE TITLE
Updates to the FastLane Guide - at the beginning

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1478]
Hi Sarah!

We need more updates to the guide! These are at the start. Let me know if you have questions! I want to create a new page within the guide.

Thank you!
Kelly 
[FastLane guide_Updates 5.2019 (aem edits) cjgKMM.docx](https://github.com/18F/nsf-sbir/files/3229708/FastLane.guide_Updates.5.2019.aem.edits.cjgKMM.docx)
## Steps to reproduce the behavior
- [ ]
- [ ]
- [ ]

## This issue is done when:
- [ ]
- [ ]
- [ ]

**Comment by seakhtar** [comment]
Hi @kmonterr , quick question. Currently, the guide is split up so that #1 is Overview and then #2 is Form Preparation, which takes up the next three pages. This is also how it's listed in the left nav.

Is Registrations considered it's own separate step, or part of Form Preparation? And if it's a separate step on it's own page, would you like it listed as "Registration" in the left nav?

**Comment by kmonterr** [comment]
Hi @seakhtar !

I thought it might help to have Registrations as its own page and listed as Registrations in the left nav above form prep. 
Thanks for asking!!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr - 
Just wanted to let you know this is almost complete-- I'm just going to do a final quality check to make sure I didn't miss anything, but if you want to check it out in the meantime, it's on this branch:

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/fastlaneUpdates0619/fastlane/

**Comment by kmonterr** [comment]
Hi @seakhtar - Thank you so much!! This is looking great!!! 

I just have a few changes now that I'm seeing it on the site...

On the FastLane Overview page: 

- Can you please modify the last paragraph and move it up to the top part of the first page? Does it make sense to make sure that these dates are coded as the deadlines?  

FastLane will not accept proposals after 5:00 PM submitter’s time on June 13th. However, a new submission window will open on June 14th. If you are unable to submit by 5:00 p.m. local time on June 13th, please submit as soon as possible once the new window opens.

- After the How to Apply link, can you make an H3 heading (like the Were you invited to submit heading) that says: "Read the SBIR/STTR Solicitation". These two paragraphs should go right after that H3 heading.

- Can you add the master SBIR and STTR solicitation links to the text too?
The Phase I **SBIR** and **STTR** solicitations explain what information should go in the proposal. The following steps will walk through the process of submitting a proposal to FastLane, one of NSF’s electronic proposal submission systems.

SBIR/STTR Proposals must be submitted to NSF via FastLane. The NSF’s Research.gov proposal preparation and submission site is not currently available for SBIR and STTR proposal submissions.

On the Form Prep Page: 

Can you make this paragraph (in the Cover Sheet section) red?? It's important that they see this!

- Proposal Cover Sheets missing required data field information will generate validation errors and cannot be saved or submitted. In addition, you may lose information entered on the Cover Sheet if it cannot be saved or submitted.

**Comment by kmonterr** [comment]
Hi @seakhtar - 

Also noticed - 

(2) In Definitions https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/fastlaneUpdates0619/fastlane/definitions/, some topics are not in alphabetical order. On quick glance, I see: Development, Equivalent proposal, Awards support/performance period, Overlapping proposals, …
Can you fix this?

**Comment by seakhtar** [comment]
Sure-- I will get these all implemented and get back to you!

**Comment by kmonterr** [comment]
Thanks, @seakhtar !!

**Comment by seakhtar** [comment]
Hi @kmonterr -

These last changes have been completed and the PDF updated. Let me know if you notice anything off. Otherwise, if not, just let me know when you'd like to publish!

https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/fastlaneUpdates0619/fastlane/

**Comment by kmonterr** [comment]
Hi @seakhtar - Great!!

I just moved the first paragraph a little further down on the first page. (I did it on the branch for you and saved it). Once that change loads and you update the PDF, feel free to push it live!!!!!!!

THANK YOU !!!!!!!!!!

**Comment by seakhtar** [comment]
Hi @kmonterr -

One more problem! There's a conflict happening when I try to merge the branch into dev, but when I try to view it the system just hangs:
https://github.com/18F/nsf-sbir/pull/1484/conflicts

Is this something I could contact Amir about, or is it a question for someone else?

Once I get that one thing taken care of I'll be able to get everything pushed to the live server!

**Comment by seakhtar** [comment]
Never mind! For some reason it worked when I clicked the link I gave you. I'll let you know when it's live!

**Comment by seakhtar** [comment]
Okay, everything is live- let me know if you need anything else.

Have a good afternoon!
