### ISSUE TITLE
Swap the Phase II Prep PDF?

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1494]
Hi Sarah!

Can you please swap this old Phase II Proposal Prep PDF for the new one?

https://seedfund.nsf.gov/assets/files/awardees/Phase%20II%20NSF%20SBIR.pdf

Thank you!
[NSF SBIR-STTR Phase II Proposal Contents (updated June 2019).pdf](https://github.com/18F/nsf-sbir/files/3327094/NSF.SBIR-STTR.Phase.II.Proposal.Contents.updated.June.2019.pdf)

CC- @bschrag

**Comment by seakhtar** [comment]
Hi @kmonterr --

This has been switched out and should now be appearing on the live site!

**Comment by kmonterr** [comment]
Thank you!!! :)
