### ISSUE TITLE
New Submission Screenshot on FastLane Guide

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1503]
HI @seakhtar -

Can you do us a favor today? We found out that the FastLane submission screenshot is outdated in our guide. 

It's on - https://seedfund.nsf.gov/fastlane/proposal-submission/

The first screenshot on the page doesn’t have the “Submit SBIR” and “Submit STTR” buttons.  Please replace with this one, but can you please first highlight the same button (Allow SPO Access) as they have on the current page?

Thank you so much!
Kelly 
![2019 Fastlane submission screenshot](https://user-images.githubusercontent.com/26437393/61063036-499a8f80-a3cd-11e9-9146-fa1e2d362660.jpg)

**Comment by seakhtar** [comment]
Hi @kmonterr ,

This has been completed, and I've updated the PDF as well!

Have a good afternoon-

**Comment by kmonterr** [comment]
Looks great! Thanks, @seakhtar !! Have a good one :)
