### ISSUE TITLE
Trouble with E-Mail and Web Page

### ISSUE THREAD

**Issue by sbguthery** [18F/nsf-sbir#1523]
1) E-mail to

awardsearch@nsf.gov

bounces.

2) On this page:

https://seedfund.nsf.gov/awardees/phase-1/

The grants under AI, IT, and QT are all the same.

The grants under EP, R, SE, and W are all the same.

For all I know this may be correct but it does seem a little strange than AI 
grants are the same as quantum information technologies grants.

**Comment by kmonterr** [comment]
Hi @seakhtar - 

Can you please look into this issue? We thought this was fixed with the update.

Thanks,
Kelly

**Comment by seakhtar** [comment]
Hi Kelly,

-We'll look into the email issue. 
-For the updates, not sure if you remember that email thread, but while most of the awards were in place there are a handful that aren't popping up correctly that we've been troubleshooting. We can publish what we have so far in the meantime-- it would be far more accurate than what's currently on the site, or we can hold off until we get those last few sorting correctly!

**Comment by kmonterr** [comment]
Thanks for the updates, @seakhtar !

Can you please publish what you have so far while you troubleshoot? Thank you again!

**Comment by seakhtar** [comment]
Hi @kmonterr -

Good news! We managed to get those last awards squared away. All of the numbers are matching up, so I think we're all set now! The branch has been pushed to production. 

I'll work on getting the email issue straightened out now. Have a good evening!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I've looked into the email issue, but I haven't been able to replicate the problem yet. The address that pops up in my email client when I click the link is the same one that shows up when I click it from the NSF awards database. I sent a test email this morning, but haven't gotten a bounce back message yet. Sometimes they can take a while to arrive, so I'll keep an eye out for now.

**Comment by kmonterr** [comment]
Thanks, @seakhtar - Keep us posted!

**Comment by seakhtar** [comment]
Hi @sbguthery -

I still haven't received a bounce back message from my test yesterday. Do you mind trying again? I'm wondering if it might have just been a temporary server issue. If you get another bounce, if you can forward it to sarah.akhtar@dakota-consulting.com I'll take a closer look. Thanks!
