### ISSUE TITLE
Removing Nancy Kamei and transferring Digital Health and Medical Devices

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1527]
Hi @seakhtar -

Can you please remove Nancy Kamei from our website? She no longer works in our office. :(

Please add these topics and their related awards to - 
Digital Health -> Peter Atherton
Medical Devices -> Henry Ahn

Thank you!!
Kelly

**Comment by seakhtar** [comment]
Sorry to hear it! But I will get them transferred over and let you know--

**Comment by kmonterr** [comment]
Thank you! Let me know if you run into any issues!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I've removed Nancy from the Portfolio and Contact pages, and resorted her topics to Henry and Peter. A site search doesn't show her name anywhere else on the site, so I think those were the only pages affected!
