### ISSUE TITLE
Portfolio page update

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1531]
Can you please update the paragraph at the top of the page to use this new data?
 - Since 2014, our awardees have had **97 exits** and have received **approximately $7.2 billion** in private investment. 

- can you also please put a date updated stamp somewhere on the page? I want people to know when we last updated the page. It would be 8/30/2019 for this number.

Thank you!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I'm just getting this finished up and wanted to check with you about the date stamp. I currently have it at the [bottom of the page](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/portfolioPageUpdate-819/portfolio/), but we could also put it right after that first paragraph, if you'd like to emphasize that information being up to date. Let me know if you prefer that-- if so I'll switch it before publishing!

**Comment by kmonterr** [comment]
It looks good! I would keep it as is (on the bottom!)

Thank you!!!
