### ISSUE TITLE
Showcase Page - addition and reorg

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1543]
Hi @seakhtar - 

can you please add this video to the showcase page?
https://youtu.be/jvnyzUogCZo

I want to move things around a bit too. Once you put it at the top let me know and I'll make some suggestions for moving the rest of the content!

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

I've added the video to the page using the standard layout (dark background, text next to the video). Let me know if you had something else in mind. I've just used placeholder text from the youtube page for the title/description, but we can update or remove that once we're finalizing things.

Just let me know which changes you'd like to see and I'll move things around!
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/showcaseUpdate0919/showcase/

**Comment by kmonterr** [comment]
Hi @seakhtar !

Thank you! I have noticed that the little testimonial cards look really tiny on a phone. Can we fix that if not do you have an idea of where to put them or how to better use them on the site?

Can you please remove 
Manufacturing equipment to build taller wind turbines on-site
Rare words uncover strongly-related ideas shared between documents and across languages
Improving LED brightness and reducing power consumption
All-in-one weather and crop monitor delivers agricultural insight to farmers

Otherwise, it looks good! Feel free to publish :)
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr 

Just wanted to confirm those videos have been removed. 

For the testimonial cards, I'll see if I can get them to resize better on smaller screens. Once I have an example made up, I'll send you a link to see if that might work better!
