### ISSUE TITLE
EVENTS ONLINE

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1591]
Hi @seakhtar -

I added four webinars to the events page and the build keeps failing! Do you mind checking it out this morning and pushing the site live?

I made some other updates that went through fine too.

Thank you!!
Kelly

**Comment by kmonterr** [comment]
Hi Sarah - I'll ask Federalist now too...I'd appreciate your help with this too!

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just wrote you an email but to log it here as well-- it looks like adding a colon (or dash) to the event title confuses the system and throws an error (it thinks you're starting a new field, I think). I believe there's a way around it, so I'm just doing some research!
