### ISSUE TITLE
Program Director Topic Areas Changing

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1597]
Hi @seakhtar - 

We'll have a few new program directors coming in so our portfolio will be shifting!

Stay tuned, but we'll be changing "educational technologies and applications" to "educational technologies" and it will be moving to Peter Atherton.

The rest of the changes are forthcoming. Please don't move anyone yet, but I wanted you to be aware!

Thank you!
Kelly

**Comment by seakhtar** [comment]
Thanks @kmonterr , that's good to know! I'll wait to hear back.

**Comment by kmonterr** [comment]
Hi @seakhtar - 

Busy week!!

We have the first of several updates to portfolio assignments.

Rajesh Mehta will take over Environmental Technologies.
Peter Atherton will take over Educational technologies (and the name will now just be Educational Technologies - no more applications).  

Let me know when you want me to look something over!
Kelly

**Comment by kmonterr** [comment]
Hi Sarah -

Can you please make the above-mentioned changes?

And, these as well?

1.	Biomedical (BM) – Henry Ahn
2.	Medical devices (MD) – Henry Ahn
3.	Digital health (DH) - Alastair Monk

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I will start getting this implemented. Since the PD assignments heavily influence the display of the portfolio pages, I'm going to work with the team to make sure everything ends up mapped correctly to reflect the changes. 

I'll keep you posted!

**Comment by kmonterr** [comment]
Great! Thank you, Sarah!

**Comment by kmonterr** [comment]
Hi @seakhtar -

Here are a few little things I noticed on the Portfolio Page in the test branch - 
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/dec18-updates/portfolio/

Chemical Technologies - 
Green Chemicals and Chemical Alternativess (CT5) - There are two "S"es

On the Pharma Tech page:
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/dec18-updates/topics/pharmaceutical-technologies/

Instead of having the full link shown, can you hyperlink the bolded text?
and must follow **NSF policies on research on human subjects** (https://www.nsf.gov/bfa/dias/policy/human.jsp). 

Space topic - missing two spaces (funny! Spaces in space!)
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/dec18-updates/portfolio/

Space (SP): Extra-terrestrial Resource Extraction (SP1)  Geological and Geoclimatic Science Data Technologies (SP2)  Ground Launch Sites and Satellite Operations Technologie**s(SP3)**  In-space Manufacturing Technologies(SP4)  Navigation and Positioning Technologies (SP5)

**Comment by seakhtar** [comment]
Thanks Kelly!! I always appreciate another pair of eyes checking things over. These edits have been made on our test branch. 

Just to answer your question-- that's right, the date at the bottom gets updated automatically (on the portfolio.md page). From now on I'll make sure to give it an update whenever we make changes on the portfolio page.
