### ISSUE TITLE
Housekeeping items - 11.1.2019

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1599]
Hi Sarah!
Can you please remove these three members from the ADCOM webpage?

- Tom Knight
- Eugene Krentsel
- Susan Butts
- 

Thank you!!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Looks like there's an update to the Upcoming Events page in dev-- would it be okay for me to push that to production along with this change?

Just let me know if you'd like me to hold off!

**Comment by kmonterr** [comment]
Yes - please push it! Thanks so much, Sarah!

**Comment by seakhtar** [comment]
Okay, looks like everything is all set!
