### ISSUE TITLE
NSF SBIR website error

### ISSUE THREAD

**Issue by tkelly62** [18F/nsf-sbir#1605]
## Expected Behavior
on https://seedfund.nsf.gov/resources/review/peer-review/ the five criteria listed under 1. and 2. should list different information. 

## Actual Behavior
on https://seedfund.nsf.gov/resources/review/peer-review/ the five criteria listed under 1. and 2. are identical. This should not be presumably. 

## Steps to reproduce the behavior
- [ ] I have repeated this several times. 
![Peer Review Criteria NSF SBIR](https://user-images.githubusercontent.com/57493508/68398469-66a45c80-013a-11ea-94a1-6f23fc8c6293.jpg)

- [ ]
- [ ]

## This issue is done when:
- [ ]
- [ ]
- [ ]

**Comment by kmonterr** [comment]
Hi @tkelly62 - Thanks for reaching out! Although it looks odd, this is correct! Numbers 1-5 on each just refer to the review criterion above. I hope this is helpful and thanks for your submission.
