### ISSUE TITLE
New Program Director - Alastair Monk

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1609]
Alastair Monk (see other topic issue for his assignments).
![Alastair](https://user-images.githubusercontent.com/26437393/68791771-f6a14500-0617-11ea-9e20-4484aa999d99.png)

Alastair Monk joined the National Science Foundation as an SBIR/STTR program director in November 2019. Prior to NSF, Alastair was an active member of the startup ecosystem in Virginia as a mentor, judge, and entrepreneur. He has been directly involved in medical startups for the last 10 years. Most recently, Alastair was the Vice President of Medical Products at Cupron, Inc. where he led the development, protection, and commercialization of a platform copper antimicrobial technology. He also founded and ran Chrysalides Consultants, a consultancy firm mentoring and providing strategic support to medical startups. Prior to Cupron and Chrysalides Consultants, Alastair was Head Scientist at Biocontrol Ltd (now Armata Pharmaceuticals) developing and commercializing bacteriophage therapy for clinical applications. Alastair had an active academic life as a microbiology postdoc at Virginia Commonwealth University in Internal Medicine, and has authored a number of published papers, conference abstracts, and oral presentations. Alastair has a Ph.D. in microbiology from the University of Bath UK, and a BSc in microbiology from the University of Birmingham, UK.

**Comment by kmonterr** [comment]
Hi Sarah! Can you please prioritize this today? We'll have another person starting on 11.25. I'll also send you his info so there's more time!

Thank you so much!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Just a note about this-- the only way to add Alastair's bio to the site is by listing it on the portfolio page. Since the portfolio page drives the Phase I and Phase II pages, this might cause some trouble with those.  I can just put him on the site for now and fix the Phase I and II pages after, but since it requires fiddling with the API it usually takes a couple of day to straighten out-- especially as we have other changes happening as well (with the reshuffling of the PDs from the other issue). 

Would you like me to go ahead?

**Comment by kmonterr** [comment]
yes! that's ok to list him on the portfolio page. I think that's what you mean? If it's the awards Phase I and Phase II - I thought we disassociated them with PD and have been sending a manual update via spreadsheet (until we have the fix for the API, which we are working on). 

Can you work on the changing of the portfolio? as noted here and in #1597? Let me know if it's super hard. Our boss is very interested in seeing these changes noted soon.
Here's the new portfolio assignment.

Biomedical (BM) – Henry Ahn
Medical devices (MD) – Henry Ahn
**Digital health (DH) - Alastair Monk**
Rajesh Mehta will take over Environmental Technologies.
Peter Atherton will take over Educational technologies (and the name will now just be Educational Technologies - no more applications).

**Comment by seakhtar** [comment]
Got it-- that's right! I was confusing myself thinking that there was going to be a brand new topic. As long as it's just switching out the names, I think we'll be okay. We noticed on our last API refresh that there were new awards that will need to be assigned a topic code, but for now I will just focus on getting the PD assignments reflected on the site.

Will keep you posted--

**Comment by kmonterr** [comment]
Ha! I know! This is so confusing. I think Lynette sent us a list. I'll ask Ben to look at it.

We haven't added any new topics yet, but I'll be sending you a list in the next couple of weeks. We'll have 2 new topics (at the least) and another new PD.

**Comment by seakhtar** [comment]
Good to know-- thanks! 
Couple quick questions:
-Did you want me to change the name of the topic "Biomedical Technologies" to "Biomedical"?
-I've put Alastair's email address as amonk@nsf.gov, but wanted to make sure it wasn't something different?

Here is what I have so far: PD's moved as mentioned above, Alastair's bio information added, and I've updated the Educational Technologies page to remove the "Applications"
Still double-checking things but if you see anything that looks off, let me know!
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/pdAddtion/portfolio/

**Comment by kmonterr** [comment]
Hi Sarah,

Looks great! Feel free to publish.

Thank you!!
Kelly

**Comment by seakhtar** [comment]
Just wanted to confirm that this has been completed!
