### ISSUE TITLE
New Program Director

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1617]
Hi Sarah!

I hope you're well. We have a new PD starting on Monday. Do you mind adding him to the site? I'll send you his topic area and email address on Monday morning!
![Erik](https://user-images.githubusercontent.com/26437393/69453329-b46fb600-0d31-11ea-9240-950bc5e18920.png)

Erik Pierstorff joined the NSF as Program Director in November 2019. Prior to NSF, he was Chief of Operations and led Research and Development at O-Ray Pharma, where he focused on integrating biology and biomedical engineering for the goal of drug development and sustained drug delivery for the treatment of hearing loss and other ear disorders. During his time working at early stage companies, he helped secure both Angel investment and non-dilutive funding in the form of licensing and co-development deals. Additionally, he served as Principal Investigator on several Phase I, II and IIB SBIR grants from the National Institutes of Health and NSF. His research interests have focused on the intersection of the biotic and abiotic, spanning molecular and cell biology, materials science, gene therapy, nanomaterials and drug delivery. Erik has a Ph.D. in Molecular and Cell Biology from the University of California, Berkeley, and a B.S. in Biology from Emory University.

**Comment by kmonterr** [comment]
Hi sarah - can you add erik? He'll be taking over the Biological Technologies portfolio from Ruth.

Please do not delete Ruth from the site, but she will not have any topics associated with her. Just leave her on the site for now in the contact us and bio page!

**Comment by kmonterr** [comment]
Hi Sarah! Do you mind looking at this before the holiday? Thnak you!

**Comment by kmonterr** [comment]
Hi Sarah - Do you mind adding Erik to the site today/tomorrow? Thanks! @seakhtar

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I'm so sorry, for some reason this request never got sent to my inbox- I'll get him posted today.

**Comment by seakhtar** [comment]
Hi @kmonterr ,

I have a branch created with Erik here: 
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/new-dir-erik/portfolio/

I have been trying to get Ruth to stay in there-- I can get her to show up on the bio and contact pages okay, but since the bio pages are generated from the portfolio page, she appears there as well and there doesn't seem to be a way to remove her. It looks a little odd- I was wondering if there might be a different title to use in place of a topic name-- something to delineate her section? Let me know what you think!

**Comment by kmonterr** [comment]
Hi @seakhtar -

Is there any way to make her show up like Andrea and Gracie show up? They are on the exec staff bios page, but don't appear with the topics. She is not exec staff, but her bio could still be on the page. I don't think she wants to be contacted either. Since she isn't taking new proposals, I think that's the best option.
Let me know if it works! 
Kelly

**Comment by seakhtar** [comment]
Thanks @kmonterr ! While I was trying to figure out how to move her out of the executive bios section, I realized I could hard-code her information into the layout templates themselves. In other words, I think we're good! 

Here the branch for one final check before publishing:
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/nsf-sbir/new-dir-erik/contact/bios/#Rick%20Schwerdtfeger

**Comment by kmonterr** [comment]
Yes! I think it looks good! 

Just one weird thing - Is there a way to make it so the text stays within the box on the contact us pages?
![size issue](https://user-images.githubusercontent.com/26437393/70269650-ccebc180-1770-11ea-955f-97b7f26cf73b.JPG)

Please publish and thanks again!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -
Just wanted to confirm that this is now up, and the box-sizing issue has been fixed!

**Comment by kmonterr** [comment]
Thanks, Sarah!
