### ISSUE TITLE
A few changes for Dec. 18th- ish

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1627]
Changes are **bolded**
Homepage:
1. "WE INVEST UP TO
**$1.75** MILLION IN
SEED FUNDING.

2. We support research and development of **deep technologies – those that are based on discoveries in fundamental science and engineering**. As we review applications, we consider your technology’s innovativeness, commercial potential, and possible societal impact.

About page: https://seedfund.nsf.gov/about/
1. Up to **$1.75M** / 24+ months. Receive up to **$256,000** in seed capital to conduct product Research and Development (R&D) over six to 12 months. During this period, your company will be immersed in the NSF network and you’ll receive training and mentorship from seasoned entrepreneurs and innovators. After you complete your Phase I award, you’re welcome to apply for a second-round investment of $1,000,000 over 24 months. During the course of that award, you can apply for supplements that may add up to another $500,000.
2. Program basics - When you decide to apply for funding**, you’ll submit a Project Pitch. You'll hear back within three weeks if your idea is a good fit for the program. Once you're invited, you'll submit a** Phase I proposal for up to $**256,000**, which will cover at least six (and up to 12) months of work. You’ll find out whether your proposal was accepted or declined within four to six months of the proposal deadline.
3. If your technology needs more development — and if you’ve met all the Phase I requirements — you can apply for more funding. Phase II awardees receive up to **$1,000,000** over two years.

For Press - https://seedfund.nsf.gov/press/
1. America’s Seed Fund powered by NSF awards $200 million annually to startups and small businesses, transforming scientific discovery into products and services with commercial and societal impact. Startups working across almost all areas of science and technology can receive up to **$1.75 million to support research and development (R&D)**, helping de-risk technology for commercial success. America’s Seed Fund is congressionally mandated through the Small Business Innovation Research (SBIR) program. The NSF is an independent federal agency with a budget of about $8.1 billion that supports fundamental research and education across all fields of science and engineering. For more information, visit seedfund.nsf.gov.
2. Please update the link to Dr. Cordova's bio - https://www.nsf.gov/news/speeches/cordova/cordova_bio.jsp
3. We'll also have a new one pager - to replace this one at the bottom of the page and on the for applicants page (old one-  https://seedfund.nsf.gov/assets/files/press/overview2019.pdf )

Contact us page: https://seedfund.nsf.gov/contact/
1. (Remove the link to the google form)
Notice something wrong with the site or want to make a recommendation? Open an issue in our GitHub repository. Please provide a detailed description of the problem you encountered (along with screenshots and steps we can take to reproduce the error) or the change you’re suggesting. **You can also share feedback by emailing us at SBIRwebmaster@nsf.gov.** We’ll respond as quickly as possible — usually within a few business days.

Showcase page: https://seedfund.nsf.gov/showcase/
1.  (Remove the link to the google form)
**We’re not interested in innovation for innovation’s sake — we back technologies that promote the social good. Learn more about our companies’ impact here.**
2. Please remove all of the images with the pull quotes (the square ones). Is it possible to move them to the for applicants page? Is there a way to make them look good on that page?
3. I'm submitting a separate issue with new videos to use.

For Applicants: https://seedfund.nsf.gov/resources/applicants/
1. add the images with pull quotes from the showcase page.
2. I'll send a new link to the FAQs
2. Update the "We offer a PDF version of program basics, too.)" with the new one.

Portfolio, showcase, apply page and project pitch updates coming!

**Comment by seakhtar** [comment]
Hi @kmonterr,

I'll get a a test branch created for these! 
Just as a heads up, I didn't get an email alert for this issue either... I'm going to try checking in on github more often until I troubleshoot the problem, but wanted to warn you in case you ever need me to look at something time sensitive.

**Comment by kmonterr** [comment]
These look great! I'm looking through the topics/portfolio pages now. I'll send the FAQ link as soon as I see it.
