### ISSUE TITLE
Changing a link

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1664]
![embrace diversity page link](https://user-images.githubusercontent.com/26437393/72379840-35b84900-36e2-11ea-9433-921ea1949b4b.JPG)

can we link this to the Showcase page instead of the Apply page- 
https://seedfund.nsf.gov/showcase/

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just confirming this was completed!

**Comment by kmonterr** [comment]
Thank you!!

**Comment by kmonterr** [comment]
Thank you!
