### ISSUE TITLE
Please remove ARPA-E

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1680]
Hi Sarah!

Can you please remove ARPA-E from the event list too? They aren't having it in 2020!

Thanks so much!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,
This has been completed and is on the live site!

**Comment by kmonterr** [comment]
I also just removed Synbiobeta. I made the change to Dev. Feel free to push this as you push the submission window variables!
Thank you!
