### ISSUE TITLE
ADding a PDF

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1692]
Hi Sarah -

I tried to add a PDF to the site (Master branch), but it's not showing up.

assets/files/applicants/How to Submit SBIR Proposal 02.11.2020.pdf

Can you please check my work and fix it if needed? I'm also adding the PDF here.
Kelly 

[How to Submit SBIR Proposal 02.11.2020.pdf](https://github.com/18F/nsf-sbir/files/4193182/How.to.Submit.SBIR.Proposal.02.11.2020.pdf)

**Comment by seakhtar** [comment]
Hi @kmonterr ,

It looks like it's in the master branch's directory-- I know sometimes Seedfund gets a little weird about pushing PDFs, so maybe there was just a lag for it to show up? Or is there a specific link you were using to reference it that isn't working properly?

**Comment by kmonterr** [comment]
It worked! Thanks, Sarah! I think I checked too soon...
