### ISSUE TITLE
Events Page Updates

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1705]
Hi Sarah!

I was trying to fix some of the text on the event page -
https://github.com/18F/nsf-sbir/blob/dev/_data/events_upcoming.yml

It didn't build in dev and I'm not sure what's up! Do you mind taking a look and pushing it live? I worry that it's another Federalist thing!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

These changes were posted with the recent updates, so they should be in place now. Let me know if there are any others you'd like to make!
