### ISSUE TITLE
Phase II Deck

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1706]
Hi Sarah!

Do you mind adding this presentation to the site? I'm deciding where to link to it now...but let's get it up there so we can share it!
[Phase II Solicitation Webinar 022020 Final.pdf](https://github.com/18F/nsf-sbir/files/4233035/Phase.II.Solicitation.Webinar.022020.Final.pdf)

We'd like to link to this tomorrow, if possible!

Thank you!
Kelly

**Comment by kmonterr** [comment]
I added it to the master branch this morning. Can you please check that I did it right? It appears, but I'm not sure if I should have added it to Dev/Staging too...

**Comment by seakhtar** [comment]
Hi @kmonterr -

That should be fine! I'm adding it to dev/staging now to get them caught up.
