### ISSUE TITLE
Changing a word...

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1707]
This is minor but I just wanted to let you know that our website (https://seedfund.nsf.gov/resources/awardees/phase-2/apply/) refers to the submission window as a deadline.

“There are quarterly deadlines for submission of a Phase II proposal. The next submission date is March 5.”

Please change it to:
“There are quarterly **windows** for submission of a Phase II proposal. The next submission date is March 5.”

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just confirming that this has been completed!
