### ISSUE TITLE
Events - Update

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1725]
Hi Sarah -

Can you please remove the last two webinars? 3/9 and 3/12?

There are also many of the annual events that have been postponed/canceled. Do you mind looking at each event and moving it to the new month? or writing (postponed) next to events that haven't been rescheduled yet?

Thank you!

https://seedfund.nsf.gov/events/

**Comment by seakhtar** [comment]
Hi @kmonterr -

I've looked through the events and at the moment there were only a couple that actually changed their date. But a lot of the ones in April mentioned that they are monitoring things and might still make the decision to reschedule, so it might be good to keep checking back. 

I also removed the two webinars and pushed everything to production!

**Comment by kmonterr** [comment]
Hi Sarah!

Can you please check/publish the events page? I added this webinar!
kelly 

Webinar: NSF Funding for COVID-19 R&D for Small Businesses
Date: 3-31-20
Registration link: https://nsf2.webex.com/nsf2/onstage/g.php?MTID=ee26cd909798ba878bc81b15f1066c91d

**Comment by kmonterr** [comment]
https://github.com/18F/nsf-sbir/blob/dev/_data/events_upcoming.yml
