### ISSUE TITLE
New Commercial Supplement Option

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1738]
Hi Sarah- 

Can you please add the language in the word doc as #3 in this list of Commerical supplements?
https://seedfund.nsf.gov/resources/awardees/supplement/commercial/

I *believe* CAP will stay on the site as #4. I'll let you know if they want that one taken down.

Thank you!
Kelly 
[Technical and Business Assistance web content 3.31.2020.docx](https://github.com/18F/nsf-sbir/files/4411061/Technical.and.Business.Assistance.web.content.3.31.2020.docx)

**Comment by kmonterr** [comment]
Confirmed! We can remove the CAP language (currently listed as #3 on this page).

**Comment by seakhtar** [comment]
Hi Kelly,

Wanted to give you a chance to look it over before publishing:
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/resources/awardees/supplement/commercial/

Let me know if there are any changes you like, or if we're good to go!

**Comment by kmonterr** [comment]
[Document1.docx](https://github.com/18F/nsf-sbir/files/4420358/Document1.docx)

**Comment by kmonterr** [comment]
here's the final, final content! I'm emailing it to you too...THANK YOU!

**Comment by seakhtar** [comment]
Hi @kmonterr -

These last changes have been made and are now on the live site!
