### ISSUE TITLE
Adding Webinar recording to FastLane guide

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1741]
Hi Sarah - 

Do you mind adding a screenshot (and linking it) to the webinar we did on Tuesday?
https://www.youtube.com/watch?v=W87WcFd7jmc

It should go below the DCL link on this page - https://seedfund.nsf.gov/fastlane/covid-19-proposal-instructions/

**Comment by seakhtar** [comment]
Hi @kmonterr -

About how large would you like the player to be? I have it added, but have kept it small for now:

https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/fastlane/covid-19-proposal-instructions/

**Comment by kmonterr** [comment]
Looks great! Thanks, Sarah!
