### ISSUE TITLE
Adding PDF to site

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1743]
Hi Sarah -

Can you please double check my work? I added this PDF to the site, but only the master branch. Does that matter? 
[NSF SBIR COVID support webinar 040320.pdf](https://github.com/18F/nsf-sbir/files/4438000/NSF.SBIR.COVID.support.webinar.040320.pdf)

https://github.com/18F/nsf-sbir/blob/master/assets/files/awardees/NSF%20SBIR%20COVID%20support%20webinar%20040320.pdf

**Comment by seakhtar** [comment]
It shouldn't matter- let me try just rebuilding the branch. I'll get back to you-

**Comment by seakhtar** [comment]
Hi @kmonterr -

The build just went through. Was probably another one of those Federalist hiccups!

**Comment by kmonterr** [comment]
Thank you, Sarah!!
