### ISSUE TITLE
TABA Language fix

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1747]
https://seedfund.nsf.gov/resources/awardees/supplement/commercial/

Hi Sarah -

Can you fix this error on the TABA (part 3) of the supplement page? I

Eligibility should read - "started between August 13, 2018 and July 31, 2020" as noted in the tracked changes here:
[TABA website fix.docx](https://github.com/18F/nsf-sbir/files/4456198/TABA.website.fix.docx)

Thank you!
Kelly

**Comment by seakhtar** [comment]
H @kmonterr ,

Just confirming this has been fixed!

**Comment by kmonterr** [comment]
Thanks, Sarah!
