### ISSUE TITLE
Design idea - Banner

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1753]
Hi Sarah- 

I've received some requests from program directors who are getting a lot of inquiries about whether NSF is open and still operating.

Is there a way to put a banner on the top part of the site (above the navigation perhaps) saying something like - NSF staff continue to work virtually through the COVID-19 crisis. Visit https://www.nsf.gov/news/special_reports/coronavirus/ for updates.

I can share the draft design and language with our staff to make sure they like it!

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -
I wasn't sure how much to make it stand out. Keeping the background white sort of had it blend in with the USA banner, but maybe that's better? I could also adjust the font size/size of the banner itself.

https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/banner/

Just let me know what you'd like to see and I'll adjust it accordingly!

**Comment by kmonterr** [comment]
Hi Sarah - 

Looks great! We had changes to the text then it's good to publish! Here's the new text:

NSF staff is working virtually and continues to review Project Pitches in all areas of technology. Send us your good ideas today!

Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just confirming that I updated the text and it is now live!
