### ISSUE TITLE
Learning technologies webinar

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1760]
Hi Sarah!

Can you please add this last webinar to the site? (In the appropriate calendar order?)

Thank you!
Kelly

Small business funding for learning technologies during and beyond COVID-19
Tuesday, May 5, at 2:00 p.m. ET 

https://nsf2.webex.com/mw3300/mywebex/default.do?nomenu=true&siteurl=nsf2&service=6&rnd=0.09174610644450654&main_url=https%3A%2F%2Fnsf2.webex.com%2Fec3300%2Feventcenter%2Fevent%2FeventAction.do%3FtheAction%3Ddetail%26%26%26EMK%3D4832534b00000002f5b93878470ea0fc3787956e7eafeac771d25d0e112f9ad6c825e89a062dbc0e%26siteurl%3Dnsf2%26confViewID%3D159406055599660343%26encryptTicket%3DSDJTSwAAAAK42hGyqjw9x74bkPtTCvrZycWYJ8Dy-AXJjiX_NmXd8w2%26

**Comment by seakhtar** [comment]
Hi @kmonterr -

This one seemed pretty straightforward so I went ahead and published:
https://seedfund.nsf.gov/events/

**Comment by kmonterr** [comment]
[NSF SBIR Learning Tech COVID DCL5.5.2020.pptx](https://github.com/18F/nsf-sbir/files/4586332/NSF.SBIR.Learning.Tech.COVID.DCL5.5.2020.pptx)

Hi Sarah!

Do you mind please removing the old webinars from the events page and adding this pdf to the site?

Let me know when you have the URL for the file.

Thank you!!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,

The old webinars have been removed, and the link for the presentation is here:

https://seedfund.nsf.gov/assets/files/applicants/NSF.SBIR.Learning.Tech.COVID.DCL5.5.2020.pptx

Let me know if you need anything else!
