### ISSUE TITLE
Update to Step 2 on Apply Page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1770]
Hi @seakhtar 

We’d like to make the following updates to step 2 on our apply page:

Make sure your company meets these eligibility requirements
•	Your company must be a small business (fewer than 500 employees) located in the United States.
•	At least 50% of your company’s equity must be owned by U.S. citizens or permanent residents. **NSF does not permit companies that are majority-owned by multiple venture capital firms, private equity firms, or hedge funds, to participate in SBIR and STTR.**
**•**	All funded work needs to take place in the United States (including work done by consultants and contractors).
•	The project’s principal investigator (tech lead) must be legally employed at least 20 hours a week by the company seeking funding. The PI doesn’t need any advanced degrees.
•	The principal investigator needs to commit to at least one month (173 hours) of work on a funded project per six months of project duration.
For more detailed information, check out **the** Eligibility Guide.

**Comment by seakhtar** [comment]
Hi Kelly- just confirming that this is [currently on the dev branch](https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/apply/) and will be pushed with the rest!
