### ISSUE TITLE
Boot Camp Page Updates

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1771]
Hi Sarah - Can you please update the https://seedfund.nsf.gov/resources/awardees/phase-1/bootcamp/

Thank you!
[SBIR Virtual Boot Camp Website Update.docx](https://github.com/18F/nsf-sbir/files/4622664/SBIR.Virtual.Boot.Camp.Website.Update.docx)

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Just to make sure I get it right, is there a specific part of the page you'd like me to link to the document? It doesn't look like we have something like it already on the page (unless I'm just missing it).

**Comment by kmonterr** [comment]
Hi Sarah!

Thanks for asking. Please just update the content on the page. This doc includes some of the same content and a few changes. (Sadly, they didn't track the changes!) Let me know if you need more info!
Kelly

**Comment by seakhtar** [comment]
Right- should have thought of that, sorry! I'll get it updated!

**Comment by kmonterr** [comment]
no worries! let me know when it's updated! :)

**Comment by seakhtar** [comment]
Hi @kmonter- these changes are [currently in dev](https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/resources/awardees/phase-1/bootcamp/) if you wanted to look them over. On parts of the document, some words were highlighted in blue-- I wasn't sure if that was just for emphasis, so I've used italics for them. If you had something else in mind, let me know. 

I've also updated the [events file](https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/events/) to remove the May 11th one, and to add all the new workshops except the June 1st one (I think we're still missing the registration link for that one).

**Comment by kmonterr** [comment]
Thanks, Sarah!

I like the italics! Can you please remove this line? I should have caught it - "See detailed schedules and dates below." 

Here's the link to the June 1 webinar!

Sure, here is the June 1st Webinar Registration link: 
https://nsf2.webex.com/nsf2/onstage/g.php?MTID=e8a95a9ba2062b325c496ad10fb976fdf

**Comment by seakhtar** [comment]
Thank you! I've made updates to both places, so they should be all set once I push everything to prod.

**Comment by kmonterr** [comment]
Hi @seakhtar - I hope you had a nice weekend! We had a few more changes to the Boot Camp page (changes tracked)!

Do you mind making them today and pushing it dev live?
[SBIR Virtual Boot Camp Website Update v2.docx](https://github.com/18F/nsf-sbir/files/4643678/SBIR.Virtual.Boot.Camp.Website.Update.v2.docx)

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

There are a few other updates in Dev that are ready to be pushed (I sent an email with all of the changes listed but you might not have seen it yet). 
Would you like me to publish anything else, or just the bootcamp page? Just wanted to double-check!
