### ISSUE TITLE
Updating Page 3 in the FastLane guide

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1773]
Hi Sarah -

Please let me know if you have any questions about this request! It's the most urgent of the recent issues (besides Boot Camp updates).

Thank you!
Kelly

[Current and Pending Support Form.pdf](https://github.com/18F/nsf-sbir/files/4627831/Current.and.Pending.Support.Form.pdf)
[biosketch.pdf](https://github.com/18F/nsf-sbir/files/4627832/biosketch.pdf)
[biosketch.pdf](https://github.com/18F/nsf-sbir/files/4627833/biosketch.pdf)
[Current and Pending Support Form.pdf](https://github.com/18F/nsf-sbir/files/4627834/Current.and.Pending.Support.Form.pdf)
[biosketch and current and pending support.docx](https://github.com/18F/nsf-sbir/files/4627858/biosketch.and.current.and.pending.support.docx)

**Comment by seakhtar** [comment]
Hi @kmonterr -

For these, did you want me to upload all the documents or just the PDFs? It doesn't look like there are currently any links to those on the page, so would I just create some out of a relevant phrase on step 16 and 17 (the biographical sketch and current/pending support sections)?

**Comment by kmonterr** [comment]
Hi @seakhtar !

I had a couple more conversations about this new requirement. Can you make the updates (as tracked) in DEV? I'm still waiting for approval from my leadership, but these changes are going into effect before the deadline - which is only about a week away! I'll let you know if they have more changes before we push it live.
[biosketch_NA.pdf](https://github.com/18F/nsf-sbir/files/4667753/biosketch_NA.pdf)
[biosketches web update 5.22.2020 (003).docx](https://github.com/18F/nsf-sbir/files/4667754/biosketches.web.update.5.22.2020.003.docx)


Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

This has been updated! Two questions-

-Did you want the text to be in red, or was that just to highlight what you wanted changed in the document?
-Should I remove the link from the words "upload document" (where I had added it last time), or leave it there as well?

https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/fastlane/form-prep-3/

**Comment by kmonterr** [comment]
Hi Sarah!

Yes! I'd love the bolded item to be in red.

I'd also remove the "upload document" link.

We also got word on Friday that they're pushing the effective date from June to October.

Here's the new text (in red) - 
You must upload the biographical sketches template provided by NSF. (Effective Oct. 1, 2020, FastLane will not allow you to submit your proposal without the NSF-approved biographical sketch document). You can elect to add your senior personnel into the template OR to put “NA” in each section of the template and upload the resumes of senior personnel as supplementary documents.

**Comment by seakhtar** [comment]
Hi @kmonterr - just confirming that this was completed!

**Comment by kmonterr** [comment]
perfect! Thanks, Sarah!
