### ISSUE TITLE
Updated Alumni tool kit PDF

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1780]
Hi Sarah!

Can you please replace the PDF that's on this page (https://seedfund.nsf.gov/resources/awardees/phase-2/ambassador/) - and maybe the PHase II page -- with this PDF? You can delete the old one! I can't believe I didn't replace it earlier!
Kelly 
[Alumni_Awardee Toolkit_5.2020.pdf](https://github.com/18F/nsf-sbir/files/4683904/Alumni_Awardee.Toolkit_5.2020.pdf)

**Comment by seakhtar** [comment]
Hi @kmonterr - 

This file shows up both Phase I and II ambassador pages-- the link has updated in both places. 
Let me know if you need anything else!
