### ISSUE TITLE
New PD - Elizabeth Mirowski

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1786]
Elizabeth (Ela) Mirowski started as an SBIR/STTR program director in May 2020.  Before NSF, Ela was a Founder and CEO of Verellium, a medical device startup. At Verellium she built strong collaborative partnerships across industry, academia, and federal labs to develop novel solutions for clinical imaging that resulted in new products and new market segments. She also worked for High Precision Devices (HPD) where she successfully transferred several technologies into prototypes and commercialized them, creating a standalone, revenue-generating company, QalibreMD, in just three years. As a principal investigator on SBIR grants from various federal agencies, Ela led the program direction including research, engineering, manufacturing, and market development. In addition to these activities, she engaged in fundraising from venture capital and private equity sources. For more than 17 years, Ela worked for and consulted to small businesses managing the development of technologies involving photonics for displays, semiconductor electronics, renewable energies, nanomaterials, and lab-on-chip platforms for evaluating neural growth and biological processes at the single-molecule level. Ela holds a Ph.D. in Physical Chemistry from the University of Colorado, a B.A. in Chemistry from Columbia University, and completed a National Research Council post-doctorate at the National Institute of Standards and Technology.

**Comment by seakhtar** [comment]
Hi @kmonterr - I'll get this added in. Does she have a topic? And is there an email address I should use for her?

**Comment by kmonterr** [comment]
![Ela](https://user-images.githubusercontent.com/26437393/83789958-7569d800-a665-11ea-9333-4f6afd7a6206.jpg)

Her topic is Advanced Manufacturing and email is - emirowsk@nsf.gov

**Comment by seakhtar** [comment]
Hi @kmonterr -

I have this change added to a new branch. I wasn't sure if you wanted to take a look, but here are the pages it will show up. Also- just wanted to double check that her email address doesn't include the "i" at the end of her name: emirowsk@nsf.gov

[Biographies](https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/newPDemirowski/contact/bios/#Elizabeth%20Mirowski) 
[Advanced Manufacturing topic page](https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/newPDemirowski/topics/advanced-manufacturing/)
[Contact](https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/newPDemirowski/contact/) 

Let me know if anything looks off, or if we're set to publish!

**Comment by kmonterr** [comment]
Looks great! Thanks, Sarah. Feel free to publish sometime today! (I agree the missing "I" is weird, but it's right! Thanks for checking:))

**Comment by seakhtar** [comment]
Hi @kmonterr -
Just confirming that this is now live!
