### ISSUE TITLE
Remove the COVID link/ information from the Homepage

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1787]
Hi @seakhtar - 

Can you please remove "Accepting Proposals Addressing COVID-19 – Learn more" on the homepage?

Can you revert it to the regular apply message that was there before?

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

This has been completed! Let me know if you'd like me to change anything:
https://seedfund.nsf.gov/

**Comment by kmonterr** [comment]
Thanks, Sarah!!
