### ISSUE TITLE
About Page change

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1790]
https://seedfund.nsf.gov/about/

Please change the Stamp of Approval language from:
NSF’s stamp of approval: An NSF award is more than just funding. Being selected out of thousands of applicants signals that your technology and expertise have strong technical and commercial merit.

To

NSF’s Merit Review Process: An NSF award is more than just funding. Being selected by experts out of thousands of applicants signals that your technology and expertise have strong technical and commercial merit.

**Comment by seakhtar** [comment]
Hi @kmonterr -

This has been completed and is now on the live site. Have a good weekend!
