### ISSUE TITLE
Updating the COVID-19 Fastlane page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1793]
Hi Sarah - 

Can you please update this page?
https://seedfund.nsf.gov/fastlane/covid-19-proposal-instructions/

With this text? Thank you!
Kelly

[Clarifying COVID-19 Fastlane Process_5.2020 v4.docx](https://github.com/18F/nsf-sbir/files/4711526/Clarifying.COVID-19.Fastlane.Process_5.2020.v4.docx)

**Comment by seakhtar** [comment]
Hi @kmonterr -

Did you want me to remove the link and video at the top of the page as well?

Here is how it looks so far:
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/fastlane/covid-19-proposal-instructions/

**Comment by kmonterr** [comment]
Hi Sarah,

yes! Good catches. Please remove the link, video and last sentence "For more information about COVID-19 proposals, please read our Frequently Asked Questions." The FAQ hasn't cleared yet so we don't have a link! I'll let you know when it is ready and we can add the last line.

Thank you! Please publish :)

Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr - 

Just wanted to confirm that this has been published!

**Comment by kmonterr** [comment]
Thank you!!
