### ISSUE TITLE
Updating the events page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1796]
Hi @seakhtar - 

Can you please remove the old webinars from the events page and add one?

It's another How to Apply webinar on June 19 - 

https://nsf2.webex.com/mw3300/mywebex/default.do?nomenu=true&siteurl=nsf2&service=6&rnd=0.4064626385160114&main_url=https%3A%2F%2Fnsf2.webex.com%2Fec3300%2Feventcenter%2Fevent%2FeventAction.do%3FtheAction%3Ddetail%26%26%26EMK%3D4832534b00000002344e26af50b5734131af3995b8e9418308b475b065219e83293452649d77ea23%26siteurl%3Dnsf2%26confViewID%3D162590954079936021%26encryptTicket%3DSDJTSwAAAAKTKU2q5jDXFMJZoVicqEypuwrCtHIE2_wj5l56Kx9LwQ2%26

**Comment by seakhtar** [comment]
Hi @kmonterr - this update has been made and published!
