### ISSUE TITLE
Updating links to YouTube videos

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1797]
Hi @seakhtar - 

We have new recorded webinars to post on our site - 

5/29 How to Submit webinar recording here: https://www.youtube.com/watch?v=jsWEvht0s6Y&feature=youtu.be. Please let me know if you approve and I will send it out to all registrants via Pardot.

Please find a YouTube link for the latest Project Pitch recording (5/4) here: https://www.youtube.com/watch?v=oVhWWydWWc4&feature=youtu.be

Typically, we have them on the For Applicants page. Do you mind updating the links there? I believe they are somewhere else too...I'm drawing a blank about where were have also posted them in the past. Do you remember?

Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

I've updated the links on the For Applicants page. I found that they were also on the Events page, and have updated them there as well. These changes have been published.

On the For Applicants page, currently only the project pitch webinar shows. Once the site switches to active, the other webinar will show up as well.
