### ISSUE TITLE
Fastlane Guide Update

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1798]
Hi @seakhtar - 

Can you please update the Fastlane Guide (Form prep page 3) as noted in the attachment? I guess they made other changes and are getting a lot of calls prior to the June 4 deadline. If you could do it today they'd
[remove CandP form in Fastlane guide_6.2.2020.docx](https://github.com/18F/nsf-sbir/files/4718786/remove.CandP.form.in.Fastlane.guide_6.2.2020.docx)
 really appreciate it.

Thank you!
Kelly

**Comment by kmonterr** [comment]
Please use this instead! They also had changes to the biosketch page...I guess it's Oct. 5 instead of Oct. 1!

[remove CandP form in Fastlane guide_6.2.2020 MK Edits.docx](https://github.com/18F/nsf-sbir/files/4718867/remove.CandP.form.in.Fastlane.guide_6.2.2020.MK.Edits.docx)

**Comment by kmonterr** [comment]
I sent more changes via email! I'm not clear about what they want with current and pending support...

Also - once they confirm that it's done and the other two changes are made, can you please update the PDF version of the guide?

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,

All of these updates have been made on the site and the PDF, and are now live!
