### ISSUE TITLE
Reminder - June 4 = Window closing date!

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1803]
Hi Sarah - 

Just a reminder that tomorrow, June 4 is the "deadline" or window closing date. I think we just need to update the formula to make it move to the next window on our site, right? 

Can you please make the updates on Friday first thing?

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi Kelly,

Here are our variables. To make sure everything is updated properly, can you let me know what you'd like listed in each?

past_deadline: March 5
next_deadline: June 4
second_deadline: June 5
solicitation_released: December 18, 2019
solicitation_window_1: December 18, 2019 - March 5, 2020
solicitation_window_2: March 6, 2020 - June 4, 2020
solicitation_window_3: June 5, 2020 - September 3, 2020
solicitation_window_4: September 4, 2020 - December 3, 2020

**Comment by kmonterr** [comment]
Hi Sarah - Yes!

I think I did this right. The "past deadline" is just the most recent one, right? And, the second deadline is the day after the next deadline, right?
The names are confusing. Do you mind adding a note to the wiki about it? A couple of definitions would be good! Thank you!
Kelly

past_deadline: June 4
next_deadline: September 3
second_deadline: September 4
solicitation_released: December 18, 2019
solicitation_window_1: December 18, 2019 - March 5, 2020
solicitation_window_2: March 6, 2020 - June 4, 2020
solicitation_window_3: June 5, 2020 - September 3, 2020
solicitation_window_4: September 4, 2020 - December 3, 2020

**Comment by seakhtar** [comment]
Thanks @kmonterr , I think those sound correct!
I'll add a wiki page that illustrates where each phrase is used so you'll have some context clues next time.

**Comment by kmonterr** [comment]
Thanks, Sarah!

**Comment by seakhtar** [comment]
Hi @kmonterr -

I was checking through the pages that use the variables and I thought you might want to take a look to make sure this one still works okay: https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/siteswitch062020/resources/awardees/phase-2/apply/

It mentions "subsequent" submission windows, but lists the previous one as well. Not sure if that is still okay? If not, we could either keep manually removing the passed submission window, or possibly change the wording to be more generic-- let me know what you think!

**Comment by kmonterr** [comment]
Hi Sarah - I agree that it's weird!
I think we should make it more generic. Why don't we just list all of the submission windows again for 2020?

Submission window dates for 2020 are as follows:
December 18, 2019 - March 5, 2020
March 6, 2020 - June 4, 2020
June 5, 2020 - September 3, 2020
September 4, 2020 - December 3, 2020

Otherwise, looks good!
Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Okay, I made that last change and have pushed to production!
