### ISSUE TITLE
Adding link to the COVID-19 Fastlane page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1809]
Hi Sarah!

Can you please add a link to the FAQs on the Fastlane COVID-19 page - https://seedfund.nsf.gov/fastlane/covid-19-proposal-instructions/?

The new sentence is in bold here!
NSF archived the Dear Colleague Letter (DCL) on the “Request for SBIR/STTR Phase I Proposals Addressing COVID-19” (NSF 20-065). **For more information, please read our Frequently Asked Questions [https://www.nsf.gov/pubs/2020/nsf20093/nsf20093.jsp].**

THank you!

**Comment by seakhtar** [comment]
Hi @kmonterr -

I went ahead and pushed this one with the PD update. It just occurred to me that you might have wanted the sentence to display as bolded? If so, let me know and I'll update it!

https://seedfund.nsf.gov/fastlane/covid-19-proposal-instructions/

**Comment by kmonterr** [comment]
Looks good as is! Thanks, Sarah!
