### ISSUE TITLE
Removing old language

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1813]
Hi Sarah - 

We discovered that our website (Apply page I think) still has this language: 

Learn about our Phase I application timeline, how to prepare your Project Pitch, and what to expect once you submit your Project Pitch or full proposal. **After a brief pause, new Phase I SBIR and STTR solicitations are expected in the coming weeks.**

Can you please remove the bolded line?
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr - just confirming that this has been taken care of!
