### ISSUE TITLE
changing the link to the email sign up form - 

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1816]
Link to the "Sign up form" https://seedfund.nsf.gov/

instead of the pardot URL - https://go.pardot.com/l/392062/2019-10-29/89hhbl

Please use:
https://go.nsf.gov/l/392062/2019-10-29/89hhbl

Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr --

This has been taken care of!
