### ISSUE TITLE
Staff Changes

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1819]
Hi Sarah - 

Gracie Narcho's last day is today - sad!!! - can you please remove her from the Bios page?
https://seedfund.nsf.gov/contact/bios/

Also, the Senate confirmed the future NSF director, Sethuraman Panchanathan. We'll need to update the https://seedfund.nsf.gov/press/ page as soon as its signed by the president and we have a link to his bio. Probably early next week??

Thank you!
Kelly

**Comment by kmonterr** [comment]
Hi Sarah - Dr. Panch is officially the director - https://nsf.gov/staff/staff_bio.jsp?lan=spanchan&org=EF&from_org=EF

Can you please make the updates? Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Sorry, this one got lost in my inbox. I'll get this updated now!

**Comment by seakhtar** [comment]
Hi @kmonterr -
Just to double-check, Sethuraman Panchanathan will replace Cordova, right? So it would look like this: https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/press/

Let me know if I misunderstood!

**Comment by kmonterr** [comment]
Looks good! Thanks, Sarah! Can you also remove the most recent webinar (6/19) when you're in there? Thank you!
Kelly

**Comment by seakhtar** [comment]
Okay, confirming that all three of those changes have been made and are now live!

**Comment by kmonterr** [comment]
Thank you!
