### ISSUE TITLE
Showcase Page Changes

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1822]
Hi Sarah - 

Can you please make changes to the Showcase Page: https://seedfund.nsf.gov/showcase/
Please keep what’s there and keep adding content to the top of the page, pushing the older stuff down.

Also, is it possible to fix the video container for each video on the page? I'd love to get rid of the tiny logo and video name in the video roll and remove the black bars above and below the image in the video thumbnails on the page,? it looks like it might be hardcoded as you bring videos in from YouTube?

Here are the new videos in the order we would like them to appear. Please pull the text from YouTube per usual: 
Kela Health - https://www.youtube.com/watch?v=w6oYYZFhzeE&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=75&t=1s
Opus 12 - https://www.youtube.com/watch?v=L-wLMGI6v9M&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=3&t=13s
Kinetic - https://www.youtube.com/watch?v=1UAXId9owiY&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=11&t=0s
Beta Hatch – https://www.youtube.com/watch?v=DRzAudR65tI&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=78&t=3s
Vital - https://www.youtube.com/watch?v=iKqpWy_9KSE&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=8&t=0s
Path Ex - https://www.youtube.com/watch?v=fnv-hdTCSPM&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=79&t=0s
Spherical Block - https://www.youtube.com/watch?v=LcDj-_89Tcw&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=12&t=0s
Dimensional Energy - https://www.youtube.com/watch?v=SlVRqx6w3rQ&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=77&t=2s
Embr Labs - https://www.youtube.com/watch?v=BqzF0oIAXUI&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=76&t=9s

**Comment by seakhtar** [comment]
Hi @kmonterr -

I'll get started on creating a new branch with these. For the videos, a lot of how they are embedded is controlled by youtube but there might be a way to makes some adjustments-- I'll look into it!

**Comment by seakhtar** [comment]
Hi @kmonterr -

The new videos are up on [this test branch](https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/showcaseUpdate072020/showcase/), if you'd like to take a look! A couple notes--

1. I looked into removing the title at the top of the videos, but Youtube insists they are "an important part of YouTube's core user experience", so unfortunately, they don't give you the option to disable them.   🙄

2. I attempted to remove the black bars-- they should be gone on the full-size desktop view, but they still appear as the window is shrunk. It has something to do with the way the CSS handles the video's proportions-- hopefully it's at least a little better than before?

3. It looks like the link in [Spherical Block's video](https://www.youtube.com/watch?v=LcDj-_89Tcw&list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb&index=12&t=0s) might have a typo in it: http://www.sphericalblock.info/ 
We might want to hold off on publishing until it's updated.

I think that's everything-- let me know if you'd like me to make any changes!

**Comment by kmonterr** [comment]
Hi Sarah!

Here are a few more things:

1. Can you please update the text on the page as noted in the attachment? (For the new videos).
2. Can you please update the name of Bay Labs to Caption Health? See the bolded changes here: 
**Caption Health (formerly known as Bay Labs)** uses artificial intelligence to help medical professionals perform and interpret ultrasounds. To learn more visit: *https://captionhealth.com/*
3. Is there a way to update the styles so not all of the videos are against a dark grey background? With so many videos in a row it's a little hard on the eyes. Maybe a white background would help?
4. I have another video to add later this week. I'll send it once it's posted! It'll go a the top. (re:3D is the company).

Thank you!
Kelly 
[Showcase updates 7.2020.docx](https://github.com/18F/nsf-sbir/files/4955399/Showcase.updates.7.2020.docx)

**Comment by seakhtar** [comment]
Hi Kelly,

How does this look? https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/showcaseUpdate072020/showcase/

Let me know if you'd like me to make any further adjustments!

**Comment by kmonterr** [comment]
Hi Sarah! It looks really good!!

I am noticing my typos! - ugh! I'm so sorry! I found these two. Once you change them, please publish! Thanks SO much!
Kelly

Spherical Block - Can you please add a comma after affordable?
Spherical Block is using concreate masonry construction to build affordable**,** efficient homes. 
 
Living Ink - Can you please remove the bolded part of this sentence?
Its sustainable algae products could replace ink made from petroleum**-based ink**.

**Comment by seakhtar** [comment]
No worries! Easy to fix :) Everything has been published and is now live!

**Comment by kmonterr** [comment]
Thanks, Sarah!!
