### ISSUE TITLE
Adding new how to apply webinars to the events page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1823]
Hi Sarah!

Can you please add the following How to Apply webinars to the events page and remove the old ones?

I'll send more Project Pitch webinar dates early next week too.

Thank you!
Kelly 

How to Submit an SBIR/STTR Proposal | 8-21-20 | 2:00pm | https://nsf2.webex.com/nsf2/onstage/g.php?MTID=e64bc0b94fbe79dea4405bb88456bc3dc

How to Submit an SBIR/STTR Proposal | 9-18-20 | 2:00pm | https://nsf2.webex.com/nsf2/onstage/g.php?MTID=e2720a22e8805f07f558ca1bbe3a84e41

How to Submit an SBIR/STTR Proposal | 10-16-20 | 2:00pm | https://nsf2.webex.com/nsf2/onstage/g.php?MTID=e998b73774a3174150f8be5081c00a3db

How to Submit an SBIR/STTR Proposal | 11-20-20 | 2:00pm | https://nsf2.webex.com/nsf2/onstage/g.php?MTID=ebd2c865c6764e9e43fe8a7ec134ef787

How To Submit an SBIR/STTR Proposal | 12-18-20 | 2:00pm | https://nsf2.webex.com/nsf2/onstage/g.php?MTID=ef60578d8bea896fdeae5d312b840e741

**Comment by seakhtar** [comment]
Just confirming that I saw this and will get started!

**Comment by seakhtar** [comment]
Hi @kmonterr -

I have this up on a test branch: https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/newWebinars072020/events/

It looks like I might need to remove the event on the 17th before publishing. Otherwise, if it looks okay, let me know and I'll push it to prod!

**Comment by kmonterr** [comment]
Yes! Please remove 7/17 and publish! Thanks, Sarah!!!

**Comment by seakhtar** [comment]
Hi @kmonterr -

Forgot to add a confirmation-- they've been published!

**Comment by kmonterr** [comment]
Thanks, Sarah!  I have a few more event updates!

Can you please check the Annual Events on Dev to make sure I did it right?

Can you please add the upcoming "Start Your Project Pitch" webinars in chronological order on the events page? (See below).

Thank you!!
Kelly 


Start Your Project Pitch | 7-31-20 2:00pm | https://nsf2.webex.com/nsf2/onstage/g.php?MTID=eb175813222f482443c9415eb3c783528
Start Your Project Pitch | 8-28-20 2:00pm | https://nsf2.webex.com/nsf2/onstage/g.php?MTID=ec99f3643e4a43d6331a3f4cb9fbc28b4
Start Your Project Pitch | 9-25-20 2:00pm | https://nsf2.webex.com/nsf2/onstage/g.php?MTID=e4d5985ba9688c4122d8d3543099e9020
Start Your Project Pitch | 10-30-20 2:00pm | https://nsf2.webex.com/nsf2/onstage/g.php?MTID=ea10ba4aa7fa42972233a7cd30080f059
Start Your Project Pitch | 11-13-20 2:00pm | https://nsf2.webex.com/nsf2/onstage/g.php?MTID=eb4657ccdb8d471cbf6d4c3b6ce6eb851
