### ISSUE TITLE
Update Phase II apply page!

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1838]
Can you please update this page with the bolded text below? 

Thank you!

https://seedfund.nsf.gov/resources/awardees/phase-2/apply/
Submission info
•	A company may submit a Phase II proposal anytime between six (6) months and two years (24 months) after the start date of the relevant Phase I award. The start date can be found on your Phase I award letter. *To extend flexibility to small businesses during the COVID-19 crisis, all Phase I companies that received their Phase I with an award start date between March 15, 2018 and December 3, 2018 will have until December 3, 2020 to submit an SBIR/STTR Phase II proposal. (Phase I companies that received their Phase I award after December 3, 2018, are not eligible for this extension).*

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just wanted to confirm that this was added to the new branch and will go live when it's published:
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/updates7272020/press/adcom/
