### ISSUE TITLE
AdCom pages update

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1839]
Hi Sarah!

Please add Chris Moran (in alphabetical order) to the AdCom Page - use their shortened names on the main page "Chris"

Chris Hewitt's photo is in the doc.
[Chris Hewitt Bio July 2020.docx](https://github.com/18F/nsf-sbir/files/4974146/Chris.Hewitt.Bio.July.2020.docx)

![Chris Moran](https://user-images.githubusercontent.com/26437393/88432815-f07c7e80-cdca-11ea-9611-a2c477ef1488.jpg)

Here's their bios. 
[Chris moran.docx](https://github.com/18F/nsf-sbir/files/4974136/Chris.moran.docx)

**Comment by kmonterr** [comment]
There might be three more coming this weekend or Monday morning. I'm confirming!

**Comment by kmonterr** [comment]
Hi Sarah!

Ok, a few more things.

1.	The word “Advisory” should be removed - I removed it in Dev. Can you make sure that it's gone when you merge your changes? https://github.com/18F/nsf-sbir/edit/dev/pages/adcom.md. 

2.	Please remove the bios and headshots for: 

- Skip Rung 
- Ann Savoca
- William Lockwood-Benet 

3.	We'll have two more people's bios/headshots coming today. Can you please add their names to the main page, Paul's headshot and add their titles to the bios page? It will be a placeholder just in case they don't send their official information today:
- Ajoy Vase, Senior Program Manager, Chan Zuckerberg Initiative
- Paul Fischer, Corporate Development Leader at W. L. Gore & Associates 
![Paul Fischer](https://user-images.githubusercontent.com/26437393/88536536-f8f6d400-cfd9-11ea-875e-71ffce8d433a.jpeg)

**Comment by kmonterr** [comment]
Here's Paul's bio:

Paul Fischer leads Corporate Development at W. L. Gore & Associates, Inc.  In this role, he focuses on external growth opportunities through acquisitions and collaborative partnership. Prior to this commitment, Paul led Gore’s Core Technology division responsible for research and development in polymerization and processing of fluoroploymers as well as manufacturing of fluoropolymer intermediates within the company.  In addition to his corporate development role, he serves on the Board of Managers of Avobis Bio LLC an early stage Stem Cell biologics company and on the Board of Directors of Shanghai Gore 3f, a fluoropolymer research and polymer manufacturing joint venture facility in China.  Paul is also member of Gore’s intellectual property committee, innovation center of excellence, and a fiduciary on Gore’s associate stock ownership plan. He has worked for Gore for 35 years in two separate stints and has worked at ICI, 3M, and led a venture-backed startup in the display industry.  He holds a B.S. in Chemical Engineering from the University of Rochester.

**Comment by kmonterr** [comment]
And - Here's Ajoy - 

![Ajoy Vase](https://user-images.githubusercontent.com/26437393/88568574-2efe7d00-d007-11ea-8fad-8b95196cdff0.jpg)

Ajoy Vase is a Senior Portfolio Manager at the Chan Zuckerberg Initiative. He has spent the past few years building innovation ecosystems for learning that bridge research from cognitive and brain sciences, community practice and technology development.  His path to this work began in the classroom as a high school math teacher, followed by stints in edtech and school turnaround management. Prior to joining the Chan Zuckerberg team, he also spent time advising healthcare, technology, and social impact organizations on growth and innovation strategy as a management consultant with Bain & Company in San Francisco.  He has degrees in physics, applied mathematics, education and business from Pomona, Stanford and Berkeley.

**Comment by seakhtar** [comment]
Hi @kmonterr -

Here is the updated page! Let me know if anything looks off. Otherwise, I'll publish on your say-so!
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/updates7272020/press/adcom/

**Comment by kmonterr** [comment]
Looks good! Please publish!

**Comment by seakhtar** [comment]
Hi @kmonterr - it's now live!

**Comment by kmonterr** [comment]
Hi Sarah - 

I've also been asked to change the URLs. 

Can we update it to be - 
https://seedfund.nsf.gov/press/adcom/ -> https://seedfund.nsf.gov/sbir-sttr-subcommittee
https://seedfund.nsf.gov/press/adcom-bios -> https://seedfund.nsf.gov/sbir-sttr-subcommittee-bios

I think it's only linked from the for press page: 
https://seedfund.nsf.gov/press/

I also made a change in the For Press text. Can you please make sure it's in there too? 
https://github.com/18F/nsf-sbir/blob/dev/pages/press.md

Thank you!!
Kelly

**Comment by kmonterr** [comment]
can we also redirect any use of the old links to the new pages? 
https://seedfund.nsf.gov/press/adcom-bios 

thank you so much for your speedy help with this today!

**Comment by seakhtar** [comment]
Sure-- I think you're right that the only link is from the press page, but I'll double check. Otherwise, I think I just need to update the links to the biographies page from the main Adcom page. 

I'll send the test branch along in a moment!

**Comment by seakhtar** [comment]
Okay, how does this look?
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/sbir-sttr-subcommittee/
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/sbir-sttr-subcommittee-bios/

I did a site search, but I couldn't find any other mention of the page, or any other instances of the old links (besides the press page). I made all the updates in DEV, so as long as you made your "for press" update there, it should show up okay!

**Comment by kmonterr** [comment]
Looks great, Sarah! Publish away!

Thanks again for your help today!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr --

Just confirming that this is now live. Have a good evening!

**Comment by kmonterr** [comment]
Thanks again, Sarah!
