### ISSUE TITLE
Updated VRS Supplement Link

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1850]
Hi Sarah - 

Can you please update the link to the VRS supplement on this page?
https://seedfund.nsf.gov/resources/awardees/supplement/educational/

Here's the new link: https://www.nsf.gov/pubs/2020/nsf20111/nsf20111.jsp

I bolded the link that needs to be updated below. 

Thank you!!

Veterans Research (VRS)
Funding support to enable veteran students, pre-college STEM teachers, and/or community college faculty to participate in active NSF grants.
Max funding: $10,000 per veteran
Deadline: Rolling submission; does not extend award duration
Recruiting tip: Many community colleges and universities have a veterans office or resource team. You can use this recruiting template to reach out.
*More Information*
Proposal / Budget submission instructions

**Comment by seakhtar** [comment]
Hi @kmonterr -
This has been updated and is now live!
