### ISSUE TITLE
Events opening in a separate window/tab

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1855]
Hi Sarah!

Would it be possible to have the WebEx registration links on our events page open in a separate tab/window? (tab is preferred). Apparently, there's not a way to easily go back to the events page once you click on them!

Let me know what you think!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -
Okay, they should be opening into new tabs now! 

Meant to ask- would you like me to go ahead and remove the Jul 31 webinar?

**Comment by kmonterr** [comment]
Great! Thanks so much, Sarah!

Yes! That'd be wonderful - re: removing 7/31.

Thank you!!
