### ISSUE TITLE
New program director - Diane 

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1860]
Hi Sarah - 

I'm waiting on a headshot (hopefully next week) and clarification about how to divide topics/subtopics, but we have a new PD. Here's her bio and topics if you want to think through how to add her topics online!
kelly 

Diane Hickey joined NSF as an SBIR/STTR program director in August 2020. She has extensive experience in multiple technical fields and early-stage deep technology ventures. Diane founded the Diamond Chameleon Group to support marketing for scientists and engineers, and then grew a broad team providing commercialization services to SBIR grantees and related startups.  Her industrial experience includes service at Accenture (Andersen Consulting), and her clients included Seagate (semiconductor), Southern Company (energy) and Sonoco (industrial products). Diane has also worked on strategy at an MIT spinoff that went public, and served as sales and marketing lead for Advanced Diamond Technologies (ADT), a thin-film CVD diamond Argonne National Lab spinoff, where she helped the company transition from grant support to commercial sustainability. Diane has served as a commercialization advisor to 40+ SBIR awardees of NASA, NOAA, NIH, DOE and NSF.  Prior to and while earning her doctorate, Diane consulted on science education and pursued coursework in science communication. She holds a B.S. in Chemical Engineering from Auburn University, and an M.S. and Ph.D. in Materials Science and Engineering from the University of Florida.

For web team: Diane lead several SBIR/STTR topics and subtopics, including: instrumentation/hardware; coatings; and education/learning technologies. Let me ask how we will handle subtopics as it's not easy with our current web structure!

**Comment by seakhtar** [comment]
Hi @kmonterr -

I'll get a new branch started so we can start getting things in place while we wait for the headshot!

**Comment by kmonterr** [comment]
![Diane Hickey](https://user-images.githubusercontent.com/26437393/89894542-3d709b00-dba8-11ea-87e8-e68f2a491ed7.jpg)
Here's Diane!

Can you please send the DEV link? I'll share it with staff for approval!
Thank you, Sarah!

**Comment by seakhtar** [comment]
Hi @kmonterr ,

The new branch is at https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/hickey/contact/

- I've listed her email address as dHickey@nsf.gov.
- Since you list her topics as  instrumentation/hardware; coatings; and education/learning technologies, I tagged her like this on the contact page: 

Education technologies (AI)
Coatings and Surface Modifications (AM)
Instrumentation and Hardware Systems (IH)

Let me know if I got those wrong, or if you'd like me to list the topic name instead!

**Comment by kmonterr** [comment]
Hi Sarah!

I'm getting confirmation. 

In the meantime, can you please mock up a second version with just Instrumentation and Hardware listed on the Contact page for Diane? (You can remove the two subtopics).

I'll be out for a few weeks - returning on 8/31. I'll tell Cecile to let you know what they've decided!

Thank you!!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just in case you need it, the alternate mock-up is here! 
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/hickeyv2/contact/

**Comment by kmonterr** [comment]
Thanks, Sarah! We'll keep you posted!

**Comment by kmonterr** [comment]
Hi Sarah! Diane had changes to her bio. Can you please use this version instead?


Diane Hickey joined NSF as an SBIR/STTR program director in August 2020. She has extensive experience in multiple technical fields and early-stage deep technology ventures. Diane founded the Diamond Chameleon Group and grew a broad team providing commercialization services to more than 40 SBIR awardees and deep technology startups with funding across government agencies. Diane began her career at Accenture, implementing enterprise-wide systems in utility and chemical corporations. She then joined C-Bridge Internet Solutions, an MIT-based startup that provided technologies to connect corporate back-end systems to front-end users; the company went public in 1999, and merged with Excelon in 2000 and Progress Software Corp (PRGS) in 2004. After completing her Ph.D., Diane joined Advanced Diamond Technologies (ADT), a startup spun out of Argonne National Laboratory, she helped the company transition from grant support to commercial sustainability.  Diane has held life-long roles in STEM education, including the NSF Young Scholars program, participation in the NSF Nanotechnology Informal Science Education network, and as a Sisters4Science mentor. She has also supported science education startups, served as the school and homeschool liaison for the Tampa’s Children’s Museum and has taught for Kaplan, Inc. Diane consulted on science education and pursued graduate coursework at the University of Florida’s College of Journalism and Communications. Diane holds a B.S. in Chemical Engineering from Auburn University, and an M.S. and Ph.D. in Materials Science and Engineering from the University of Florida.

**Comment by seakhtar** [comment]
Hi @kmonterr -

Sure-- once I get the test branch set up, I'll send it along!

**Comment by seakhtar** [comment]
Okay, here is the updated branch-- I'll keep an eye out for the new photo (if there ends up being one!)
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/hickeyv2/contact/

**Comment by kmonterr** [comment]
Looks good! Please publish!

**Comment by seakhtar** [comment]
Sure- it's been published!

**Comment by kmonterr** [comment]
Hi Sarah - 
One last tiny change - 
Remove the word “front-end” from this sentence: 
“She then joined C-Bridge Internet Solutions, an MIT-based startup that provided technologies to connect corporate back-end systems to **front-end** users; the company went public in 1999,”

**Comment by seakhtar** [comment]
This was pushed with the other updates today and is now on the live site!
