### ISSUE TITLE
Another Video to Showcase

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1861]
Hi Sarah - 

Can you please add this video to the Showcase page? It can go at the top.

https://www.youtube.com/watch?v=rnUx5iRdHWk&feature=youtu.be

Here's the text: 
Learning math using music and psychology – Muzology
Muzology is developing a learning platform to help students learn math. Grounded in psychology, Muzology’s platform helps students learn algebra concepts with music.
To learn more visit: https://www.muzology.com/.

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just confirming that this has been completed and is now live!
https://seedfund.nsf.gov/showcase/
