### ISSUE TITLE
New Reviewer Page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1862]
Hi SArah!

Can you please make this page the main page/landing page for the review section: https://seedfund.nsf.gov/resources/review/

[Serve as a reviewer page combined edits_clean 8.14.2020v4 cjg.docx](https://github.com/18F/nsf-sbir/files/5074683/Serve.as.a.reviewer.page.combined.edits_clean.8.14.2020v4.cjg.docx).

I'd also like to link to it from the bottom of our About Page and our Contact Us page - https://seedfund.nsf.gov/contact/

Perhaps with text like - Learn more by serving as an NSF reviewer. (with Learn more linked to this page).

Does that make sense?

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just wanted to confirm I saw this and will work on getting it completed!

**Comment by seakhtar** [comment]
Hi @kmonterr -

Did you mean for this page to replace the current [https://seedfund.nsf.gov/resources/review/](https://seedfund.nsf.gov/resources/review/) page, or will this be a separate page that just uses that link? If so, would you like me to create a new link for the "Review Process" page that is currently there?

**Comment by kmonterr** [comment]
Hi Sarah!

Sorry for the delay! yes! Please make the new content the landing page and the existing "review process" content just keep it on the tab on the left. It's still needed on the site, but just not on the main page. does that make sense?

Thank you! I hope you're well!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr , welcome back!

That makes sense! For the About page, would you like the Learn more... line to go above the "About NSF" section?  

And on the Contact page, would you like it to go in the header text (i.e. a new line after Call our help line...), or would you prefer it a few lines after Ben's photo?

**Comment by kmonterr** [comment]
Hi Sarah!

Above the "About NSF" section is perfect on the About Page.

For the Contact Us page a few lines after Ben's photo would work well! Thanks for asking! I'm sorry I spaced on telling you where to put it!

Have a great long weekend! :)
Kelly

**Comment by seakhtar** [comment]
No problem! Just wanted to make sure things look how you'd like :)
Here is the test branch I have up: https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/reviewerLanding/resources/review/

**Comment by seakhtar** [comment]
Hi @kmonterr -

Wasn't sure if you might have missed this-- thought you might want to look it over before publishing!

**Comment by kmonterr** [comment]
Looks good! please publish!
