### ISSUE TITLE
New Solicitation Window Updates

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1866]
Hi Sarah - 

Can you please update the website with the new solicitation window?

It's September 4 - December 3.

I know it's on this page. Can you please make sure to change it elsewhere too? 
https://seedfund.nsf.gov/fastlane/

Thank you!
Kelly

**Comment by seakhtar** [comment]
Will do! Just to make sure I have it right, the two dates mentioned below-
![image](https://user-images.githubusercontent.com/28659251/92501343-664a7700-f1cc-11ea-9e25-71f7ab71f7c7.png)

Should be December 3rd, and  December 4th? Wanted to check as I know we don't really have a Dec 4 window listed anywhere (we have a list of submission windows on [step 4 of the apply page](https://seedfund.nsf.gov/apply/)), so if I need to just remove that line instead, let me know!

**Comment by kmonterr** [comment]
Hi Sarah!

Please remove that sentence..(A new submission window will open ....)we don't know when the next solicitation window will open after Dec. 3!

Thank you and good catch!
kelly

**Comment by seakhtar** [comment]
Hi @kmonterr , 
This was completed and is now live!
