### ISSUE TITLE
New video for Showcase

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1871]
Shape-shifting robots provide real-time data in disasters - Squishy Robotics
Squishy Robotics is developing mobile sensor robots for use in disaster rescue, remote monitoring, and space exploration.
To learn more visit: https://squishy-robotics.com/.

Here's the link to the video - 
https://youtu.be/RcPFQJorwpc

please add it to the top!

**Comment by kmonterr** [comment]
I forgot the thumbnail...ack. Give me a day or two! Thank you!!

**Comment by kmonterr** [comment]
It's ready! Thanks for putting it up!
Kelly

**Comment by seakhtar** [comment]
This has been [posted](https://seedfund.nsf.gov/showcase/)-- let me know if you'd like me to make any changes!
