### ISSUE TITLE
Updating the Biosketch & Current and Pending support Fastlane info

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1885]
NSF made updates to the biosketches and current/pending support requirements.
 https://seedfund.nsf.gov/fastlane/form-prep-3/

We are waiting for final policy sign-off, but can you please create a dev branch with an update the Fastlane guide for the biosketch and current and pending support sections? The parts that involve screenshots and how to upload the documents are still correct.

Thank you!
Kelly 

Can you please replace the Biosketch information:
"Type/Upload the “Biographical Sketch” in the below text box. When this section is completed, click “Go Back” to return to the “Form Preparation” screen.

NSF is providing a fillable PDF for use in preparation of the biographical sketch. You can download it from this page, complete the form, and upload it as part of your proposal via FastLane. (If you elect to add resumes as supplementary documents, please remember to add “NA” to every field in this PDF and upload it as it is required for submission."

with this instead?

•	Download the NSF-approved fillable Biographical Sketch PDF for each individual designated as Principal Investigator (PI), co-PI or Senior Personnel.

•	Complete the “Name”, “Title” and “Institution” (Organization) fields at the top of each form.

•	If you want to continue using the PDF, please complete the remaining fields and upload into the Biographical Sketches section of the proposal.

•	If you do not want to continue using this new format, you must enter “N/A” into the remaining fields of this PDF and upload into the “Biographical Sketches” section of the proposal. If you choose this option, you must upload resumes for the PI, co-PI and all Senior Personnel in Supplementary Documents in the format outlined in the relevant NSF SBIR/STTR solicitation (under the “Biographical Sketches” section of Proposal Preparation). If you fail to include the required resumes as Supplemental Documents, your proposal may be Returned Without Review.  

•	**Proposals without the NSF-approved PDF form (completed or not) will not be able to be submitted in Fastlane.**

please also replace the language for Current and Pending Support:

•	Download the NSF-approved fillable Current and Pending Support for each individual designated as PI, co-PI or Senior Personnel.
•	Complete the “PI/co-PI/Senior Personnel Name” field at the top of each form.
•	If you want to continue using the PDF, please complete the remaining fields and upload into the Current and Pending Support section of the proposal.
•	If you do not want to continue using this new format, then you must enter “N/A” into the remaining fields of this PDF and upload into the “Current and Pending Support” section of the proposal. You must upload the individual statements regarding Current and Pending Support for the PI, co-PI and all Senior Personnel in the in Supplementary Documents and correct format as outlined in the relevant NSF SBIR/STTR solicitation (under the “Current and Pending Support” section of Proposal Preparation).
•	Proposals without an uploaded the NSF-approved PDF form (completed or not) will not be able to submit their proposal.

**Comment by kmonterr** [comment]
[BioSketch and Current Pending Support SBIR-STTR Guidance_v4_for website.docx](https://github.com/18F/nsf-sbir/files/5329758/BioSketch.and.Current.Pending.Support.SBIR-STTR.Guidance_v4_for.website.docx)

Hi Sarah! Here's the final version. Can you please mock it up and share a link? 

Thank you!
Kelly

**Comment by kmonterr** [comment]
Hi Sarah! Just kidding. here's the final, final version. Please let me know if you have any questions!

**Comment by kmonterr** [comment]
Effective October 5, 2020, NSF requires all NSF proposals (including SBIR/STTR proposals) to include Biographical Sketches using NSF-approved formats.  NSF will only accept PDFs using the fillable-PDFs created by NSF or the same formats produced using SciENcv.  Users will be prevented from uploading non-compliant Biographical Sketches and NSF prevents submission of proposals without these documents. For more information, review the guidance in the Proposal & Award Policies & Procedures Guide (PAPPG) (NSF 20-1), and the Policy Office website.

As you prepare your SBIR or STTR proposal, and if you do not already use SciENcv, we recommend following the step-by-step guidance as outlined below. 

Biographical Sketches

•	Download the NSF-approved fillable Biographical Sketch PDF for each individual designated as Principal Investigator (PI), co-PI or Senior Personnel.
•	Complete the “Name”, “Title” and “Institution” (Organization) fields at the top of each form.
•	If you want to continue using the PDF, please complete the remaining fields and upload into the Biographical Sketches section of the proposal.
•	If you do not want to continue using this new format, you must enter “N/A” into the remaining fields of this PDF and upload into the “Biographical Sketches” section of the proposal. If you choose this option, you must upload resumes for the PI, co-PI and all Senior Personnel in Supplementary Documents in the format outlined in the relevant NSF SBIR/STTR solicitation (under the “Biographical Sketches” section of Proposal Preparation).
•	Proposals without the NSF-approved PDF format (completed or not) will not be able to be submitted in FastLane.
•	If you do not use the NSF-approved format for Biographical Sketches and fail to include the required resumes as Supplemental Documents, your proposal will be Returned Without Review.  

If you are preparing your SBIR or STTR proposal and already use SciENcv, we recommend following the step-by-step guidance as outlined below.


•	Navigate to the SciENcv site: https://www.ncbi.nlm.nih.gov/sciencv/ and follow the directions for preparation of the NSF Biographical sketch format.
•	Export a PDF of the Biographical sketch for each PI/co-PI and upload the files into FastLane.  Proposals without the NSF-approved PDF format will not be able to be submitted in FastLane.
•	Reminder: If you do not use the NSF-approved format for Biographical Sketches and fail to include the required resumes as Supplemental Documents, your proposal will be Returned Without Review.  





Effective October 5, 2020, NSF will require all NSF proposals (including SBIR/STTR proposals) to include Current and Pending Support using NSF-approved formats.  NSF will only accept PDFs using the fillable-PDFs created by NSF or the same formats produced using SciENcv.  Users will be prevented from uploading non-compliant Biographical Sketches and NSF prevents submission of proposals without these documents. For more information, review the guidance in the Proposal & Award Policies & Procedures Guide (PAPPG) (NSF 20-1), and the Policy Office website.

Current and Pending Support

•	Download the NSF-approved fillable Current and Pending Support for each individual designated as PI, co-PI or Senior Personnel.
•	Complete the “PI/co-PI/Senior Personnel Name” field at the top of each form.
•	If you want to continue using the PDF, please complete the remaining fields and upload into the Current and Pending Support section of the proposal.
•	If you do not want to continue using this new format, then you must enter “N/A” into the remaining fields of this PDF and upload into the “Current and Pending Support” section of the proposal. You must upload the individual statements regarding Current and Pending Support for the PI, co-PI and all Senior Personnel in Supplementary Documents in the format outlined in the relevant NSF SBIR/STTR solicitation (under the “Current and Pending Support” section of Proposal Preparation).
•	Proposals that do not include the NSF-approved PDF format (completed or not) will be prevented from submission.
•	If you do not use the NSF-approved format for the Current and Pending Support documents and fail to include the required statements noted in #4 above as Supplemental Documents, your proposal will be Returned Without Review.  


Current and Pending Support

•	Navigate to the SciENcv site: https://www.ncbi.nlm.nih.gov/sciencv/ and follow the directions for preparation of the NSF Current and Pending Support format.
•	Export a PDF of the Current and Pending Support format for each PI/co-PI and upload the files into FastLane.  Proposals without the NSF-approved PDF format will not be able to be submitted in FastLane.
•	Reminder: If you do not use the NSF-approved format for the Current and Pending Support documents and fail to include the required statements noted in #4 above as Supplemental Documents, your proposal will be Returned Without Review.

**Comment by kmonterr** [comment]
My Word is failing and I have to restart, hence adding the updated text above. Please use the links in the other document since they didn't copy! Thank you!

**Comment by kmonterr** [comment]
[Final Biosketch and current.pending support web update 10.6.2020.docx](https://github.com/18F/nsf-sbir/files/5334507/Final.Biosketch.and.current.pending.support.web.update.10.6.2020.docx)
Here's the final doc with the links.

**Comment by seakhtar** [comment]
Hi @kmonterr -

I have all the information on the word doc now up on the [dev branch](https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/fastlane/form-prep-3/). If anything looks off or needs updating, just let me know!

(Just a quick note-- all the sections of the Fastlane Guide are numbered, so I kept the 16/17 in so as not to break continuity. ) 

-Sarah

**Comment by seakhtar** [comment]
Sure! I've placed the images back in where I thought they might fit best (though I can shift them around if I've gotten it wrong). I also included some of the original text that explained what was going on in each picture, but let me know if that needs to be removed/updated!

https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/fastlane/form-prep-3/

**Comment by kmonterr** [comment]
Looks great! please publish! Thank you.

**Comment by seakhtar** [comment]
Hi @kmonterr -

Forgot to confirm that this was published. I've also updated the Fastlane PDF to reflect the changes!
