### ISSUE TITLE
Project Pitch submission form error

### ISSUE THREAD

**Issue by jpom** [18F/nsf-sbir#1894]
## Expected Behavior
Submitting a Response to Request for More Information. From an email from Farzin Samadani:

Please use the link below to respond to the reasons provided in this email as to why your Project Pitch submission requires further clarification or is incomplete. This link will route you to a read-only copy of your Project Pitch submission. All information submitted with your original Pitch will be available for you to review through this link. Below this information, a text box will be provided at the bottom of the second page (labelled as field #17 – “Response to Request for More Information”). This text box is where you should respond to the feedback provided in this email (up to 500 words). Once you feel you have addressed all of the comments provided above, you should press the Submit button.

https://nsfgov.secure.force.com/sbir/SBIRExecutiveSummary?esid=ODU1ZjE3MjJmZjJlOTdiY2JlNThlZDFlNDlhYTEzY2M=

## Actual Behavior

I click on the on the link above, which brings me to the Contact Info page of the Project Pitch submission form. When I click Next to move on to the next page, the form throws the following error:

Error:
Upsert failed. First exception on row 0 with id 500t000000Xs3eyAAB; first error: ENTITY_IS_LOCKED, This record is locked. If you need to edit it, contact your admin.: []

## Steps to reproduce the behavior
- Go to: https://nsfgov.secure.force.com/sbir/SBIRExecutiveSummary?esid=ODU1ZjE3MjJmZjJlOTdiY2JlNThlZDFlNDlhYTEzY2M=
- Click Next button
- See top of form

## This issue is done when:
- When I can get to the second page of the Project Pitch submission form & successfully fill out the Response to Request for More Information field & submit the form.
- [ ]
- [ ]

**Comment by kmonterr** [comment]
Thanks for alerting us!!
