### ISSUE TITLE
Adding a link to the Photonics DCL

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1900]
Hi Sarah,

Can you please add a link to the Photonics DCL on the Photonics Tech page? (https://seedfund.nsf.gov/topics/photonics/)

The Photonics topic addresses the research and development of new materials, devices, components, and systems that have the potential for revolutionary change in the optics and photonics industries. Photonic technologies can include anything generally operating in or using photons in the electromagnetic spectrum from gamma rays down to long radio waves. Examples include photovoltaics, lasers, various light-emitting diode technologies (LED, OLED, QLED), radiation detectors, and novel communications technologies.

Here's the new paragraph:

Read the **Dear Colleague Letter: Research on Integrated Photonics Utilizing AIM Photonics Capabilities** (link) to learn more about opportunities to encourage innovative exploratory and translational research by academic researchers and small businesses in all aspects of integrated photonics that utilize the current silicon photonics capabilities resident in AIM Photonics.

https://www.nsf.gov/pubs/2021/nsf21015/nsf21015.jsp

**Comment by mpadigala** [comment]
This issue has been resolved and deployed.

**Comment by kmonterr** [comment]
thanks!
