### ISSUE TITLE
About Page Changes

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1904]
https://seedfund.nsf.gov/about/

We need to update the mentorship language on the "About Page"
**Instead of this:**
•	Virtual mentorship from program advisors: Our program directors, who have deep technical expertise and entrepreneurial experience, have been in your shoes — they can offer guidance and advice through the award process. And we promote startups in all locations, not just tech hubs. You don’t need to relocate to gain access to our funding or mentorship.
**Use this:**
•	Virtual coaching from program staff: Our program directors, who have deep technical expertise and entrepreneurial experience, have been in your shoes. And we support startups in all locations. You don’t need to relocate to gain access to our funding.

**Instead of this:**
You’ll work with a program director, who will serve as your mentor and advocate. You’ll also become part of the largest group of technology startups and small businesses in the country.
**Use this:**
You’ll work with a program director, who will serve as your coach. You’ll also become part of the largest group of technology startups and small businesses in the country.

**Comment by seakhtar** [comment]
Hi @kmonterr -

This has been completed!

**Comment by kmonterr** [comment]
Thank you!
