### ISSUE TITLE
fixing award conditions link - Phase I 

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1952]
Hi - Can you please update the link on page https://seedfund.nsf.gov/resources/awardees/phase-1/

 “Phase I general award conditions” 

needs to point to https://www.nsf.gov/awards/managing/sbirsttr_conditions.jsp. 

THanks!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just confirming this has been completed!

**Comment by kmonterr** [comment]
thank you!!
