### ISSUE TITLE
Extension Note on Phase II application page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1955]
Hi Sarah - Can you please mock up a draft page changing this page?

https://seedfund.nsf.gov/resources/awardees/phase-2/apply/

**Please update the language under the "Submission Info" portion of the site:**

A company may submit a Phase II proposal anytime between six (6) months and two years (24 months) after the start date of the relevant Phase I award. The start date can be found on your Phase I award letter. 

All SBIR/STTR Phase I awardees with Phase I start dates between December 4, 2018, and December 4, 2019, will have a three-month extension to submit their Phase II proposal. The Phase II submission deadline will be extended by three months to be 27 months (rather than 24 months). In other words, if your award date was:

•	December 4, 2018: your new Phase II proposal deadline is March 4, 2021.
•	January 1, 2019: your new Phase II proposal deadline is April 1, 2021.
•	February 1, 2019: your new Phase II proposal deadline is May 1, 2021.

Proposals that have already been submitted will not be affected by this change. 

**Please remove the quarterly windows from 2020 -** 
There are quarterly windows for submission of a Phase II proposal. The next submission date is December 3.

Submission window dates for 2020 are as follows:
March 6, 2020 - June 4, 2020
June 5, 2020 - September 3, 2020
September 4, 2020 - December 3, 2020

**Comment by seakhtar** [comment]
Hi @kmonterr -

Here is the test branch. Let me know if I got anything wrong!
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/extension/resources/awardees/phase-2/apply/

**Comment by kmonterr** [comment]
Please publish! Thanks, Sarah!
