### ISSUE TITLE
About Page Changes

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#1960]
Can you please move these two sections higher up? Above the section about "Funding for R&D with Founder friendly terms"

We support small companies and new entrepreneurs
We work with startups and small businesses, and we welcome proposals from newly formed companies — you don’t need a track record of commercialization to apply for funding. Please note that your company needs to be a legal entity before you apply.

If your company is majority owned by venture capital operating companies, hedge funds, or private-equity firms, you’re not eligible to apply for funding, although joint ventures and partnerships are eligible. Read more about proposal eligibility in our Eligibility Guide.

We support R&D with lots of technical risk
Our seed funding is for R&D that involves a good amount of technical risk. If you’re already sure that your product is technically feasible, this program isn’t a good fit for you.

In selected cases, we support innovations to existing products and services, but these innovations must dramatically change the products’ commercial prospects. We don’t fund work that simply improves existing products. Check out our portfolio to get a sense of our founders’ work.

Learn more by serving as an NSF reviewer.

**Comment by kmonterr** [comment]
Can you also please remove the sentence under program basics - "For more program information, check out our last solicitation."

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Had this on the test branch with the other updates, so wanted to give you a chance to look it over if you'd like!
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/youtubeLinkFix/about/

Otherwise, it's all set to be published with the rest!

**Comment by kmonterr** [comment]
This looks good! Please publish!
