### ISSUE TITLE
Updating the press release templates

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#2015]
Hi Sarah,

can you please replace the press release templates on our website? The URLs should stay the same.

thank you!
Kelly 

Phase I
https://seedfund.nsf.gov/assets/files/awardees/Phase%20I%20press%20release%20template.docx

Phase II
https://seedfund.nsf.gov/assets/files/awardees/Phase%20II%20press%20release%20template.docx 

Here are the updated docs:
[Phase II press release template FY21.docx](https://github.com/18F/nsf-sbir/files/6037418/Phase.II.press.release.template.FY21.docx)
[Phase I press release template FY21.docx](https://github.com/18F/nsf-sbir/files/6037419/Phase.I.press.release.template.FY21.docx)

**Comment by seakhtar** [comment]
Hi @kmonterr -

This has been completed!
