### ISSUE TITLE
Updating the Annual Events Calendar?

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#2039]
Hi Sarah!

Can you please update the annual events calendar?

Can you please update the language at the top to read 2021 (instead of 2020)?

Please keep the following events and delete the others:
ACA
AISES
SACNAS
NSBE - move to April https://convention.nsbe.org/

I'll have more to add in the coming month(s)!

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Here are the changes in dev. If everything looks good let me know and I'll push to prod!
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/events/
