### ISSUE TITLE
Resources and Events Page: Content

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf-sbir#204]
<img width="71" alt="screen shot 2017-06-01 at 10 41 54 am" src="https://cloud.githubusercontent.com/assets/5495118/26685070/042e4a9c-46b7-11e7-8f99-76e8497d175d.png">

## Key Content Strategy for this page
- The value of 1:1 communication with NSF has surfaced in user research - as a way to ultimately  determine fit and for networking opportunities, among other things.  Users are interested in knowing if there are upcoming NSF events they can participate in 

## Top User Stories and Needs
- As a user, I want to find out about events that I can attend so that I can talk to or pitch ideas to NSF personnel.  (note that this may not be NSF's intention - to receive pitches, but that will likely be an end user goal - to promote an idea or product). 
- As a user, I want to know if NSF what events NSF will be participating in that I may also be attending or be interested in attending.
- As a user, I want to know what events I can attend if I cannot travel in person (remote opportunities).  
- As a user, I want to understand what will be discussed during the events, and who will be in attendance. 

---

## Workflow
- [x] Content strategy
- [x] First round content / wireframe
- [x] Team checkin
- [x] Second round content
- [x] Team checkin
- [x] Handoff to design
- [x] First round design 
- [x] Team checkin (+NSF)
- [x] Second round design
- [x] Team checkin
- [ ] Implement 
- [ ] Push to dev

## Research (00/00/00 - 00/00/00)
- [ ] Interviews (3 days)
- [ ] Synthesis + recommendations (2 days)
- [ ] Implementation (2 days)

**Comment by OpenGlobe** [comment]
I think this is the most up-to-date page, is that correct @kategarklavs ?

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/dev/events/

**Comment by kategarklavs** [comment]
@OpenGlobe Yep, that is indeed the most recent version!

**Comment by kategarklavs** [comment]
An update here: Just implemented the changes we discussed during today's content check in (and a PR for this is open). We can close this issue once the changes are live!
