### ISSUE TITLE
Updating Project Pitch Language on Apply Page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#2043]
Hi Sarah!

Can you please update the text in Project Pitch (step 4) on the apply page?
Let me know if you have questions!
Kelly 

Each small business is allowed to submit one Project Pitch at a time.*
*A small business may only submit one Project Pitch per submission window. A small business is permitted to resubmit its Project Pitch (with revisions to address any deficiencies) in a future submission window. (Please reference the solicitation for submission windows).

Any small business that has received an invitation to submit a full proposal, or which has a full proposal under review, must wait for a resolution of the full proposal before submitting a new Project Pitch. 

An invitation to submit a full proposal is valid for one year.

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just wanted to do a quick check that it looks okay before publishing!
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/apply/

Let me know if you'd like me to make any adjustments. Thanks!
