### ISSUE TITLE
Linking to the YouTube playlist

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#2046]
Hi Sarah!

Can you please link to the Startups and Small Business playlist on the top of the showcase page?

https://www.youtube.com/playlist?list=PLGhBP1C7iCOkPp8yv2I3ZGk16LiMIiikb

We’re not interested in innovation for innovation’s sake — we back technologies that promote the social good. Learn more about our companies’ impact below. To watch more videos of startups funded by NSF, visit our YouTube playlist [link].

Let me know if you have questions!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr,

This is ready to go-- just sending along a draft for you to check over!
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/showcase/

If it looks good, let me know and I'll publish!

**Comment by kmonterr** [comment]
perfect!! Thank you, Sarah!
