### ISSUE TITLE
Updating the video link on the For Applicants page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#2049]
https://youtu.be/tFPIn8wDQUo

Can you please move the current link to the Project Pitch webinar to the bolded text and add the following link too? 

Thinking of applying for Phase I funding? Ask all your application-related questions during our Virtual Office Hours or watch a recorded **program overview** or a recorded how to apply overview [https://youtu.be/tFPIn8wDQUo]. (We offer a PDF version of program basics, too.)

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just checking that I have it right before publishing. Let me know if anything needs to change!
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/resources/applicants/

Thanks-

**Comment by kmonterr** [comment]
looks good! Thanks, Sarah!
