### ISSUE TITLE
Updating NCE page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#2054]
Hi Sarah,
can you please make the following updates?
Thank you!
Kelly

Phase I – 

1.	Please add the following bullet to the end of the list of bullets on this page: https://seedfund.nsf.gov/resources/awardees/phase-1/no-cost-extension/

Requirements for a No-cost extension
-	Please note: A No-cost extension does not extend the eligibility period for supplements. 

Phase II – 

1.	Please add the highlighted sentences to the end of this paragraph on this page: https://seedfund.nsf.gov/resources/awardees/supplement/overview/
Supplemental Funding overview
-	Please notify your Program Director of your intention to submit a supplemental funding request before preparing and submitting a proposal. Supplemental funding is only available for active Phase II awardees. 
--	Please note: A no-cost extension does not extend the eligibility period for any supplement. You will not be eligible to apply for or receive supplemental funding after your original award period has ended.  Receipt of a Technology Enhancement for Commercial Partnerships (TECP) supplement may extend the base award six months, and can thereby extend the deadline for submission of a Phase IIB supplement.  Aside from this one exception, extensions to your project do not extend any of the supplemental opportunities.

2.	Please add the following bullet to the end of the list of bullets on this page: https://seedfund.nsf.gov/resources/awardees/phase-2/no-cost-extension/
Requirements for a No-cost extension
-	Please note: A no-cost extension does not extend the eligibility period for any supplement. You will not be eligible to apply for or receive supplemental funding after your original award period has ended.  Receipt of a Technology Enhancement for Commercial Partnerships (TECP) supplement may extend the base award six months, and can thereby extend the deadline for submission of a Phase IIB supplement.  Aside from this one exception, extensions to your project do not extend any of the supplemental opportunities.

**Comment by seakhtar** [comment]
Hi @kmonterr -

Just finishing this up and wanted to check that I updated the Supplemental Funding Overview page correctly. Would you like the new sentences to appear in the paragraph or below it?
https://federalist-e9c24948-6a42-4d93-94cd-6dbacf6299bd.app.cloud.gov/preview/18f/nsf-sbir/dev/resources/awardees/supplement/overview/

Once I have that right, we should be set to publish. Thanks!

**Comment by kmonterr** [comment]
Looks good! Please publish :)
