### ISSUE TITLE
NSF innovation frontier

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#2062]
Hi Sarah,

Can you please see where we've posted information about NSF Innovation Frontier on our site?

https://seedfund.nsf.gov/resources/nsfinnovationfrontier/

We are closing the platform and need to unpublish this information.

Let me know when you find it all and I can confirm and rewrite the content!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr ,

Unless it goes by any other names or acronyms, the page you linked was the only mention of it I could find on the Seedfund site. If there was another place you thought it might be showing up, let me know and I'll double check. But otherwise, I haven't seen anything else!

**Comment by kmonterr** [comment]
thanks for checking, Sarah! Is it linked from somewhere or is it a standalone page? I can't remember!

**Comment by seakhtar** [comment]
It doesn't look like it's linked from anywhere in the site itself, so I guess it was developed as a standalone page? Unless the internal link was removed at some point with content changes. Either way, it looks like this is the only page we need to worry about!

**Comment by kmonterr** [comment]
wonderful! Can you please unpublish the page?
Thank you!
