### ISSUE TITLE
QA: URLs.

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf-sbir#251]
- [x] Let's make sure that the URLs are going to the right places (and we don't have broken / wrong links)

**Comment by OpenGlobe** [comment]
Brian - to help solve for the first part of this issue, can you run the URL scanner you suggested here?

**Comment by gemfarmer** [comment]
@OpenGlobe a bit late response, but I think @line47 has run the scanner

**Comment by OpenGlobe** [comment]
I'm closing this, but let's re-open if there's something we need to address here.
