### ISSUE TITLE
QA: Content Review

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf-sbir#257]
Need to check for voice and tone, and inconsistencies.

**Comment by OpenGlobe** [comment]
@kategarklavs to schedule a time

**Comment by kategarklavs** [comment]
@OpenGlobe Hey! Just blocked off time on the morning of Wednesday, 6/28.

**Comment by OpenGlobe** [comment]
@kategarklavs I'm closing this following the meeting - I think we can open specific items to address as necessary - but feel free to re-open if we need to comb through again as a group following a number of significant changes.
