### ISSUE TITLE
Federalist Questions

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf-sbir#277]
1. Can we link out to a Google Form at NSF that collects company proprietary information and PII?

2. Can we restyle the form fields on our Federalist site for the Google Form?

3.  Can we embed white-label iframe registration buttons and details from Webex for NSF webinar announcements on our events page?

4.  Can we use a GSA Google Form to solicit feedback about our website on our Federalist site?

cc: @line47 @femmebot @wslack 

(feel free to correct anything I have here!)

**Comment by OpenGlobe** [comment]
@wslack anything else here we need to do?  Are we ok as outlined above?

**Comment by wslack** [comment]
Oh no! I never added you to the invite!

**Comment by wslack** [comment]
Will get back to you; apologies.

**Comment by wslack** [comment]
I sent an e-mail with my expected answers for them to confirm or deny.

**Comment by wslack** [comment]
Ok answers:

> 1. Can we link out to a Google Form at NSF that collects company proprietary information and PII?

**​Yes, as long as we are not in any way directly connected to this PII. ​**

> 2. Can we restyle the form fields on our Federalist site for the Google Form?

Not possible without much further negotiation given the PII.

> 3.  Can we embed white-label iframe registration buttons and details from Webex for NSF webinar announcements on our events page?

Not via the GSA ATO.

> 4.  Can we use a GSA Google Form to solicit feedback about our website on our Federalist site?

GSA wants to know what kind of data is being collected (no PII right?)

**Comment by OpenGlobe** [comment]
@wslack what about iframes for Google Maps and such?  NSF has content like that embedded in various places, or to videos.   Is that possible?

**Comment by wslack** [comment]
@OpenGlobe The GSA Authorizing Official has not accepted the risk for iFrames like that. I think a YouTube video or Google Map embed might be different; do you have an example I can point to?

I think it gets tricky for any iFrame to a system that GSA hasn't vetted or approved already - so NSF would be taking responsibility for that.

**Comment by OpenGlobe** [comment]
Here are some examples: 

https://www.nsf.gov/eng/iip/sbir/portfolio.jsp

cc: @femmebot @kmonterr

**Comment by OpenGlobe** [comment]
@femmebot if we can't embed the iframe for the webinars, I guess we can just embed the link in the button?

**Comment by OpenGlobe** [comment]
So, to recap: 

- Youtube videos ok (already done elsewhere)
- NSF would need to assume responsibility for iFrame content (not covered under ATO)
- Google Maps _might_ be ok, but also might have to be covered by NSF

With all that said, I think where possible we should default to linking out where we can, but can talk to Kelly re: anything that looks really difficult to do otherwise.  For now, I'd say we want to steer clear of iFrame content and the like.

**Comment by OpenGlobe** [comment]
@openglobe to send a quick note re: iframe / embedded content to NSF

cc: @wslack

**Comment by wslack** [comment]
GSA IT's initial guidance is that we can't do embedded Google Maps under our ATO

**Comment by OpenGlobe** [comment]
Email sent 06/26

**Comment by OpenGlobe** [comment]
Closing per NSF's ok to put maps on the site, per e-mail.
