### ISSUE TITLE
Add Accesslint circle configuration to the website

### ISSUE THREAD

**Issue by line47** [18F/nsf-sbir#283]
Follow the [development guide instructions](https://github.com/18F/development-guide/tree/master/accessibility_scanning) on accessiblity scanning using accesslint to create a `circle.yml` config file that will scan this repo.

**Comment by line47** [comment]
Will follow up with @gemfarmer

**Comment by gemfarmer** [comment]
Let's skip this. It would have been most important during active development, and we have been using `pally-ci` instead for a more "manual automated" approach
