### ISSUE TITLE
Rewrite leading paragraph for tech topic areas?

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf-sbir#303]
Since we're planning on soliciting feedback via the Google Form as opposed to an email, I think we need to come up with a rewrite of the folllowing text that leads each tech topic area.  

For example: 

You may communicate with the Program Director, Rajesh Mehta (rmehta@nsf.gov), to gauge if a project meets the program’s intellectual merit and commercial impact criteria. Send a 1-2 page executive summary by e-mail discussing the following aspects of the project: 1) the company and team; 2) the market opportunity, value proposition, and customers; 3) the technology/innovation; 4) the technical challenges to overcome; and 5) the competition. Please note that responsiveness will likely be limited in the 2 weeks leading up to the solicitation deadline.

**Comment by kategarklavs** [comment]
Circling back on this — I'm happy to start this on next week (if there's time) 👍

**Comment by OpenGlobe** [comment]
I believe we're addressing this now with the form, and this: 

<img width="272" alt="screen shot 2017-06-30 at 10 17 17 pm" src="https://user-images.githubusercontent.com/5495118/27758444-f39c3832-5de1-11e7-8ded-2bbb0161b4d6.png">

Closing this issue.
