### ISSUE TITLE
Content: Event cleanup

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#324]
Per our 6/13/17 issue cleanup meeting: We need to decide where to highlight events-related information – on an Events/resources page (the direction we were going in), or on the landing page (events-related section of the landing page is not currently designed).

Some more concrete steps:

- [x] Confirm with NSF team that webinars, CES, SxSW, and the bus tour are the only events to promote. 
- [x] Drawing on NSF's input, make a decision about where to place event-related content.
- [x] If we decide to go with displaying event content on the landing page, write a brief intro for that section.
- [x]  If we decide to go with displaying event content on the landing page, retitle the "Events/Resources" page simply "Resources" and rewrite content accordingly.
- [x] If we decide to keep events/resources content bundled, restructure content based on user need rather than content type. 

@OpenGlobe & @femmebot -- please add/edit as you see fit!

**Comment by kategarklavs** [comment]
Update from yesterday: I updated Events/Resources content on `Dev` (still waiting on a review of the PR). The page now presents content by user type (applicants, Phase I awardees, Phase II applicants/awardees, and all users (general content)), and once again features event-related content at the top of the page. 

cc @femmebot and @OpenGlobe

**Comment by kategarklavs** [comment]
Update: Confirmed with @OpenGlobe that we're not going to introduce the events feed to the landing page before launch; event info will live on the Resources/events page.

**Comment by OpenGlobe** [comment]
@kmonterr can you recommend any upcoming events that you'd like to see highlighted on the Events and Resource page?  Right now we just have placeholders: 

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/dev/events/

cc: @femmebot

**Comment by kmonterr** [comment]
Yes, @OpenGlobe 
Here's the big ones for the rest of the year:

- New York Venture Summit - http://www.youngstartup.com/newyork2017/overview.php (July)
- SBIR Road Tour - http://www.sbirroadtour.com/dates.php# (July, September and October - stand alone event)
- SEMICON West - http://www.semiconwest.org/ (July)
- SymBioBeta - http://synbiobeta.com/ (October)
- Black Enterprise - TechConnext Summit http://www.blackenterprise.com/events/techconnext/  (October)
- SOCAP - http://socialcapitalmarkets.net/ (October)
- EmTech http://events.technologyreview.com/emtech/16/  (October)

Here are some of the big ones we tend to do every year....

CES http://www.ces.tech/ (January)
SXSW https://www.sxsw.com/ (March)
ACA Summit https://www.angelcapitalassociation.org/ (April) 
National SBIR Conference (May)
ISTE https://www.iste.org/ (June)
BIO International Convention http://convention.bio.org/home.aspx (June)
Phase II SBIR Conference - https://www.nsfiipconf.com/2017sbirp2/ (June)
SBIR Road Tour - Summer

**Comment by kategarklavs** [comment]
Update to this issue — I removed the Award management forms from the Resources/events page (and added a link instead). This way, potential applicants won't be distracted by info that's not directly relevant to them.

Maybe next week, we can discuss how to present info re: onsite events in a way that's actionable and appealing to users 👍 

cc @kmonterr @OpenGlobe @femmebot
