### ISSUE TITLE
NSF AC: Could this language be more positive?

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf-sbir#339]
<img width="670" alt="screen shot 2017-06-13 at 5 09 17 pm" src="https://user-images.githubusercontent.com/5495118/27104712-1c89b3ee-505b-11e7-9db3-976b93637656.png">

Can we revisit: 

"You'll need to register your company with four different systems"

**Comment by kategarklavs** [comment]
To avoid potentially confusing users re: the necessity of registering with these systems, I'm going to leave the copy as is for now.
