### ISSUE TITLE
NSF: Can NSF reorder this list?

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf-sbir#340]
<img width="656" alt="screen shot 2017-06-13 at 5 15 39 pm" src="https://user-images.githubusercontent.com/5495118/27105009-fcccd47c-505b-11e7-9a93-13d03ed0a297.png">

Per @benschrag

**Comment by kategarklavs** [comment]
@benschrag Hello, and thanks for your feedback! I've removed the mention of incorporation from the eligibility step. As for re-ordering the list, the team can definitely discuss this (and gather insights on the flow as we conduct our final usability tests).

**Comment by kategarklavs** [comment]
@line47 - In looking at this issue again, I realize I'm not sure how to reorder the timeline steps. I'm going to reassign this issue to you, if that's cool.
