### ISSUE TITLE
Document in the wiki where to update content on the site

### ISSUE THREAD

**Issue by line47** [18F/nsf-sbir#388]
Document things like 
- [x] Where pages are stored
- [x] Where assets are stored
- [x] How to add a background image to a page
- [ ] Hints to picking photos or photo guidance for the templates & landing pages. 
- [x] How to add a PDF and link to it on a page
- [x] How to update the Showcase Page with a new video or photo
- [x] Where to change the static statistics in the Current Awardees Pages
- [x] How to update any site navigation (top, footer, other secondary pages)
- [x] How to add a relative link to a file to a given page
- [x] How do layouts work and how are they built
- [x] Where to find SASS/CSS and how to update
- [x] How to update the application timeline
- [x] How to update the tech topic information 
- [ ] How to run the site locally
- [x] How the API is being used and can be updated
- [ ] Link to portions of the USWDS like the Grid and buttons and other relevant items to the site
- [x] Process for moving updates from `dev` to `staging` to `master`
- [x] How to toggle the site from active to inactive
- [x] Document how to update site via config/data files and variables

**Comment by kategarklavs** [comment]
@line47 Hey! Happy to do an editing pass at this, if you like (just keep me posted) 👍

**Comment by line47** [comment]
CC @kmonterr @kevinbrogan7690 @mtemplet if you have things you'd like to see documented in the wiki that are not in the list above please add them here 👍

**Comment by OpenGlobe** [comment]
A few how-to-guides are here @line47 - as helpful!  

https://github.com/18F/nsf-sbir/wiki/How-to-guides...
