### ISSUE TITLE
Remove expired deadline from landing page

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#393]
From NSF's 6/16 feedback doc:

Please remove the July 14 deadline from the homepage now that the deadline has passed.

**Comment by line47** [comment]
Should this be June 14?

**Comment by kategarklavs** [comment]
@line47 Yep! July 14th was in the feedback doc (and I just copied/pasted directly from that doc), but it should be June 14.

**Comment by kategarklavs** [comment]
Note: This was in the "critical" section of the 6/16 feedback doc.
