### ISSUE TITLE
Update "formerly known as NSF SBIR/STTR"

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#395]
From the 6/16 NSF feedback doc:

"'In the section entitled "We are America's Seed Fund," we recommend removing the verbiage "formerly known as NSF SBIR/STTR" since the program is still called SBIR/STTR. Perhaps say, also still known as NSF SBIR/STTR.'"

- [x] Update this reference on the landing page.
- [x] Update references across all other pages.

**Comment by kategarklavs** [comment]
Note: This was in the "critical" feedback section of the 6/16 doc.

**Comment by line47** [comment]
This was updated on the homepage and could not be found anywhere else on the `dev` site @kmonterr fixed this in https://github.com/18F/nsf-sbir/pull/430
