### ISSUE TITLE
Update "commercial plan" to "commercial potential"

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#396]
Per the 6/16 NSF feedback doc:

"As we review applications section: 'We consider your technology’s innovativeness, commercial potential, and possible social impact.'"

- [x] On landing page, change _commercial plan_ to _commercial potential_.

**Comment by kategarklavs** [comment]
Note: This was in the "critical" section of the 6/16 feedback doc.

**Comment by line47** [comment]
This was updated.
