### ISSUE TITLE
Add disclaimer to portfolio page

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#397]
Per 6/16 NSF feedback doc, to the portfolio page, please add a disclaimer explaining that the featured companies don't represent all companies (see below):

"These featured companies are a small, random selection of all our funded companies. To see all the awards we've made to small businesses, please visit the [NSF Awards Database](link)." 

- [ ] Copy updated.

**Comment by kategarklavs** [comment]
Note: This was in the "critical" section of the 6/16 feedback doc.

**Comment by wslack** [comment]
@mtemplet did this in https://github.com/18F/nsf-sbir/pull/429 - but not merged to live yet

**Comment by line47** [comment]
This has been merged but needs further review from the NSF team @kmonterr

**Comment by kmonterr** [comment]
We should be good! I updated the language per NSF guidance yesterday
