### ISSUE TITLE
Critical font feedback (6/16 doc)

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#398]
- [x] There are varied fonts on the page that are not part of brand guidelines. Please change the font that appears to be courier new. 

- [ ] The size seems really tiny. Can we make it a little bigger please?

**Comment by kategarklavs** [comment]
Note: This was in the "critical" section of the 6/16 feedback doc.

**Comment by line47** [comment]
To give a bit more context, the small font size found throughout the site is using `$font-size-xxs: 1.2rem;` if that is to small then `$font-size-xxxs: 1.1rem;` is also going to be too small. We may need to refactor the font sizing to address this.

**Comment by OpenGlobe** [comment]
@femmebot has updated per the first issue - have we addressed the second?  Do we need to?

**Comment by OpenGlobe** [comment]
@kmonterr are we ok to close this issue?  Did the adjustment in the fonts help address the smaller size concern?

**Comment by kmonterr** [comment]
@OpenGlobe yes! Gracie said it looked OK now.

**Comment by OpenGlobe** [comment]
Great!  Ok, closing the issue.
