### ISSUE TITLE
Landing page, "Diverse Portfolio" section

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#402]
Per 6/16 NSF feedback:

"Diverse portfolio” section, not sure I like the “We provide much more than academic research grants” because SBIR/STTR does not provide any academic research grants and I presume this page is all about SBIR/STTR.  Can we say “We fund startups and small businesses across technology areas, across market sectors, and across the country”, or something like that?"

**Comment by OpenGlobe** [comment]
Revised: 

"We fund startups and small businesses across technology areas and markets including IoT, edtech, smart health, robotics, and much more."
