### ISSUE TITLE
Landing page, events-related information

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#403]
Per 6/16 NSF feedback:

"Access to our network of innovators and industry experts”, the text is “Attend dozens of annual events…”.  Doesn’t this imply that as a grantee, one of the benefits is that we let you attend dozens of events?  I am not sure this is clear.  Especially since we’re getting out of the business of sending our grantees to events.  Maybe we mention here how many alumni we have or how many experts we use to do reviews?"

**Comment by OpenGlobe** [comment]
This is addressed in the revised text: 

"Meet other entrepreneurs, technical experts, industry leaders, and NSF program directors, and build lasting bonds with future leaders in your industry. **Find us at dozens of annual events **— conferences, road shows, and more."
