### ISSUE TITLE
About page: Update "24" to "24+"

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#412]
Per 6/16 NSF feedback doc:

"Up to $1.5M / 24+ months." (In other words, add a plus sign after 24.)

---

- [ ] On this page, change _24_ to _24+_
- [ ] Apply this change to all instances of _24_ throughout the site.

**Comment by OpenGlobe** [comment]
This appears to have been implemented - can we close this @kategarklavs ?

**Comment by kategarklavs** [comment]
@OpenGlobe Ah, yep! This was another one of the changes that the NSF team implemented — closing now!
