### ISSUE TITLE
Portfolio page feedback: PD photos

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#421]
Per 6/16 NSF feedback doc:

"We recommend adding photos of PDs above their name to the left of the description of their topic area."

**Comment by line47** [comment]
@kmonterr Is this issue referring to the tech topic pages? If so I'd say it's completed. 👍 
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/dev/topics/manufacturing-and-nanotechnology/

**Comment by OpenGlobe** [comment]
This is also addressed with the addition of the links to the bios - I'll close for now and we can re-open should we need to.
