### ISSUE TITLE
Text changes to about page_R&D section

### ISSUE THREAD

**Issue by mtemplet** [18F/nsf-sbir#458]
•	Up to $1.5M / 24+ months. 
•	Spell out R&D – Research and Development (R&D)
•	Minimal standard reporting: We provide templates for reporting monthly progress and financials. No need to waste time crafting decks and building spreadsheets — we help you focus on building your product or service instead.
•	Possible follow-on funding: Companies that complete Phase I may be eligible for more funding. If you’ve shown that your technology is feasible and needs more development, you can apply to receive an additional $750,000 over two years. And, depending on your circumstances, you could be eligible to apply for up to $500,000 in supplemental funding.
•	Program Basics: 
o	When you decide to apply for funding, you’ll submit a Phase I proposal for up to $225,000, which will cover at least six (and up to 12) months of work. You’ll find out whether your proposal was accepted or declined within four to six months of the proposal deadline.
•	We Support R&D…Add “service” whenever we say product. 
•	About NSF: 
•	(we could add SBIR info here if it makes more sense – I might vote for keeping it up top for the next year though). 

•	Link to the tech topic page.
•	Perhaps we give all the photos the same treatment? They look bad right now. 
•	There are two pictures of Rick under Program Directors. Please put both of his tech topic areas under his photo and delete one photo.

**Comment by OpenGlobe** [comment]
@kategarklavs I think this one is also merged?

**Comment by kategarklavs** [comment]
@OpenGlobe Just looked over the list of to-dos, and I believe all the content items were addressed in the onsite workshop. I'm not sure whether the photo-treatment stuff has been addressed, but I think we're OK to close this issue out and open new photo-related issues, if necessary.
