### ISSUE TITLE
Content: Update grantees to awardees

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf-sbir#487]
<img width="582" alt="screen shot 2017-06-21 at 2 09 12 pm" src="https://user-images.githubusercontent.com/5495118/27399605-54616ff6-568b-11e7-88fc-1e3c9f2399f9.png">

**Comment by kategarklavs** [comment]
@OpenGlobe This was resolved with the most recent update of the Ambassador toolkit page 🎉 Closing out this issue!
