### ISSUE TITLE
Adding the Design Style Guide to the Wiki Page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#493]
Just want to make sure this is on our radar and with the other content we need to add to Wiki. No rush - just before July 7!

https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/explore/sub/index.html

**Comment by OpenGlobe** [comment]
Added to wiki - updated the link: 

https://github.com/18F/nsf-sbir/wiki/NSF-SBIR-Design-style-guide
