### ISSUE TITLE
Content: Additions to Press Page

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf-sbir#518]
I have a list of things to add:
•	our boilerplate
•	one-pager about the program
•	the re-brand
•	history of NSF SBIR (can be a short blurb and link to SBA.gov)
•	NSF Logo link: https://www.nsf.gov/policies/logos.jsp
•	NSF newsroom: https://www.nsf.gov/news/newsroom.jsp
•	Please contact Media Officer Sarah Bates with inquiries (sabates@nsf.gov)
•	Link to the director’s bio: https://www.nsf.gov/mobile/staff/staff_bio.jsp?lan=fcordova&org=NSF&from_org

Bio for Barry W. Johnson, Division Director, Industrial Innovation and Partnerships: https://www.nsf.gov/news/news_summ.jsp?cntn_id=134426

Per @kmonterr

**Comment by kategarklavs** [comment]
@kmonterr Hello! A quick question for you — would you like me to write the blurb about the rebrand, or would you prefer to do it? (Either is fine by me; just want to make sure we're not duplicating efforts.)

**Comment by kmonterr** [comment]
That would be very helpful! Thank you, @kategarklavs

**Comment by kategarklavs** [comment]
@kmonterr Sounds good — will do!

**Comment by kategarklavs** [comment]
Update: Added WIP rebrand copy to the press page (to be merged into `press-page-edits`) and requested review from @kmonterr 👍 This content is very much in draft format, so it'll likely change a bit next week.

**Comment by kmonterr** [comment]
I love your rebrand language! I think the last issue is adding the PDF to the link at the bottom of the page. I'm not sure how to do it! @kategarklavs 
[NSF SBIR Overview 2016.pdf](https://github.com/18F/nsf-sbir/files/1103135/NSF.SBIR.Overview.2016.pdf)

**Comment by kategarklavs** [comment]
@kmonterr Ah, awesome! I'm glad you like it, and I can add the PDF today 👍

**Comment by kategarklavs** [comment]
@kmonterr - on second glance, I need to consult with @line47 on how to upload this PDF. Will get this done tomorrow!

**Comment by kmonterr** [comment]
awesome! I don't know how to do it either @kategarklavs ! probably another good thing to add to the wiki...I figured out how to add it to the repository, but forgot how to link it on the page!

**Comment by kategarklavs** [comment]
@kmonterr YES, this will definitely be a good thing to add to the wiki — in fact, if it's not already on the checklist, I'll add it now.

**Comment by kategarklavs** [comment]
@kmonterr OK, just added it to our list of "things to add to the wiki" 😁

**Comment by kategarklavs** [comment]
Update here: It looks like everything has been added — I opened a PR to merge `press-page-edits` into `dev`. That PR just needs a review, and then we should be all set to close this issue.

**Comment by OpenGlobe** [comment]
WWOOOOOOO!

**Comment by kategarklavs** [comment]
OK! Merged in the PR — I think we should be good! But let me know if we need to make any changes.
