### ISSUE TITLE
Changing Usa.gov to USA.gov

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#563]
Hi @line47 and @gemfarmer Quick note – in the footer, Usa.gov should be USA.gov. Thank you!

**Comment by line47** [comment]
Hey @kmonterr, do you want to take a shot at updating this? 
Here is where you can make the change https://github.com/18F/nsf-sbir/blob/dev/_data/navigation.yml#L84

**Comment by kmonterr** [comment]
hi @line47 done! I updated the USA.gov  in the subfooter. We didn't get to update the language around the NSF mainline v. the SBIR mainline. should we do that in the footer? Or, if you want to walk me through it today, that could work too.
