### ISSUE TITLE
Press page updates

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#573]
Needs a content review from @kategarklavs and the PDF added

**Comment by kategarklavs** [comment]
@kmonterr Thank you! @OpenGlobe & I are conducting interviews now, but I shall take a look right afterward :)

**Comment by kategarklavs** [comment]
@OpenGlobe Howdy! I think @kmonterr already merged this PR (the History language is up on the press page on `press-page-edits`), and I have a PR in for the addition of the one sheet PDF — I think we should be all set!
