### ISSUE TITLE
Fixing Text on the How to Apply Pages

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#576]
- make this sentence parallel add: “Learn more about our Phase I application timeline, **how to prepare** your proposal, and what to expect once you submit.”

- Can we revise the text on eligibility to read “Check if your company meets the eligibility requirements”?  Not sure why we need to tell them to incorporate explicitly.

- Let’s also reiterate on this page what we’re really looking for at the top.  

- here are changes in the eligibility section: 
o	Small business (add "**fewer than 500 employees**"). Make sure that’s on there.
o	PI should be spelled out again.
o	Link to the eligibility section of the SBA site instead of the PDF. Also, remove the term “our” since it does not belong to us.
o	Remove the hyphen with early stage technology
o	Reorder the criteria – High-risk, pre-traction, scale. 
o	Remove seed stage. It doesn’t work with the text behind it.
o	Add – “Game-changing: Your innovation could make difference to people worldwide or revolutionize an industry.”

- We recommend changing "If you're funded through STTR, 30% of your funding must go to your research partner and 40% must go to your company" to "... at least 30%.....and at least 40%..."

- We recommend substituting "Register your company with these systems" or "You'll need to register your company with four different systems".  

- Do people know what EFT is? I recommend saying bank information. 

- In the Review the solicitation part:
o	Add links to the solicitations here. 
o	The solicitation has “tips **and outlines**” for preparing your proposal.
•	Start your application: include a link to the coded Application guide.

**Comment by OpenGlobe** [comment]
@kategarklavs is working through these changes.

**Comment by kategarklavs** [comment]
- _make this sentence parallel add: “Learn more about our Phase I application timeline, how to prepare your proposal, and what to expect once you submit.”_- done!
- _Can we revise the text on eligibility to read “Check if your company meets the eligibility requirements”? Not sure why we need to tell them to incorporate explicitly._ -  latest version of the copy doesn't include mention of incorporation, so we're all set here!
- _Let’s also reiterate on this page what we’re really looking for at the top._ - I'm happy to add more copy if you all have specific suggestions, but I think the eligibility section does a good job of outlining what we're looking for (About page includes some of this info, as well). Thoughts?
- _fewer than 500 employees_ added back in
- _PI_ spelled out the second time
- Current site links to https://www.sbir.gov/faqs/eligibility-requirements for eligibility (not the PDF), so we should be all set here.
- removed hyphen from _early stage_ (it is a compound adjective, so the hyphen is OK, but I don't think the lack of a hyphen will cause too much confusion)
- Replaced _seed-stage_ blurb w/ _game-changing_ blurb
- Added "at least"s to the STTR description
- _We recommend substituting "Register your company with these systems" or "You'll need to register your company with four different systems"._ - The most current version of the site features the latter phrasing, so I think we're set here 👍 
- changed _EFT_ to _bank account_

re: the review solicitation section, I'm not seeing the copy stating that the solicitation has "tips" for preparing your proposal — I think this may have been part of a previous version of the page. 

- I added links to the FastLane guide + application video. @line47 - would you be able to verify that the FastLane link is correct? 

cc @kmonterr

**Comment by kategarklavs** [comment]
This should all be accounted for, minus the `Review solicitation` parts at the end (which will be resolved once PR #585 is merged).

**Comment by kategarklavs** [comment]
@line47 fixed the link issue with PR #594 — I think everything on this checklist is done! Moving this to the next column ...

**Comment by kmonterr** [comment]
Thank you, @kategarklavs !!!
per the hyphen feedback with early stage - our team upstairs wanted it removed!

**Comment by OpenGlobe** [comment]
It looks like the hyphen was removed - are we ok to close @kategarklavs ?

**Comment by kmonterr** [comment]
yes! @OpenGlobe! @kategarklavs made all of the changes. much more than just the hyphen!

**Comment by kategarklavs** [comment]
Word! Closing this now 🌟
