### ISSUE TITLE
Adding the Tech Topic Icons

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#578]
It would be ideal to use them.

**Comment by OpenGlobe** [comment]
The icons were on the Showcase page, but looks like with the redesign and videos perhaps they didn't work.  @femmebot can we use the icons elsewhere?

**Comment by line47** [comment]
We are OK to use the icons separately from the background images. Let's see if we can integrate the icons somewhere to help support the tech topics.
