### ISSUE TITLE
Adding past deadline and upcoming solicitation variable to the About Page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#590]
For more program information, check out our last solicitation. Our next solicitation will be posted in [MONTH YEAR].
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/nsf-nav/about/

**Comment by line47** [comment]
Hey @kmonterr what would be a good variable name for this?
`solicitation_date:`

**Comment by line47** [comment]
We will use `past_deadline` here

**Comment by line47** [comment]
https://github.com/18F/nsf-sbir/pull/609

**Comment by kategarklavs** [comment]
@line47 - anything I can do re: this issue, or are you all set? (Just making sure I'm not overlooking anything!)

**Comment by line47** [comment]
We are good! Thanks @kategarklavs
