### ISSUE TITLE
Changing "social" impact to "societal" impact throughout the site

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#598]
We heard from our team in the director's office that they want us to use the term "societal" instead of "social" impact. I know that @line47 has a way to see where it is used throughout the site pretty easily.

**Comment by kategarklavs** [comment]
@kmonterr Howdy, and thanks for the update! A question about the context for this change — I'm wondering what user need this language shift might be addressing? In keeping with our Phase I/Phase II research, we'd gone with "social" to create a more conversational, less academic tone (which has tested really well with users so far).

**Comment by OpenGlobe** [comment]
https://github.com/18F/nsf-sbir/pull/603 addresses this.  There were three instances where I found this - landing.md, mn.md, and about.md.

**Comment by kmonterr** [comment]
@kategarklavs I think the feeling is that the terms have slightly different meanings and it's how NSF talks about broader impact.

**Comment by kategarklavs** [comment]
@kmonterr Ah, gotcha — thanks for the context. I know @OpenGlobe opened a PR, so I can merge that now.

**Comment by kategarklavs** [comment]
Just merged PR #603 - closing this issue now.
