### ISSUE TITLE
Update Ambassadors Page

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#608]
We need to link to the pdf on this page.
[NSF Alumni.Grantee Tool Kit 10.2016.pdf](https://github.com/18F/nsf-sbir/files/1109918/NSF.Alumni.Grantee.Tool.Kit.10.2016.pdf)

**Comment by OpenGlobe** [comment]
Looks like this was a bad URL, but we have the doc. 

https://github.com/18F/nsf-sbir/pull/650
