### ISSUE TITLE
Removing the "N°" from the Award Pages

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#635]
Can we remove the "N°" from the award pull? management and program staff wanted it removed. 

NSF AWARD
N° 1549035 – SMALL BUSINESS PHASE I

Not sure if this is a content or API question.

**Comment by kategarklavs** [comment]
@kmonterr Hey! I think this is a content issue - checking now.

**Comment by kategarklavs** [comment]
@kmonterr - just opened a [PR](https://github.com/18F/nsf-sbir/pull/636) to address this!
