### ISSUE TITLE
Missing from Current Phase II Awardees 

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#638]
We noticed that we are missing at least one company from the current Phase II Awardee List - 
Spheryx - perhaps there are more?

Not sure what the bug is in the API.

**Comment by gemfarmer** [comment]
@kmonterr I think it is in there now: https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/randomize/awardees/phase-2/details/?company=spheryx-inc#spheryx-inc

**Comment by kmonterr** [comment]
Thank you @gemfarmer !
