### ISSUE TITLE
Adding Goodbye Script to External Links

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#651]
We have to add this script (bolded below) to all external links. I think they are only on the showcase page (YouTube) and the Events page. 

Are links to non-government websites going to be using the NSF Goodbye script? I didn’t see them on the Showcase page - **https://www.nsf.gov/cgi-bin/good-bye?https://www.youtube.com/watch?v=vPNkUWDKvck**

**Comment by OpenGlobe** [comment]
As I understand it we've found these goodbye scripts are not overly helpful and the information is covered in your [privacy policy](https://www.nsf.gov/policies/privacy.jsp).  I can get more information from our folks if helpful, but in general I don't believe we're encouraging the use of these pop-ups / scripts.

**Comment by kmonterr** [comment]
Right now, I don't think we can get out of using it. If you have things I can send them, that would be helpful.

**Comment by OpenGlobe** [comment]
Some sites use a tooltip to implement this.  See https://everykidinapark.gov/plan-your-trip/ - mouse over one of the external links.  Another example is here: https://www.financialresearch.gov/working-papers/ - you can mouse over the social media links. 

Other sites, including GSA.gov and Whitehouse.gov, do not use the disclaimers at all.   

@gemfarmer @line47 @kategarklavs @femmebot any thoughts here?

**Comment by OpenGlobe** [comment]
Update per @line47  - there is a more intuitive for handling external links than what I posted - already part of the US Web Design Standards: 

https://standards.usa.gov/components/typography/#links

@kmonterr are your folks ok to use the standards as a guide here?

**Comment by kmonterr** [comment]
yes! @OpenGlobe let's do that. I just got clarification from our team. I'll follow up with the head of another office next week to be sure, but will have her read the standards...

**Comment by OpenGlobe** [comment]
Great.  Closing this [related issue](https://github.com/18F/nsf-sbir/issues/507) to keep everything in one place.   We'll move it to ready for implementation.

**Comment by line47** [comment]
I'm working on implementing this ATM, do we want to show external link icons to items in the USA banner and footer or just keep the focus on the main content of the page?

### USA banner screenshot

![screen shot 2017-06-30 at 12 23 24 pm](https://user-images.githubusercontent.com/1449852/27744806-047cfe50-5d8f-11e7-98de-73c4b2cc5d61.png)

### Footer screenshot

![screen shot 2017-06-30 at 12 23 13 pm](https://user-images.githubusercontent.com/1449852/27744809-08410af4-5d8f-11e7-9e33-00d0babb6411.png)

CC @kmonterr @OpenGlobe @femmebot

**Comment by kmonterr** [comment]
Let's not worry about it in the footer! I think it looks funny. I would keep it on links on each of the pages. We won't need it to links to NSF sites either. @line47
