### ISSUE TITLE
Write recommendations for how to improve API

### ISSUE THREAD

**Issue by gemfarmer** [18F/nsf-sbir#681]
@kmonterr had mentioned that it would be helpful to have a write-up of our experience using the API, along with some recommendations for improvements that could be made to make the API easier to use

## Steps to reproduce the behavior
- [x] Document pain points
- [x] Document how we worked around/through those pain points
- [x] Document potential future solutions

**Comment by line47** [comment]
See issues #281, #336, #568, #626

**Comment by scienceanswers** [comment]
@gemfarmer   We'll bring this to our Team's attention..

**Comment by gemfarmer** [comment]
#795

**Comment by gemfarmer** [comment]
@kmonterr I could write up something formal if you'd like, but I think the following list of issues is a good place to start:
 #281, #336, #568, #626, #795

**Comment by kmonterr** [comment]
Just to close the loop, it'd be great if you could write something more formal! I'll make sure everyone here is aware of it!! THANK YOU!!

**Comment by gemfarmer** [comment]
@kmonterr I wrote a more comprehensive set of suggestions here: 

https://docs.google.com/document/d/1VEw3yf95rx9w8TynW50rVuEVRu-hSr1KVmFj4ZcSKbc/edit#

**Comment by gemfarmer** [comment]
With the write up out of the way, this issue is now done!

**Comment by kmonterr** [comment]
[NSF SBIR API Recommendations.docx](https://github.com/18F/nsf-sbir/files/1288142/NSF.SBIR.API.Recommendations.docx)
great resource for your team, @billdaus !

**Comment by scienceanswers** [comment]
Thanks @kmonterr . We'll create a JIRA and try to prioritize it in a future release.

**Comment by kmonterr** [comment]
awesome! Thanks, @scienceanswers !
