### ISSUE TITLE
Fix Success Stories Google Form to match other Google Form

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#685]
hi @OpenGlobe ! Do you mind branding the success stories google form like the one you made? Thanks!

https://docs.google.com/forms/d/e/1FAIpQLSd3vzxNdZ-QebKd12bBweyXsr0oLNWmcZbCBmTQnkA65vwifw/viewform?c=0&w=1

**Comment by OpenGlobe** [comment]
Fixed!  All three should now look the same.
