### ISSUE TITLE
Current awardees order?

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#694]
hi @gemfarmer - how is this generated?

I really like how the current awardees are displayed, with relevant stats at the top. However, navigation of the lists of companies was a bit difficult - I couldn’t figure out in what iorder the companies are listed - it’s not alphabetical, neither chronological. Maybe it would be easier if the table headers were clickable to sort the table? Also it would be handy to have an “expand all” button so we can see all the companies funded at once under the different categories.

**Comment by OpenGlobe** [comment]
I believe this was intentionally random so the same companies weren't always at the top of the list (but could be wrong).

**Comment by gemfarmer** [comment]
@kmonterr @OpenGlobe 

It was originally chronological, with most recent first, but I randomized it, per the randomization request. If that wasn't supposed to also be for the awardees pages, then we can remove it. There is one html attribute that controls that, so it wouldn't take too long to revert it.

**Comment by kmonterr** [comment]
@gemfarmer good to know! I would keep the randomization on the porfolio page only. do you mind removing it on the awardees pages?
Thank you!
