### ISSUE TITLE
Removing the Most Recent Phase I Awardees Option

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#708]
For some reason, there's a bug in the API for getting the newest Phase I awardees. We probably have 130 new companies since June 2017 and only 44 are showing up. Rather than fixing it, Gracie would like to remove this as an option from our site. (https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/dev/awardees/phase-1-recent/). Her rationale - Phase I is so short that the companies listed here will also be posted in the current Phase I award search making it redundant. Does that make sense?

**Comment by gemfarmer** [comment]
@kmonterr Hmm that's strange. I can make sure I'm not doing anything wrong on our end, but we can also just remove the recent option entirely. Before removing it entirely, I would want to be sure that this is something that we want to do as it will actually require removing quite a bit of stuff.

**Comment by gemfarmer** [comment]
@kmonterr thoughts on this?

**Comment by kmonterr** [comment]
hi @gemfarmer! sorry for the delay. I wanted my boss to bless this again just in case. 
She would like this sort (most recent awardees - right now June 2017) removed. Since Phase I can be 6 months she thought it was duplicative to the Phase I sort. 
Let me know if you have any other questions!

**Comment by gemfarmer** [comment]
@kmonterr, so basically remove https://seedfund.nsf.gov/awardees/phase-1-recent/ and all links to it on the site?

**Comment by kmonterr** [comment]
yes, please! Thanks, @gemfarmer
