### ISSUE TITLE
Shasqi Image Not showing on Master Branch

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#976]
Hi @seakhtar - 

I just merged Staging into Master and noticed that the main image for Shasqi's technology didn't make it. I'm not sure why...It is clearly in the Staging Preview - https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/staging/showcase/

Can you please take a look and fix/re-merge?

Thank you!
Kelly

**Comment by seakhtar** [comment]
Hi @kmonterr -

Looks like I set up the image filepath incorrectly... but in a very specific way that only affected the master branch. At least now I know how to avoid the same problem in the future! 

It looks like it's showing up correctly now- let me know if you see otherwise.

**Comment by kmonterr** [comment]
Looks great! Thanks, @seakhtar !
